// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type ClusterGroupMod interface {
	Apply(context.Context, *ClusterGroupTemplate)
}

type ClusterGroupModFunc func(context.Context, *ClusterGroupTemplate)

func (f ClusterGroupModFunc) Apply(ctx context.Context, n *ClusterGroupTemplate) {
	f(ctx, n)
}

type ClusterGroupModSlice []ClusterGroupMod

func (mods ClusterGroupModSlice) Apply(ctx context.Context, n *ClusterGroupTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ClusterGroupTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ClusterGroupTemplate struct {
	ID             func() uuid.UUID
	OrganizationID func() uuid.UUID
	Name           func() string
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time

	r clusterGroupR
	f *Factory

	alreadyPersisted bool
}

type clusterGroupR struct {
	Clusters     []*clusterGroupRClustersR
	Organization *clusterGroupROrganizationR
}

type clusterGroupRClustersR struct {
	number int
	o      *ClusterTemplate
}
type clusterGroupROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the ClusterGroupTemplate
func (o *ClusterGroupTemplate) Apply(ctx context.Context, mods ...ClusterGroupMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ClusterGroup
// according to the relationships in the template. Nothing is inserted into the db
func (t ClusterGroupTemplate) setModelRels(o *models.ClusterGroup) {
	if t.r.Clusters != nil {
		rel := models.ClusterSlice{}
		for _, r := range t.r.Clusters {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterGroupID = o.ID // h2
				rel.R.ClusterGroup = o
			}
			rel = append(rel, related...)
		}
		o.R.Clusters = rel
	}

	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.ClusterGroups = append(rel.R.ClusterGroups, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.ClusterGroupSetter
// this does nothing with the relationship templates
func (o ClusterGroupTemplate) BuildSetter() *models.ClusterGroupSetter {
	m := &models.ClusterGroupSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ClusterGroupSetter
// this does nothing with the relationship templates
func (o ClusterGroupTemplate) BuildManySetter(number int) []*models.ClusterGroupSetter {
	m := make([]*models.ClusterGroupSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ClusterGroup
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClusterGroupTemplate.Create
func (o ClusterGroupTemplate) Build() *models.ClusterGroup {
	m := &models.ClusterGroup{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ClusterGroupSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClusterGroupTemplate.CreateMany
func (o ClusterGroupTemplate) BuildMany(number int) models.ClusterGroupSlice {
	m := make(models.ClusterGroupSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableClusterGroup(m *models.ClusterGroupSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ClusterGroup
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ClusterGroupTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ClusterGroup) error {
	var err error

	isClustersDone, _ := clusterGroupRelClustersCtx.Value(ctx)
	if !isClustersDone && o.r.Clusters != nil {
		ctx = clusterGroupRelClustersCtx.WithValue(ctx, true)
		for _, r := range o.r.Clusters {
			if r.o.alreadyPersisted {
				m.R.Clusters = append(m.R.Clusters, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachClusters(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a clusterGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ClusterGroupTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ClusterGroup, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableClusterGroup(opt)

	if o.r.Organization == nil {
		ClusterGroupMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel1 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel1 = o.r.Organization.o.Build()
	} else {
		rel1, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel1.ID)

	m, err := models.ClusterGroups.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Organization = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a clusterGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ClusterGroupTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ClusterGroup {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a clusterGroup and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ClusterGroupTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ClusterGroup {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple clusterGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ClusterGroupTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ClusterGroupSlice, error) {
	var err error
	m := make(models.ClusterGroupSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple clusterGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ClusterGroupTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ClusterGroupSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple clusterGroups and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ClusterGroupTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ClusterGroupSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ClusterGroup has methods that act as mods for the ClusterGroupTemplate
var ClusterGroupMods clusterGroupMods

type clusterGroupMods struct{}

func (m clusterGroupMods) RandomizeAllColumns(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModSlice{
		ClusterGroupMods.RandomID(f),
		ClusterGroupMods.RandomOrganizationID(f),
		ClusterGroupMods.RandomName(f),
		ClusterGroupMods.RandomCreatedAt(f),
		ClusterGroupMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m clusterGroupMods) ID(val uuid.UUID) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m clusterGroupMods) IDFunc(f func() uuid.UUID) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m clusterGroupMods) UnsetID() ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterGroupMods) RandomID(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m clusterGroupMods) OrganizationID(val uuid.UUID) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m clusterGroupMods) OrganizationIDFunc(f func() uuid.UUID) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m clusterGroupMods) UnsetOrganizationID() ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterGroupMods) RandomOrganizationID(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m clusterGroupMods) Name(val string) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m clusterGroupMods) NameFunc(f func() string) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m clusterGroupMods) UnsetName() ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterGroupMods) RandomName(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m clusterGroupMods) CreatedAt(val time.Time) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m clusterGroupMods) CreatedAtFunc(f func() time.Time) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m clusterGroupMods) UnsetCreatedAt() ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterGroupMods) RandomCreatedAt(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m clusterGroupMods) UpdatedAt(val time.Time) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m clusterGroupMods) UpdatedAtFunc(f func() time.Time) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m clusterGroupMods) UnsetUpdatedAt() ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterGroupMods) RandomUpdatedAt(f *faker.Faker) ClusterGroupMod {
	return ClusterGroupModFunc(func(_ context.Context, o *ClusterGroupTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m clusterGroupMods) WithParentsCascading() ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		if isDone, _ := clusterGroupWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = clusterGroupWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m clusterGroupMods) WithOrganization(rel *OrganizationTemplate) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Organization = &clusterGroupROrganizationR{
			o: rel,
		}
	})
}

func (m clusterGroupMods) WithNewOrganization(mods ...OrganizationMod) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m clusterGroupMods) WithExistingOrganization(em *models.Organization) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Organization = &clusterGroupROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m clusterGroupMods) WithoutOrganization() ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Organization = nil
	})
}

func (m clusterGroupMods) WithClusters(number int, related *ClusterTemplate) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Clusters = []*clusterGroupRClustersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterGroupMods) WithNewClusters(number int, mods ...ClusterMod) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		related := o.f.NewClusterWithContext(ctx, mods...)
		m.WithClusters(number, related).Apply(ctx, o)
	})
}

func (m clusterGroupMods) AddClusters(number int, related *ClusterTemplate) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Clusters = append(o.r.Clusters, &clusterGroupRClustersR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterGroupMods) AddNewClusters(number int, mods ...ClusterMod) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		related := o.f.NewClusterWithContext(ctx, mods...)
		m.AddClusters(number, related).Apply(ctx, o)
	})
}

func (m clusterGroupMods) AddExistingClusters(existingModels ...*models.Cluster) ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		for _, em := range existingModels {
			o.r.Clusters = append(o.r.Clusters, &clusterGroupRClustersR{
				o: o.f.FromExistingCluster(em),
			})
		}
	})
}

func (m clusterGroupMods) WithoutClusters() ClusterGroupMod {
	return ClusterGroupModFunc(func(ctx context.Context, o *ClusterGroupTemplate) {
		o.r.Clusters = nil
	})
}
