// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type ClusterMod interface {
	Apply(context.Context, *ClusterTemplate)
}

type ClusterModFunc func(context.Context, *ClusterTemplate)

func (f ClusterModFunc) Apply(ctx context.Context, n *ClusterTemplate) {
	f(ctx, n)
}

type ClusterModSlice []ClusterMod

func (mods ClusterModSlice) Apply(ctx context.Context, n *ClusterTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ClusterTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ClusterTemplate struct {
	ID             func() uuid.UUID
	OrganizationID func() uuid.UUID
	ClusterGroupID func() uuid.UUID
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time
	LastObserved   func() time.Time

	r clusterR
	f *Factory

	alreadyPersisted bool
}

type clusterR struct {
	ClusterGroup          *clusterRClusterGroupR
	Organization          *clusterROrganizationR
	ClusterInfo           *clusterRClusterInfoR
	ClusterTags           []*clusterRClusterTagsR
	ClusterUpgrade        *clusterRClusterUpgradeR
	DeprecatedApis        []*clusterRDeprecatedApisR
	Objects               []*clusterRObjectsR
	UnmatchedComponents   []*clusterRUnmatchedComponentsR
	UpgradeableComponents []*clusterRUpgradeableComponentsR
}

type clusterRClusterGroupR struct {
	o *ClusterGroupTemplate
}
type clusterROrganizationR struct {
	o *OrganizationTemplate
}
type clusterRClusterInfoR struct {
	o *ClusterInfoTemplate
}
type clusterRClusterTagsR struct {
	number int
	o      *ClusterTagTemplate
}
type clusterRClusterUpgradeR struct {
	o *ClusterUpgradeTemplate
}
type clusterRDeprecatedApisR struct {
	number int
	o      *DeprecatedAPITemplate
}
type clusterRObjectsR struct {
	number int
	o      *ObjectTemplate
}
type clusterRUnmatchedComponentsR struct {
	number int
	o      *UnmatchedComponentTemplate
}
type clusterRUpgradeableComponentsR struct {
	number int
	o      *UpgradeableComponentTemplate
}

// Apply mods to the ClusterTemplate
func (o *ClusterTemplate) Apply(ctx context.Context, mods ...ClusterMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Cluster
// according to the relationships in the template. Nothing is inserted into the db
func (t ClusterTemplate) setModelRels(o *models.Cluster) {
	if t.r.ClusterGroup != nil {
		rel := t.r.ClusterGroup.o.Build()
		rel.R.Clusters = append(rel.R.Clusters, o)
		o.ClusterGroupID = rel.ID // h2
		o.R.ClusterGroup = rel
	}

	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.Clusters = append(rel.R.Clusters, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}

	if t.r.ClusterInfo != nil {
		rel := t.r.ClusterInfo.o.Build()
		rel.R.Cluster = o
		rel.ClusterID = o.ID // h2
		o.R.ClusterInfo = rel
	}

	if t.r.ClusterTags != nil {
		rel := models.ClusterTagSlice{}
		for _, r := range t.r.ClusterTags {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterID = o.ID // h2
				rel.R.Cluster = o
			}
			rel = append(rel, related...)
		}
		o.R.ClusterTags = rel
	}

	if t.r.ClusterUpgrade != nil {
		rel := t.r.ClusterUpgrade.o.Build()
		rel.R.Cluster = o
		rel.ClusterID = o.ID // h2
		o.R.ClusterUpgrade = rel
	}

	if t.r.DeprecatedApis != nil {
		rel := models.DeprecatedAPISlice{}
		for _, r := range t.r.DeprecatedApis {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterID = o.ID // h2
				rel.R.Cluster = o
			}
			rel = append(rel, related...)
		}
		o.R.DeprecatedApis = rel
	}

	if t.r.Objects != nil {
		rel := models.ObjectSlice{}
		for _, r := range t.r.Objects {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterID = o.ID // h2
				rel.R.Cluster = o
			}
			rel = append(rel, related...)
		}
		o.R.Objects = rel
	}

	if t.r.UnmatchedComponents != nil {
		rel := models.UnmatchedComponentSlice{}
		for _, r := range t.r.UnmatchedComponents {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterID = o.ID // h2
				rel.R.Cluster = o
			}
			rel = append(rel, related...)
		}
		o.R.UnmatchedComponents = rel
	}

	if t.r.UpgradeableComponents != nil {
		rel := models.UpgradeableComponentSlice{}
		for _, r := range t.r.UpgradeableComponents {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ClusterID = o.ID // h2
				rel.R.Cluster = o
			}
			rel = append(rel, related...)
		}
		o.R.UpgradeableComponents = rel
	}
}

// BuildSetter returns an *models.ClusterSetter
// this does nothing with the relationship templates
func (o ClusterTemplate) BuildSetter() *models.ClusterSetter {
	m := &models.ClusterSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.ClusterGroupID != nil {
		val := o.ClusterGroupID()
		m.ClusterGroupID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}
	if o.LastObserved != nil {
		val := o.LastObserved()
		m.LastObserved = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ClusterSetter
// this does nothing with the relationship templates
func (o ClusterTemplate) BuildManySetter(number int) []*models.ClusterSetter {
	m := make([]*models.ClusterSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Cluster
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClusterTemplate.Create
func (o ClusterTemplate) Build() *models.Cluster {
	m := &models.Cluster{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.ClusterGroupID != nil {
		m.ClusterGroupID = o.ClusterGroupID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.LastObserved != nil {
		m.LastObserved = o.LastObserved()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ClusterSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ClusterTemplate.CreateMany
func (o ClusterTemplate) BuildMany(number int) models.ClusterSlice {
	m := make(models.ClusterSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCluster(m *models.ClusterSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.ClusterGroupID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ClusterGroupID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Cluster
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ClusterTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Cluster) error {
	var err error

	isClusterInfoDone, _ := clusterRelClusterInfoCtx.Value(ctx)
	if !isClusterInfoDone && o.r.ClusterInfo != nil {
		ctx = clusterRelClusterInfoCtx.WithValue(ctx, true)
		if o.r.ClusterInfo.o.alreadyPersisted {
			m.R.ClusterInfo = o.r.ClusterInfo.o.Build()
		} else {
			var rel2 *models.ClusterInfo
			rel2, err = o.r.ClusterInfo.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachClusterInfo(ctx, exec, rel2)
			if err != nil {
				return err
			}
		}

	}

	isClusterTagsDone, _ := clusterRelClusterTagsCtx.Value(ctx)
	if !isClusterTagsDone && o.r.ClusterTags != nil {
		ctx = clusterRelClusterTagsCtx.WithValue(ctx, true)
		for _, r := range o.r.ClusterTags {
			if r.o.alreadyPersisted {
				m.R.ClusterTags = append(m.R.ClusterTags, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachClusterTags(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isClusterUpgradeDone, _ := clusterRelClusterUpgradeCtx.Value(ctx)
	if !isClusterUpgradeDone && o.r.ClusterUpgrade != nil {
		ctx = clusterRelClusterUpgradeCtx.WithValue(ctx, true)
		if o.r.ClusterUpgrade.o.alreadyPersisted {
			m.R.ClusterUpgrade = o.r.ClusterUpgrade.o.Build()
		} else {
			var rel4 *models.ClusterUpgrade
			rel4, err = o.r.ClusterUpgrade.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachClusterUpgrade(ctx, exec, rel4)
			if err != nil {
				return err
			}
		}

	}

	isDeprecatedApisDone, _ := clusterRelDeprecatedApisCtx.Value(ctx)
	if !isDeprecatedApisDone && o.r.DeprecatedApis != nil {
		ctx = clusterRelDeprecatedApisCtx.WithValue(ctx, true)
		for _, r := range o.r.DeprecatedApis {
			if r.o.alreadyPersisted {
				m.R.DeprecatedApis = append(m.R.DeprecatedApis, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachDeprecatedApis(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	isObjectsDone, _ := clusterRelObjectsCtx.Value(ctx)
	if !isObjectsDone && o.r.Objects != nil {
		ctx = clusterRelObjectsCtx.WithValue(ctx, true)
		for _, r := range o.r.Objects {
			if r.o.alreadyPersisted {
				m.R.Objects = append(m.R.Objects, r.o.Build())
			} else {
				rel6, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachObjects(ctx, exec, rel6...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUnmatchedComponentsDone, _ := clusterRelUnmatchedComponentsCtx.Value(ctx)
	if !isUnmatchedComponentsDone && o.r.UnmatchedComponents != nil {
		ctx = clusterRelUnmatchedComponentsCtx.WithValue(ctx, true)
		for _, r := range o.r.UnmatchedComponents {
			if r.o.alreadyPersisted {
				m.R.UnmatchedComponents = append(m.R.UnmatchedComponents, r.o.Build())
			} else {
				rel7, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUnmatchedComponents(ctx, exec, rel7...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpgradeableComponentsDone, _ := clusterRelUpgradeableComponentsCtx.Value(ctx)
	if !isUpgradeableComponentsDone && o.r.UpgradeableComponents != nil {
		ctx = clusterRelUpgradeableComponentsCtx.WithValue(ctx, true)
		for _, r := range o.r.UpgradeableComponents {
			if r.o.alreadyPersisted {
				m.R.UpgradeableComponents = append(m.R.UpgradeableComponents, r.o.Build())
			} else {
				rel8, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpgradeableComponents(ctx, exec, rel8...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a cluster and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ClusterTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Cluster, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCluster(opt)

	if o.r.ClusterGroup == nil {
		ClusterMods.WithNewClusterGroup().Apply(ctx, o)
	}

	var rel0 *models.ClusterGroup

	if o.r.ClusterGroup.o.alreadyPersisted {
		rel0 = o.r.ClusterGroup.o.Build()
	} else {
		rel0, err = o.r.ClusterGroup.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ClusterGroupID = omit.From(rel0.ID)

	if o.r.Organization == nil {
		ClusterMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel1 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel1 = o.r.Organization.o.Build()
	} else {
		rel1, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel1.ID)

	m, err := models.Clusters.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.ClusterGroup = rel0
	m.R.Organization = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a cluster and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ClusterTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Cluster {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a cluster and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ClusterTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Cluster {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple clusters and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ClusterTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ClusterSlice, error) {
	var err error
	m := make(models.ClusterSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple clusters and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ClusterTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ClusterSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple clusters and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ClusterTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ClusterSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Cluster has methods that act as mods for the ClusterTemplate
var ClusterMods clusterMods

type clusterMods struct{}

func (m clusterMods) RandomizeAllColumns(f *faker.Faker) ClusterMod {
	return ClusterModSlice{
		ClusterMods.RandomID(f),
		ClusterMods.RandomOrganizationID(f),
		ClusterMods.RandomClusterGroupID(f),
		ClusterMods.RandomCreatedAt(f),
		ClusterMods.RandomUpdatedAt(f),
		ClusterMods.RandomLastObserved(f),
	}
}

// Set the model columns to this value
func (m clusterMods) ID(val uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m clusterMods) IDFunc(f func() uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetID() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomID(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m clusterMods) OrganizationID(val uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m clusterMods) OrganizationIDFunc(f func() uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetOrganizationID() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomOrganizationID(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m clusterMods) ClusterGroupID(val uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ClusterGroupID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m clusterMods) ClusterGroupIDFunc(f func() uuid.UUID) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ClusterGroupID = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetClusterGroupID() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ClusterGroupID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomClusterGroupID(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.ClusterGroupID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m clusterMods) CreatedAt(val time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m clusterMods) CreatedAtFunc(f func() time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetCreatedAt() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomCreatedAt(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m clusterMods) UpdatedAt(val time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m clusterMods) UpdatedAtFunc(f func() time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetUpdatedAt() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomUpdatedAt(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m clusterMods) LastObserved(val time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.LastObserved = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m clusterMods) LastObservedFunc(f func() time.Time) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.LastObserved = f
	})
}

// Clear any values for the column
func (m clusterMods) UnsetLastObserved() ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.LastObserved = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m clusterMods) RandomLastObserved(f *faker.Faker) ClusterMod {
	return ClusterModFunc(func(_ context.Context, o *ClusterTemplate) {
		o.LastObserved = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m clusterMods) WithParentsCascading() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		if isDone, _ := clusterWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = clusterWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewClusterGroupWithContext(ctx, ClusterGroupMods.WithParentsCascading())
			m.WithClusterGroup(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
		{

			related := o.f.NewClusterInfoWithContext(ctx, ClusterInfoMods.WithParentsCascading())
			m.WithClusterInfo(related).Apply(ctx, o)
		}
		{

			related := o.f.NewClusterUpgradeWithContext(ctx, ClusterUpgradeMods.WithParentsCascading())
			m.WithClusterUpgrade(related).Apply(ctx, o)
		}
	})
}

func (m clusterMods) WithClusterGroup(rel *ClusterGroupTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterGroup = &clusterRClusterGroupR{
			o: rel,
		}
	})
}

func (m clusterMods) WithNewClusterGroup(mods ...ClusterGroupMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewClusterGroupWithContext(ctx, mods...)

		m.WithClusterGroup(related).Apply(ctx, o)
	})
}

func (m clusterMods) WithExistingClusterGroup(em *models.ClusterGroup) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterGroup = &clusterRClusterGroupR{
			o: o.f.FromExistingClusterGroup(em),
		}
	})
}

func (m clusterMods) WithoutClusterGroup() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterGroup = nil
	})
}

func (m clusterMods) WithOrganization(rel *OrganizationTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Organization = &clusterROrganizationR{
			o: rel,
		}
	})
}

func (m clusterMods) WithNewOrganization(mods ...OrganizationMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m clusterMods) WithExistingOrganization(em *models.Organization) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Organization = &clusterROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m clusterMods) WithoutOrganization() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Organization = nil
	})
}

func (m clusterMods) WithClusterInfo(rel *ClusterInfoTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterInfo = &clusterRClusterInfoR{
			o: rel,
		}
	})
}

func (m clusterMods) WithNewClusterInfo(mods ...ClusterInfoMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewClusterInfoWithContext(ctx, mods...)

		m.WithClusterInfo(related).Apply(ctx, o)
	})
}

func (m clusterMods) WithExistingClusterInfo(em *models.ClusterInfo) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterInfo = &clusterRClusterInfoR{
			o: o.f.FromExistingClusterInfo(em),
		}
	})
}

func (m clusterMods) WithoutClusterInfo() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterInfo = nil
	})
}

func (m clusterMods) WithClusterUpgrade(rel *ClusterUpgradeTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterUpgrade = &clusterRClusterUpgradeR{
			o: rel,
		}
	})
}

func (m clusterMods) WithNewClusterUpgrade(mods ...ClusterUpgradeMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewClusterUpgradeWithContext(ctx, mods...)

		m.WithClusterUpgrade(related).Apply(ctx, o)
	})
}

func (m clusterMods) WithExistingClusterUpgrade(em *models.ClusterUpgrade) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterUpgrade = &clusterRClusterUpgradeR{
			o: o.f.FromExistingClusterUpgrade(em),
		}
	})
}

func (m clusterMods) WithoutClusterUpgrade() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterUpgrade = nil
	})
}

func (m clusterMods) WithClusterTags(number int, related *ClusterTagTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterTags = []*clusterRClusterTagsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterMods) WithNewClusterTags(number int, mods ...ClusterTagMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewClusterTagWithContext(ctx, mods...)
		m.WithClusterTags(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddClusterTags(number int, related *ClusterTagTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterTags = append(o.r.ClusterTags, &clusterRClusterTagsR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterMods) AddNewClusterTags(number int, mods ...ClusterTagMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewClusterTagWithContext(ctx, mods...)
		m.AddClusterTags(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddExistingClusterTags(existingModels ...*models.ClusterTag) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		for _, em := range existingModels {
			o.r.ClusterTags = append(o.r.ClusterTags, &clusterRClusterTagsR{
				o: o.f.FromExistingClusterTag(em),
			})
		}
	})
}

func (m clusterMods) WithoutClusterTags() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.ClusterTags = nil
	})
}

func (m clusterMods) WithDeprecatedApis(number int, related *DeprecatedAPITemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.DeprecatedApis = []*clusterRDeprecatedApisR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterMods) WithNewDeprecatedApis(number int, mods ...DeprecatedAPIMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewDeprecatedAPIWithContext(ctx, mods...)
		m.WithDeprecatedApis(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddDeprecatedApis(number int, related *DeprecatedAPITemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.DeprecatedApis = append(o.r.DeprecatedApis, &clusterRDeprecatedApisR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterMods) AddNewDeprecatedApis(number int, mods ...DeprecatedAPIMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewDeprecatedAPIWithContext(ctx, mods...)
		m.AddDeprecatedApis(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddExistingDeprecatedApis(existingModels ...*models.DeprecatedAPI) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		for _, em := range existingModels {
			o.r.DeprecatedApis = append(o.r.DeprecatedApis, &clusterRDeprecatedApisR{
				o: o.f.FromExistingDeprecatedAPI(em),
			})
		}
	})
}

func (m clusterMods) WithoutDeprecatedApis() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.DeprecatedApis = nil
	})
}

func (m clusterMods) WithObjects(number int, related *ObjectTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Objects = []*clusterRObjectsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterMods) WithNewObjects(number int, mods ...ObjectMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewObjectWithContext(ctx, mods...)
		m.WithObjects(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddObjects(number int, related *ObjectTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Objects = append(o.r.Objects, &clusterRObjectsR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterMods) AddNewObjects(number int, mods ...ObjectMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewObjectWithContext(ctx, mods...)
		m.AddObjects(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddExistingObjects(existingModels ...*models.Object) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		for _, em := range existingModels {
			o.r.Objects = append(o.r.Objects, &clusterRObjectsR{
				o: o.f.FromExistingObject(em),
			})
		}
	})
}

func (m clusterMods) WithoutObjects() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.Objects = nil
	})
}

func (m clusterMods) WithUnmatchedComponents(number int, related *UnmatchedComponentTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UnmatchedComponents = []*clusterRUnmatchedComponentsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterMods) WithNewUnmatchedComponents(number int, mods ...UnmatchedComponentMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewUnmatchedComponentWithContext(ctx, mods...)
		m.WithUnmatchedComponents(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddUnmatchedComponents(number int, related *UnmatchedComponentTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UnmatchedComponents = append(o.r.UnmatchedComponents, &clusterRUnmatchedComponentsR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterMods) AddNewUnmatchedComponents(number int, mods ...UnmatchedComponentMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewUnmatchedComponentWithContext(ctx, mods...)
		m.AddUnmatchedComponents(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddExistingUnmatchedComponents(existingModels ...*models.UnmatchedComponent) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		for _, em := range existingModels {
			o.r.UnmatchedComponents = append(o.r.UnmatchedComponents, &clusterRUnmatchedComponentsR{
				o: o.f.FromExistingUnmatchedComponent(em),
			})
		}
	})
}

func (m clusterMods) WithoutUnmatchedComponents() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UnmatchedComponents = nil
	})
}

func (m clusterMods) WithUpgradeableComponents(number int, related *UpgradeableComponentTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UpgradeableComponents = []*clusterRUpgradeableComponentsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m clusterMods) WithNewUpgradeableComponents(number int, mods ...UpgradeableComponentMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewUpgradeableComponentWithContext(ctx, mods...)
		m.WithUpgradeableComponents(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddUpgradeableComponents(number int, related *UpgradeableComponentTemplate) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UpgradeableComponents = append(o.r.UpgradeableComponents, &clusterRUpgradeableComponentsR{
			number: number,
			o:      related,
		})
	})
}

func (m clusterMods) AddNewUpgradeableComponents(number int, mods ...UpgradeableComponentMod) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		related := o.f.NewUpgradeableComponentWithContext(ctx, mods...)
		m.AddUpgradeableComponents(number, related).Apply(ctx, o)
	})
}

func (m clusterMods) AddExistingUpgradeableComponents(existingModels ...*models.UpgradeableComponent) ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		for _, em := range existingModels {
			o.r.UpgradeableComponents = append(o.r.UpgradeableComponents, &clusterRUpgradeableComponentsR{
				o: o.f.FromExistingUpgradeableComponent(em),
			})
		}
	})
}

func (m clusterMods) WithoutUpgradeableComponents() ClusterMod {
	return ClusterModFunc(func(ctx context.Context, o *ClusterTemplate) {
		o.r.UpgradeableComponents = nil
	})
}
