// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type DeprecatedAPIMod interface {
	Apply(context.Context, *DeprecatedAPITemplate)
}

type DeprecatedAPIModFunc func(context.Context, *DeprecatedAPITemplate)

func (f DeprecatedAPIModFunc) Apply(ctx context.Context, n *DeprecatedAPITemplate) {
	f(ctx, n)
}

type DeprecatedAPIModSlice []DeprecatedAPIMod

func (mods DeprecatedAPIModSlice) Apply(ctx context.Context, n *DeprecatedAPITemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// DeprecatedAPITemplate is an object representing the database table.
// all columns are optional and should be set by mods
type DeprecatedAPITemplate struct {
	ClusterID           func() uuid.UUID
	OrganizationID      func() uuid.UUID
	CurrentGroupVersion func() string
	Kind                func() string
	Name                func() string
	ClusterK8SVersion   func() string
	Deprecated          func() bool
	DeprecatedIn        func() string
	RemovedIn           func() string
	ReplacementVersion  func() string

	r deprecatedAPIR
	f *Factory

	alreadyPersisted bool
}

type deprecatedAPIR struct {
	Cluster      *deprecatedAPIRClusterR
	Organization *deprecatedAPIROrganizationR
}

type deprecatedAPIRClusterR struct {
	o *ClusterTemplate
}
type deprecatedAPIROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the DeprecatedAPITemplate
func (o *DeprecatedAPITemplate) Apply(ctx context.Context, mods ...DeprecatedAPIMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.DeprecatedAPI
// according to the relationships in the template. Nothing is inserted into the db
func (t DeprecatedAPITemplate) setModelRels(o *models.DeprecatedAPI) {
	if t.r.Cluster != nil {
		rel := t.r.Cluster.o.Build()
		rel.R.DeprecatedApis = append(rel.R.DeprecatedApis, o)
		o.ClusterID = rel.ID // h2
		o.R.Cluster = rel
	}

	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.DeprecatedApis = append(rel.R.DeprecatedApis, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.DeprecatedAPISetter
// this does nothing with the relationship templates
func (o DeprecatedAPITemplate) BuildSetter() *models.DeprecatedAPISetter {
	m := &models.DeprecatedAPISetter{}

	if o.ClusterID != nil {
		val := o.ClusterID()
		m.ClusterID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.CurrentGroupVersion != nil {
		val := o.CurrentGroupVersion()
		m.CurrentGroupVersion = omit.From(val)
	}
	if o.Kind != nil {
		val := o.Kind()
		m.Kind = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.ClusterK8SVersion != nil {
		val := o.ClusterK8SVersion()
		m.ClusterK8SVersion = omit.From(val)
	}
	if o.Deprecated != nil {
		val := o.Deprecated()
		m.Deprecated = omit.From(val)
	}
	if o.DeprecatedIn != nil {
		val := o.DeprecatedIn()
		m.DeprecatedIn = omit.From(val)
	}
	if o.RemovedIn != nil {
		val := o.RemovedIn()
		m.RemovedIn = omit.From(val)
	}
	if o.ReplacementVersion != nil {
		val := o.ReplacementVersion()
		m.ReplacementVersion = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.DeprecatedAPISetter
// this does nothing with the relationship templates
func (o DeprecatedAPITemplate) BuildManySetter(number int) []*models.DeprecatedAPISetter {
	m := make([]*models.DeprecatedAPISetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.DeprecatedAPI
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DeprecatedAPITemplate.Create
func (o DeprecatedAPITemplate) Build() *models.DeprecatedAPI {
	m := &models.DeprecatedAPI{}

	if o.ClusterID != nil {
		m.ClusterID = o.ClusterID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.CurrentGroupVersion != nil {
		m.CurrentGroupVersion = o.CurrentGroupVersion()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.ClusterK8SVersion != nil {
		m.ClusterK8SVersion = o.ClusterK8SVersion()
	}
	if o.Deprecated != nil {
		m.Deprecated = o.Deprecated()
	}
	if o.DeprecatedIn != nil {
		m.DeprecatedIn = o.DeprecatedIn()
	}
	if o.RemovedIn != nil {
		m.RemovedIn = o.RemovedIn()
	}
	if o.ReplacementVersion != nil {
		m.ReplacementVersion = o.ReplacementVersion()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.DeprecatedAPISlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DeprecatedAPITemplate.CreateMany
func (o DeprecatedAPITemplate) BuildMany(number int) models.DeprecatedAPISlice {
	m := make(models.DeprecatedAPISlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableDeprecatedAPI(m *models.DeprecatedAPISetter) {
	if !(m.ClusterID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ClusterID = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.CurrentGroupVersion.IsValue()) {
		val := random_string(nil)
		m.CurrentGroupVersion = omit.From(val)
	}
	if !(m.Kind.IsValue()) {
		val := random_string(nil)
		m.Kind = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.ClusterK8SVersion.IsValue()) {
		val := random_string(nil)
		m.ClusterK8SVersion = omit.From(val)
	}
	if !(m.Deprecated.IsValue()) {
		val := random_bool(nil)
		m.Deprecated = omit.From(val)
	}
	if !(m.DeprecatedIn.IsValue()) {
		val := random_string(nil)
		m.DeprecatedIn = omit.From(val)
	}
	if !(m.RemovedIn.IsValue()) {
		val := random_string(nil)
		m.RemovedIn = omit.From(val)
	}
	if !(m.ReplacementVersion.IsValue()) {
		val := random_string(nil)
		m.ReplacementVersion = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.DeprecatedAPI
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *DeprecatedAPITemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.DeprecatedAPI) error {
	var err error

	return err
}

// Create builds a deprecatedAPI and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *DeprecatedAPITemplate) Create(ctx context.Context, exec bob.Executor) (*models.DeprecatedAPI, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableDeprecatedAPI(opt)

	if o.r.Cluster == nil {
		DeprecatedAPIMods.WithNewCluster().Apply(ctx, o)
	}

	var rel0 *models.Cluster

	if o.r.Cluster.o.alreadyPersisted {
		rel0 = o.r.Cluster.o.Build()
	} else {
		rel0, err = o.r.Cluster.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.ClusterID = omit.From(rel0.ID)

	if o.r.Organization == nil {
		DeprecatedAPIMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel1 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel1 = o.r.Organization.o.Build()
	} else {
		rel1, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel1.ID)

	m, err := models.DeprecatedApis.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Cluster = rel0
	m.R.Organization = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a deprecatedAPI and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *DeprecatedAPITemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.DeprecatedAPI {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a deprecatedAPI and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *DeprecatedAPITemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.DeprecatedAPI {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple deprecatedApis and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o DeprecatedAPITemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.DeprecatedAPISlice, error) {
	var err error
	m := make(models.DeprecatedAPISlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple deprecatedApis and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o DeprecatedAPITemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.DeprecatedAPISlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple deprecatedApis and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o DeprecatedAPITemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.DeprecatedAPISlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// DeprecatedAPI has methods that act as mods for the DeprecatedAPITemplate
var DeprecatedAPIMods deprecatedAPIMods

type deprecatedAPIMods struct{}

func (m deprecatedAPIMods) RandomizeAllColumns(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModSlice{
		DeprecatedAPIMods.RandomClusterID(f),
		DeprecatedAPIMods.RandomOrganizationID(f),
		DeprecatedAPIMods.RandomCurrentGroupVersion(f),
		DeprecatedAPIMods.RandomKind(f),
		DeprecatedAPIMods.RandomName(f),
		DeprecatedAPIMods.RandomClusterK8SVersion(f),
		DeprecatedAPIMods.RandomDeprecated(f),
		DeprecatedAPIMods.RandomDeprecatedIn(f),
		DeprecatedAPIMods.RandomRemovedIn(f),
		DeprecatedAPIMods.RandomReplacementVersion(f),
	}
}

// Set the model columns to this value
func (m deprecatedAPIMods) ClusterID(val uuid.UUID) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) ClusterIDFunc(f func() uuid.UUID) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterID = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetClusterID() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomClusterID(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) OrganizationID(val uuid.UUID) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) OrganizationIDFunc(f func() uuid.UUID) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetOrganizationID() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomOrganizationID(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) CurrentGroupVersion(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.CurrentGroupVersion = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) CurrentGroupVersionFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.CurrentGroupVersion = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetCurrentGroupVersion() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.CurrentGroupVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomCurrentGroupVersion(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.CurrentGroupVersion = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) Kind(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) KindFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetKind() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomKind(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) Name(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) NameFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetName() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomName(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) ClusterK8SVersion(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterK8SVersion = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) ClusterK8SVersionFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterK8SVersion = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetClusterK8SVersion() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterK8SVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomClusterK8SVersion(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ClusterK8SVersion = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) Deprecated(val bool) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Deprecated = func() bool { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) DeprecatedFunc(f func() bool) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Deprecated = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetDeprecated() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Deprecated = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomDeprecated(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.Deprecated = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) DeprecatedIn(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.DeprecatedIn = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) DeprecatedInFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.DeprecatedIn = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetDeprecatedIn() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.DeprecatedIn = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomDeprecatedIn(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.DeprecatedIn = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) RemovedIn(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.RemovedIn = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) RemovedInFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.RemovedIn = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetRemovedIn() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.RemovedIn = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomRemovedIn(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.RemovedIn = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m deprecatedAPIMods) ReplacementVersion(val string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ReplacementVersion = func() string { return val }
	})
}

// Set the Column from the function
func (m deprecatedAPIMods) ReplacementVersionFunc(f func() string) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ReplacementVersion = f
	})
}

// Clear any values for the column
func (m deprecatedAPIMods) UnsetReplacementVersion() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ReplacementVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m deprecatedAPIMods) RandomReplacementVersion(f *faker.Faker) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(_ context.Context, o *DeprecatedAPITemplate) {
		o.ReplacementVersion = func() string {
			return random_string(f)
		}
	})
}

func (m deprecatedAPIMods) WithParentsCascading() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		if isDone, _ := deprecatedAPIWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = deprecatedAPIWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewClusterWithContext(ctx, ClusterMods.WithParentsCascading())
			m.WithCluster(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m deprecatedAPIMods) WithCluster(rel *ClusterTemplate) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Cluster = &deprecatedAPIRClusterR{
			o: rel,
		}
	})
}

func (m deprecatedAPIMods) WithNewCluster(mods ...ClusterMod) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		related := o.f.NewClusterWithContext(ctx, mods...)

		m.WithCluster(related).Apply(ctx, o)
	})
}

func (m deprecatedAPIMods) WithExistingCluster(em *models.Cluster) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Cluster = &deprecatedAPIRClusterR{
			o: o.f.FromExistingCluster(em),
		}
	})
}

func (m deprecatedAPIMods) WithoutCluster() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Cluster = nil
	})
}

func (m deprecatedAPIMods) WithOrganization(rel *OrganizationTemplate) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Organization = &deprecatedAPIROrganizationR{
			o: rel,
		}
	})
}

func (m deprecatedAPIMods) WithNewOrganization(mods ...OrganizationMod) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m deprecatedAPIMods) WithExistingOrganization(em *models.Organization) DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Organization = &deprecatedAPIROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m deprecatedAPIMods) WithoutOrganization() DeprecatedAPIMod {
	return DeprecatedAPIModFunc(func(ctx context.Context, o *DeprecatedAPITemplate) {
		o.r.Organization = nil
	})
}
