// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type EmailVerificationTokenMod interface {
	Apply(context.Context, *EmailVerificationTokenTemplate)
}

type EmailVerificationTokenModFunc func(context.Context, *EmailVerificationTokenTemplate)

func (f EmailVerificationTokenModFunc) Apply(ctx context.Context, n *EmailVerificationTokenTemplate) {
	f(ctx, n)
}

type EmailVerificationTokenModSlice []EmailVerificationTokenMod

func (mods EmailVerificationTokenModSlice) Apply(ctx context.Context, n *EmailVerificationTokenTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// EmailVerificationTokenTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type EmailVerificationTokenTemplate struct {
	Email      func() string
	Value      func() uuid.UUID
	Expiration func() time.Time
	CreatedAt  func() time.Time
	UpdatedAt  func() time.Time

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the EmailVerificationTokenTemplate
func (o *EmailVerificationTokenTemplate) Apply(ctx context.Context, mods ...EmailVerificationTokenMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.EmailVerificationToken
// according to the relationships in the template. Nothing is inserted into the db
func (t EmailVerificationTokenTemplate) setModelRels(o *models.EmailVerificationToken) {}

// BuildSetter returns an *models.EmailVerificationTokenSetter
// this does nothing with the relationship templates
func (o EmailVerificationTokenTemplate) BuildSetter() *models.EmailVerificationTokenSetter {
	m := &models.EmailVerificationTokenSetter{}

	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Value != nil {
		val := o.Value()
		m.Value = omit.From(val)
	}
	if o.Expiration != nil {
		val := o.Expiration()
		m.Expiration = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.EmailVerificationTokenSetter
// this does nothing with the relationship templates
func (o EmailVerificationTokenTemplate) BuildManySetter(number int) []*models.EmailVerificationTokenSetter {
	m := make([]*models.EmailVerificationTokenSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.EmailVerificationToken
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EmailVerificationTokenTemplate.Create
func (o EmailVerificationTokenTemplate) Build() *models.EmailVerificationToken {
	m := &models.EmailVerificationToken{}

	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Value != nil {
		m.Value = o.Value()
	}
	if o.Expiration != nil {
		m.Expiration = o.Expiration()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.EmailVerificationTokenSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use EmailVerificationTokenTemplate.CreateMany
func (o EmailVerificationTokenTemplate) BuildMany(number int) models.EmailVerificationTokenSlice {
	m := make(models.EmailVerificationTokenSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableEmailVerificationToken(m *models.EmailVerificationTokenSetter) {
	if !(m.Email.IsValue()) {
		val := random_string(nil)
		m.Email = omit.From(val)
	}
	if !(m.Value.IsValue()) {
		val := random_uuid_UUID(nil)
		m.Value = omit.From(val)
	}
	if !(m.Expiration.IsValue()) {
		val := random_time_Time(nil)
		m.Expiration = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.EmailVerificationToken
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *EmailVerificationTokenTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.EmailVerificationToken) error {
	var err error

	return err
}

// Create builds a emailVerificationToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *EmailVerificationTokenTemplate) Create(ctx context.Context, exec bob.Executor) (*models.EmailVerificationToken, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableEmailVerificationToken(opt)

	m, err := models.EmailVerificationTokens.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a emailVerificationToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *EmailVerificationTokenTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.EmailVerificationToken {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a emailVerificationToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *EmailVerificationTokenTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.EmailVerificationToken {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple emailVerificationTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o EmailVerificationTokenTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.EmailVerificationTokenSlice, error) {
	var err error
	m := make(models.EmailVerificationTokenSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple emailVerificationTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o EmailVerificationTokenTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.EmailVerificationTokenSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple emailVerificationTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o EmailVerificationTokenTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.EmailVerificationTokenSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// EmailVerificationToken has methods that act as mods for the EmailVerificationTokenTemplate
var EmailVerificationTokenMods emailVerificationTokenMods

type emailVerificationTokenMods struct{}

func (m emailVerificationTokenMods) RandomizeAllColumns(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModSlice{
		EmailVerificationTokenMods.RandomEmail(f),
		EmailVerificationTokenMods.RandomValue(f),
		EmailVerificationTokenMods.RandomExpiration(f),
		EmailVerificationTokenMods.RandomCreatedAt(f),
		EmailVerificationTokenMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m emailVerificationTokenMods) Email(val string) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m emailVerificationTokenMods) EmailFunc(f func() string) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m emailVerificationTokenMods) UnsetEmail() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationTokenMods) RandomEmail(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Email = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationTokenMods) Value(val uuid.UUID) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Value = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m emailVerificationTokenMods) ValueFunc(f func() uuid.UUID) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Value = f
	})
}

// Clear any values for the column
func (m emailVerificationTokenMods) UnsetValue() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Value = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationTokenMods) RandomValue(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Value = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationTokenMods) Expiration(val time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Expiration = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m emailVerificationTokenMods) ExpirationFunc(f func() time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Expiration = f
	})
}

// Clear any values for the column
func (m emailVerificationTokenMods) UnsetExpiration() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Expiration = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationTokenMods) RandomExpiration(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.Expiration = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationTokenMods) CreatedAt(val time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m emailVerificationTokenMods) CreatedAtFunc(f func() time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m emailVerificationTokenMods) UnsetCreatedAt() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationTokenMods) RandomCreatedAt(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m emailVerificationTokenMods) UpdatedAt(val time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m emailVerificationTokenMods) UpdatedAtFunc(f func() time.Time) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m emailVerificationTokenMods) UnsetUpdatedAt() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m emailVerificationTokenMods) RandomUpdatedAt(f *faker.Faker) EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(_ context.Context, o *EmailVerificationTokenTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m emailVerificationTokenMods) WithParentsCascading() EmailVerificationTokenMod {
	return EmailVerificationTokenModFunc(func(ctx context.Context, o *EmailVerificationTokenTemplate) {
		if isDone, _ := emailVerificationTokenWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = emailVerificationTokenWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
