// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type ForgotPasswordTokenMod interface {
	Apply(context.Context, *ForgotPasswordTokenTemplate)
}

type ForgotPasswordTokenModFunc func(context.Context, *ForgotPasswordTokenTemplate)

func (f ForgotPasswordTokenModFunc) Apply(ctx context.Context, n *ForgotPasswordTokenTemplate) {
	f(ctx, n)
}

type ForgotPasswordTokenModSlice []ForgotPasswordTokenMod

func (mods ForgotPasswordTokenModSlice) Apply(ctx context.Context, n *ForgotPasswordTokenTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ForgotPasswordTokenTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ForgotPasswordTokenTemplate struct {
	UserID     func() uuid.UUID
	Value      func() uuid.UUID
	Expiration func() time.Time
	CreatedAt  func() time.Time
	UpdatedAt  func() time.Time

	r forgotPasswordTokenR
	f *Factory

	alreadyPersisted bool
}

type forgotPasswordTokenR struct {
	UserUserAccount *forgotPasswordTokenRUserUserAccountR
}

type forgotPasswordTokenRUserUserAccountR struct {
	o *UserAccountTemplate
}

// Apply mods to the ForgotPasswordTokenTemplate
func (o *ForgotPasswordTokenTemplate) Apply(ctx context.Context, mods ...ForgotPasswordTokenMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ForgotPasswordToken
// according to the relationships in the template. Nothing is inserted into the db
func (t ForgotPasswordTokenTemplate) setModelRels(o *models.ForgotPasswordToken) {
	if t.r.UserUserAccount != nil {
		rel := t.r.UserUserAccount.o.Build()
		rel.R.UserForgotPasswordToken = o
		o.UserID = rel.ID // h2
		o.R.UserUserAccount = rel
	}
}

// BuildSetter returns an *models.ForgotPasswordTokenSetter
// this does nothing with the relationship templates
func (o ForgotPasswordTokenTemplate) BuildSetter() *models.ForgotPasswordTokenSetter {
	m := &models.ForgotPasswordTokenSetter{}

	if o.UserID != nil {
		val := o.UserID()
		m.UserID = omit.From(val)
	}
	if o.Value != nil {
		val := o.Value()
		m.Value = omit.From(val)
	}
	if o.Expiration != nil {
		val := o.Expiration()
		m.Expiration = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ForgotPasswordTokenSetter
// this does nothing with the relationship templates
func (o ForgotPasswordTokenTemplate) BuildManySetter(number int) []*models.ForgotPasswordTokenSetter {
	m := make([]*models.ForgotPasswordTokenSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ForgotPasswordToken
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForgotPasswordTokenTemplate.Create
func (o ForgotPasswordTokenTemplate) Build() *models.ForgotPasswordToken {
	m := &models.ForgotPasswordToken{}

	if o.UserID != nil {
		m.UserID = o.UserID()
	}
	if o.Value != nil {
		m.Value = o.Value()
	}
	if o.Expiration != nil {
		m.Expiration = o.Expiration()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ForgotPasswordTokenSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ForgotPasswordTokenTemplate.CreateMany
func (o ForgotPasswordTokenTemplate) BuildMany(number int) models.ForgotPasswordTokenSlice {
	m := make(models.ForgotPasswordTokenSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableForgotPasswordToken(m *models.ForgotPasswordTokenSetter) {
	if !(m.UserID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.UserID = omit.From(val)
	}
	if !(m.Value.IsValue()) {
		val := random_uuid_UUID(nil)
		m.Value = omit.From(val)
	}
	if !(m.Expiration.IsValue()) {
		val := random_time_Time(nil)
		m.Expiration = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ForgotPasswordToken
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ForgotPasswordTokenTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ForgotPasswordToken) error {
	var err error

	return err
}

// Create builds a forgotPasswordToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ForgotPasswordTokenTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ForgotPasswordToken, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableForgotPasswordToken(opt)

	if o.r.UserUserAccount == nil {
		ForgotPasswordTokenMods.WithNewUserUserAccount().Apply(ctx, o)
	}

	var rel0 *models.UserAccount

	if o.r.UserUserAccount.o.alreadyPersisted {
		rel0 = o.r.UserUserAccount.o.Build()
	} else {
		rel0, err = o.r.UserUserAccount.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.UserID = omit.From(rel0.ID)

	m, err := models.ForgotPasswordTokens.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.UserUserAccount = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a forgotPasswordToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ForgotPasswordTokenTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ForgotPasswordToken {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a forgotPasswordToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ForgotPasswordTokenTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ForgotPasswordToken {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple forgotPasswordTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ForgotPasswordTokenTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ForgotPasswordTokenSlice, error) {
	var err error
	m := make(models.ForgotPasswordTokenSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple forgotPasswordTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ForgotPasswordTokenTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ForgotPasswordTokenSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple forgotPasswordTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ForgotPasswordTokenTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ForgotPasswordTokenSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ForgotPasswordToken has methods that act as mods for the ForgotPasswordTokenTemplate
var ForgotPasswordTokenMods forgotPasswordTokenMods

type forgotPasswordTokenMods struct{}

func (m forgotPasswordTokenMods) RandomizeAllColumns(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModSlice{
		ForgotPasswordTokenMods.RandomUserID(f),
		ForgotPasswordTokenMods.RandomValue(f),
		ForgotPasswordTokenMods.RandomExpiration(f),
		ForgotPasswordTokenMods.RandomCreatedAt(f),
		ForgotPasswordTokenMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m forgotPasswordTokenMods) UserID(val uuid.UUID) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UserID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m forgotPasswordTokenMods) UserIDFunc(f func() uuid.UUID) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UserID = f
	})
}

// Clear any values for the column
func (m forgotPasswordTokenMods) UnsetUserID() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UserID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forgotPasswordTokenMods) RandomUserID(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UserID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m forgotPasswordTokenMods) Value(val uuid.UUID) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Value = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m forgotPasswordTokenMods) ValueFunc(f func() uuid.UUID) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Value = f
	})
}

// Clear any values for the column
func (m forgotPasswordTokenMods) UnsetValue() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Value = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forgotPasswordTokenMods) RandomValue(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Value = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m forgotPasswordTokenMods) Expiration(val time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Expiration = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forgotPasswordTokenMods) ExpirationFunc(f func() time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Expiration = f
	})
}

// Clear any values for the column
func (m forgotPasswordTokenMods) UnsetExpiration() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Expiration = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forgotPasswordTokenMods) RandomExpiration(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.Expiration = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m forgotPasswordTokenMods) CreatedAt(val time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forgotPasswordTokenMods) CreatedAtFunc(f func() time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m forgotPasswordTokenMods) UnsetCreatedAt() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forgotPasswordTokenMods) RandomCreatedAt(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m forgotPasswordTokenMods) UpdatedAt(val time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m forgotPasswordTokenMods) UpdatedAtFunc(f func() time.Time) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m forgotPasswordTokenMods) UnsetUpdatedAt() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m forgotPasswordTokenMods) RandomUpdatedAt(f *faker.Faker) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(_ context.Context, o *ForgotPasswordTokenTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m forgotPasswordTokenMods) WithParentsCascading() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(ctx context.Context, o *ForgotPasswordTokenTemplate) {
		if isDone, _ := forgotPasswordTokenWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = forgotPasswordTokenWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserAccountWithContext(ctx, UserAccountMods.WithParentsCascading())
			m.WithUserUserAccount(related).Apply(ctx, o)
		}
	})
}

func (m forgotPasswordTokenMods) WithUserUserAccount(rel *UserAccountTemplate) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(ctx context.Context, o *ForgotPasswordTokenTemplate) {
		o.r.UserUserAccount = &forgotPasswordTokenRUserUserAccountR{
			o: rel,
		}
	})
}

func (m forgotPasswordTokenMods) WithNewUserUserAccount(mods ...UserAccountMod) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(ctx context.Context, o *ForgotPasswordTokenTemplate) {
		related := o.f.NewUserAccountWithContext(ctx, mods...)

		m.WithUserUserAccount(related).Apply(ctx, o)
	})
}

func (m forgotPasswordTokenMods) WithExistingUserUserAccount(em *models.UserAccount) ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(ctx context.Context, o *ForgotPasswordTokenTemplate) {
		o.r.UserUserAccount = &forgotPasswordTokenRUserUserAccountR{
			o: o.f.FromExistingUserAccount(em),
		}
	})
}

func (m forgotPasswordTokenMods) WithoutUserUserAccount() ForgotPasswordTokenMod {
	return ForgotPasswordTokenModFunc(func(ctx context.Context, o *ForgotPasswordTokenTemplate) {
		o.r.UserUserAccount = nil
	})
}
