// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type InvitedUserMod interface {
	Apply(context.Context, *InvitedUserTemplate)
}

type InvitedUserModFunc func(context.Context, *InvitedUserTemplate)

func (f InvitedUserModFunc) Apply(ctx context.Context, n *InvitedUserTemplate) {
	f(ctx, n)
}

type InvitedUserModSlice []InvitedUserMod

func (mods InvitedUserModSlice) Apply(ctx context.Context, n *InvitedUserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// InvitedUserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type InvitedUserTemplate struct {
	Email          func() string
	OrganizationID func() uuid.UUID
	RoleName       func() string
	Expiration     func() time.Time
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time

	r invitedUserR
	f *Factory

	alreadyPersisted bool
}

type invitedUserR struct {
	Organization *invitedUserROrganizationR
}

type invitedUserROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the InvitedUserTemplate
func (o *InvitedUserTemplate) Apply(ctx context.Context, mods ...InvitedUserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.InvitedUser
// according to the relationships in the template. Nothing is inserted into the db
func (t InvitedUserTemplate) setModelRels(o *models.InvitedUser) {
	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.InvitedUsers = append(rel.R.InvitedUsers, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.InvitedUserSetter
// this does nothing with the relationship templates
func (o InvitedUserTemplate) BuildSetter() *models.InvitedUserSetter {
	m := &models.InvitedUserSetter{}

	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.RoleName != nil {
		val := o.RoleName()
		m.RoleName = omit.From(val)
	}
	if o.Expiration != nil {
		val := o.Expiration()
		m.Expiration = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.InvitedUserSetter
// this does nothing with the relationship templates
func (o InvitedUserTemplate) BuildManySetter(number int) []*models.InvitedUserSetter {
	m := make([]*models.InvitedUserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.InvitedUser
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InvitedUserTemplate.Create
func (o InvitedUserTemplate) Build() *models.InvitedUser {
	m := &models.InvitedUser{}

	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.RoleName != nil {
		m.RoleName = o.RoleName()
	}
	if o.Expiration != nil {
		m.Expiration = o.Expiration()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.InvitedUserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use InvitedUserTemplate.CreateMany
func (o InvitedUserTemplate) BuildMany(number int) models.InvitedUserSlice {
	m := make(models.InvitedUserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableInvitedUser(m *models.InvitedUserSetter) {
	if !(m.Email.IsValue()) {
		val := random_string(nil)
		m.Email = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.RoleName.IsValue()) {
		val := random_string(nil)
		m.RoleName = omit.From(val)
	}
	if !(m.Expiration.IsValue()) {
		val := random_time_Time(nil)
		m.Expiration = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.InvitedUser
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *InvitedUserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.InvitedUser) error {
	var err error

	return err
}

// Create builds a invitedUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *InvitedUserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.InvitedUser, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableInvitedUser(opt)

	if o.r.Organization == nil {
		InvitedUserMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel0 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel0 = o.r.Organization.o.Build()
	} else {
		rel0, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel0.ID)

	m, err := models.InvitedUsers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Organization = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a invitedUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *InvitedUserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.InvitedUser {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a invitedUser and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *InvitedUserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.InvitedUser {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple invitedUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o InvitedUserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.InvitedUserSlice, error) {
	var err error
	m := make(models.InvitedUserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple invitedUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o InvitedUserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.InvitedUserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple invitedUsers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o InvitedUserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.InvitedUserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// InvitedUser has methods that act as mods for the InvitedUserTemplate
var InvitedUserMods invitedUserMods

type invitedUserMods struct{}

func (m invitedUserMods) RandomizeAllColumns(f *faker.Faker) InvitedUserMod {
	return InvitedUserModSlice{
		InvitedUserMods.RandomEmail(f),
		InvitedUserMods.RandomOrganizationID(f),
		InvitedUserMods.RandomRoleName(f),
		InvitedUserMods.RandomExpiration(f),
		InvitedUserMods.RandomCreatedAt(f),
		InvitedUserMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m invitedUserMods) Email(val string) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) EmailFunc(f func() string) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetEmail() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomEmail(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Email = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m invitedUserMods) OrganizationID(val uuid.UUID) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) OrganizationIDFunc(f func() uuid.UUID) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetOrganizationID() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomOrganizationID(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m invitedUserMods) RoleName(val string) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.RoleName = func() string { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) RoleNameFunc(f func() string) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.RoleName = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetRoleName() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.RoleName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomRoleName(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.RoleName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m invitedUserMods) Expiration(val time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Expiration = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) ExpirationFunc(f func() time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Expiration = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetExpiration() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Expiration = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomExpiration(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.Expiration = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m invitedUserMods) CreatedAt(val time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) CreatedAtFunc(f func() time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetCreatedAt() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomCreatedAt(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m invitedUserMods) UpdatedAt(val time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m invitedUserMods) UpdatedAtFunc(f func() time.Time) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m invitedUserMods) UnsetUpdatedAt() InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m invitedUserMods) RandomUpdatedAt(f *faker.Faker) InvitedUserMod {
	return InvitedUserModFunc(func(_ context.Context, o *InvitedUserTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m invitedUserMods) WithParentsCascading() InvitedUserMod {
	return InvitedUserModFunc(func(ctx context.Context, o *InvitedUserTemplate) {
		if isDone, _ := invitedUserWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = invitedUserWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m invitedUserMods) WithOrganization(rel *OrganizationTemplate) InvitedUserMod {
	return InvitedUserModFunc(func(ctx context.Context, o *InvitedUserTemplate) {
		o.r.Organization = &invitedUserROrganizationR{
			o: rel,
		}
	})
}

func (m invitedUserMods) WithNewOrganization(mods ...OrganizationMod) InvitedUserMod {
	return InvitedUserModFunc(func(ctx context.Context, o *InvitedUserTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m invitedUserMods) WithExistingOrganization(em *models.Organization) InvitedUserMod {
	return InvitedUserModFunc(func(ctx context.Context, o *InvitedUserTemplate) {
		o.r.Organization = &invitedUserROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m invitedUserMods) WithoutOrganization() InvitedUserMod {
	return InvitedUserModFunc(func(ctx context.Context, o *InvitedUserTemplate) {
		o.r.Organization = nil
	})
}
