// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type OrganizationScheduleMod interface {
	Apply(context.Context, *OrganizationScheduleTemplate)
}

type OrganizationScheduleModFunc func(context.Context, *OrganizationScheduleTemplate)

func (f OrganizationScheduleModFunc) Apply(ctx context.Context, n *OrganizationScheduleTemplate) {
	f(ctx, n)
}

type OrganizationScheduleModSlice []OrganizationScheduleMod

func (mods OrganizationScheduleModSlice) Apply(ctx context.Context, n *OrganizationScheduleTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrganizationScheduleTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrganizationScheduleTemplate struct {
	ID             func() uuid.UUID
	OrganizationID func() uuid.UUID
	Name           func() string
	Payload        func() null.Val[types.JSON[json.RawMessage]]
	ScheduledFor   func() time.Time
	CreatedAt      func() time.Time
	Processing     func() bool

	r organizationScheduleR
	f *Factory

	alreadyPersisted bool
}

type organizationScheduleR struct {
	Organization *organizationScheduleROrganizationR
}

type organizationScheduleROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the OrganizationScheduleTemplate
func (o *OrganizationScheduleTemplate) Apply(ctx context.Context, mods ...OrganizationScheduleMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.OrganizationSchedule
// according to the relationships in the template. Nothing is inserted into the db
func (t OrganizationScheduleTemplate) setModelRels(o *models.OrganizationSchedule) {
	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.OrganizationSchedules = append(rel.R.OrganizationSchedules, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.OrganizationScheduleSetter
// this does nothing with the relationship templates
func (o OrganizationScheduleTemplate) BuildSetter() *models.OrganizationScheduleSetter {
	m := &models.OrganizationScheduleSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Payload != nil {
		val := o.Payload()
		m.Payload = omitnull.FromNull(val)
	}
	if o.ScheduledFor != nil {
		val := o.ScheduledFor()
		m.ScheduledFor = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.Processing != nil {
		val := o.Processing()
		m.Processing = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrganizationScheduleSetter
// this does nothing with the relationship templates
func (o OrganizationScheduleTemplate) BuildManySetter(number int) []*models.OrganizationScheduleSetter {
	m := make([]*models.OrganizationScheduleSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.OrganizationSchedule
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationScheduleTemplate.Create
func (o OrganizationScheduleTemplate) Build() *models.OrganizationSchedule {
	m := &models.OrganizationSchedule{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Payload != nil {
		m.Payload = o.Payload()
	}
	if o.ScheduledFor != nil {
		m.ScheduledFor = o.ScheduledFor()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.Processing != nil {
		m.Processing = o.Processing()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrganizationScheduleSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrganizationScheduleTemplate.CreateMany
func (o OrganizationScheduleTemplate) BuildMany(number int) models.OrganizationScheduleSlice {
	m := make(models.OrganizationScheduleSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrganizationSchedule(m *models.OrganizationScheduleSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.ScheduledFor.IsValue()) {
		val := random_time_Time(nil)
		m.ScheduledFor = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.OrganizationSchedule
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrganizationScheduleTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.OrganizationSchedule) error {
	var err error

	return err
}

// Create builds a organizationSchedule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrganizationScheduleTemplate) Create(ctx context.Context, exec bob.Executor) (*models.OrganizationSchedule, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrganizationSchedule(opt)

	if o.r.Organization == nil {
		OrganizationScheduleMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel0 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel0 = o.r.Organization.o.Build()
	} else {
		rel0, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel0.ID)

	m, err := models.OrganizationSchedules.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Organization = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a organizationSchedule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrganizationScheduleTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.OrganizationSchedule {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a organizationSchedule and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrganizationScheduleTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.OrganizationSchedule {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple organizationSchedules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrganizationScheduleTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrganizationScheduleSlice, error) {
	var err error
	m := make(models.OrganizationScheduleSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple organizationSchedules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrganizationScheduleTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrganizationScheduleSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple organizationSchedules and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrganizationScheduleTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrganizationScheduleSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// OrganizationSchedule has methods that act as mods for the OrganizationScheduleTemplate
var OrganizationScheduleMods organizationScheduleMods

type organizationScheduleMods struct{}

func (m organizationScheduleMods) RandomizeAllColumns(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModSlice{
		OrganizationScheduleMods.RandomID(f),
		OrganizationScheduleMods.RandomOrganizationID(f),
		OrganizationScheduleMods.RandomName(f),
		OrganizationScheduleMods.RandomPayload(f),
		OrganizationScheduleMods.RandomScheduledFor(f),
		OrganizationScheduleMods.RandomCreatedAt(f),
		OrganizationScheduleMods.RandomProcessing(f),
	}
}

// Set the model columns to this value
func (m organizationScheduleMods) ID(val uuid.UUID) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) IDFunc(f func() uuid.UUID) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetID() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomID(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) OrganizationID(val uuid.UUID) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) OrganizationIDFunc(f func() uuid.UUID) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetOrganizationID() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomOrganizationID(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) Name(val string) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) NameFunc(f func() string) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetName() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomName(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) Payload(val null.Val[types.JSON[json.RawMessage]]) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Payload = func() null.Val[types.JSON[json.RawMessage]] { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) PayloadFunc(f func() null.Val[types.JSON[json.RawMessage]]) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Payload = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetPayload() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Payload = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m organizationScheduleMods) RandomPayload(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Payload = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m organizationScheduleMods) RandomPayloadNotNull(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Payload = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) ScheduledFor(val time.Time) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ScheduledFor = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) ScheduledForFunc(f func() time.Time) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ScheduledFor = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetScheduledFor() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ScheduledFor = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomScheduledFor(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.ScheduledFor = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) CreatedAt(val time.Time) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) CreatedAtFunc(f func() time.Time) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetCreatedAt() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomCreatedAt(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m organizationScheduleMods) Processing(val bool) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Processing = func() bool { return val }
	})
}

// Set the Column from the function
func (m organizationScheduleMods) ProcessingFunc(f func() bool) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Processing = f
	})
}

// Clear any values for the column
func (m organizationScheduleMods) UnsetProcessing() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Processing = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m organizationScheduleMods) RandomProcessing(f *faker.Faker) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(_ context.Context, o *OrganizationScheduleTemplate) {
		o.Processing = func() bool {
			return random_bool(f)
		}
	})
}

func (m organizationScheduleMods) WithParentsCascading() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(ctx context.Context, o *OrganizationScheduleTemplate) {
		if isDone, _ := organizationScheduleWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = organizationScheduleWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m organizationScheduleMods) WithOrganization(rel *OrganizationTemplate) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(ctx context.Context, o *OrganizationScheduleTemplate) {
		o.r.Organization = &organizationScheduleROrganizationR{
			o: rel,
		}
	})
}

func (m organizationScheduleMods) WithNewOrganization(mods ...OrganizationMod) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(ctx context.Context, o *OrganizationScheduleTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m organizationScheduleMods) WithExistingOrganization(em *models.Organization) OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(ctx context.Context, o *OrganizationScheduleTemplate) {
		o.r.Organization = &organizationScheduleROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m organizationScheduleMods) WithoutOrganization() OrganizationScheduleMod {
	return OrganizationScheduleModFunc(func(ctx context.Context, o *OrganizationScheduleTemplate) {
		o.r.Organization = nil
	})
}
