// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type RepositoryPersonalAccessTokenMod interface {
	Apply(context.Context, *RepositoryPersonalAccessTokenTemplate)
}

type RepositoryPersonalAccessTokenModFunc func(context.Context, *RepositoryPersonalAccessTokenTemplate)

func (f RepositoryPersonalAccessTokenModFunc) Apply(ctx context.Context, n *RepositoryPersonalAccessTokenTemplate) {
	f(ctx, n)
}

type RepositoryPersonalAccessTokenModSlice []RepositoryPersonalAccessTokenMod

func (mods RepositoryPersonalAccessTokenModSlice) Apply(ctx context.Context, n *RepositoryPersonalAccessTokenTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// RepositoryPersonalAccessTokenTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RepositoryPersonalAccessTokenTemplate struct {
	RepositoryID          func() uuid.UUID
	PersonalAccessTokenID func() uuid.UUID
	CreatedAt             func() time.Time

	r repositoryPersonalAccessTokenR
	f *Factory

	alreadyPersisted bool
}

type repositoryPersonalAccessTokenR struct {
	PersonalAccessToken *repositoryPersonalAccessTokenRPersonalAccessTokenR
	Repository          *repositoryPersonalAccessTokenRRepositoryR
}

type repositoryPersonalAccessTokenRPersonalAccessTokenR struct {
	o *PersonalAccessTokenTemplate
}
type repositoryPersonalAccessTokenRRepositoryR struct {
	o *RepositoryTemplate
}

// Apply mods to the RepositoryPersonalAccessTokenTemplate
func (o *RepositoryPersonalAccessTokenTemplate) Apply(ctx context.Context, mods ...RepositoryPersonalAccessTokenMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.RepositoryPersonalAccessToken
// according to the relationships in the template. Nothing is inserted into the db
func (t RepositoryPersonalAccessTokenTemplate) setModelRels(o *models.RepositoryPersonalAccessToken) {
	if t.r.PersonalAccessToken != nil {
		rel := t.r.PersonalAccessToken.o.Build()
		rel.R.RepositoryPersonalAccessTokens = append(rel.R.RepositoryPersonalAccessTokens, o)
		o.PersonalAccessTokenID = rel.ID // h2
		o.R.PersonalAccessToken = rel
	}

	if t.r.Repository != nil {
		rel := t.r.Repository.o.Build()
		rel.R.RepositoryPersonalAccessTokens = append(rel.R.RepositoryPersonalAccessTokens, o)
		o.RepositoryID = rel.ID // h2
		o.R.Repository = rel
	}
}

// BuildSetter returns an *models.RepositoryPersonalAccessTokenSetter
// this does nothing with the relationship templates
func (o RepositoryPersonalAccessTokenTemplate) BuildSetter() *models.RepositoryPersonalAccessTokenSetter {
	m := &models.RepositoryPersonalAccessTokenSetter{}

	if o.RepositoryID != nil {
		val := o.RepositoryID()
		m.RepositoryID = omit.From(val)
	}
	if o.PersonalAccessTokenID != nil {
		val := o.PersonalAccessTokenID()
		m.PersonalAccessTokenID = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.RepositoryPersonalAccessTokenSetter
// this does nothing with the relationship templates
func (o RepositoryPersonalAccessTokenTemplate) BuildManySetter(number int) []*models.RepositoryPersonalAccessTokenSetter {
	m := make([]*models.RepositoryPersonalAccessTokenSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RepositoryPersonalAccessToken
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RepositoryPersonalAccessTokenTemplate.Create
func (o RepositoryPersonalAccessTokenTemplate) Build() *models.RepositoryPersonalAccessToken {
	m := &models.RepositoryPersonalAccessToken{}

	if o.RepositoryID != nil {
		m.RepositoryID = o.RepositoryID()
	}
	if o.PersonalAccessTokenID != nil {
		m.PersonalAccessTokenID = o.PersonalAccessTokenID()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RepositoryPersonalAccessTokenSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RepositoryPersonalAccessTokenTemplate.CreateMany
func (o RepositoryPersonalAccessTokenTemplate) BuildMany(number int) models.RepositoryPersonalAccessTokenSlice {
	m := make(models.RepositoryPersonalAccessTokenSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRepositoryPersonalAccessToken(m *models.RepositoryPersonalAccessTokenSetter) {
	if !(m.RepositoryID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.RepositoryID = omit.From(val)
	}
	if !(m.PersonalAccessTokenID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.PersonalAccessTokenID = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RepositoryPersonalAccessToken
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RepositoryPersonalAccessTokenTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RepositoryPersonalAccessToken) error {
	var err error

	return err
}

// Create builds a repositoryPersonalAccessToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RepositoryPersonalAccessTokenTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RepositoryPersonalAccessToken, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRepositoryPersonalAccessToken(opt)

	if o.r.PersonalAccessToken == nil {
		RepositoryPersonalAccessTokenMods.WithNewPersonalAccessToken().Apply(ctx, o)
	}

	var rel0 *models.PersonalAccessToken

	if o.r.PersonalAccessToken.o.alreadyPersisted {
		rel0 = o.r.PersonalAccessToken.o.Build()
	} else {
		rel0, err = o.r.PersonalAccessToken.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.PersonalAccessTokenID = omit.From(rel0.ID)

	if o.r.Repository == nil {
		RepositoryPersonalAccessTokenMods.WithNewRepository().Apply(ctx, o)
	}

	var rel1 *models.Repository

	if o.r.Repository.o.alreadyPersisted {
		rel1 = o.r.Repository.o.Build()
	} else {
		rel1, err = o.r.Repository.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.RepositoryID = omit.From(rel1.ID)

	m, err := models.RepositoryPersonalAccessTokens.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.PersonalAccessToken = rel0
	m.R.Repository = rel1

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a repositoryPersonalAccessToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RepositoryPersonalAccessTokenTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RepositoryPersonalAccessToken {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a repositoryPersonalAccessToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RepositoryPersonalAccessTokenTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RepositoryPersonalAccessToken {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple repositoryPersonalAccessTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RepositoryPersonalAccessTokenTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RepositoryPersonalAccessTokenSlice, error) {
	var err error
	m := make(models.RepositoryPersonalAccessTokenSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple repositoryPersonalAccessTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RepositoryPersonalAccessTokenTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RepositoryPersonalAccessTokenSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple repositoryPersonalAccessTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RepositoryPersonalAccessTokenTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RepositoryPersonalAccessTokenSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// RepositoryPersonalAccessToken has methods that act as mods for the RepositoryPersonalAccessTokenTemplate
var RepositoryPersonalAccessTokenMods repositoryPersonalAccessTokenMods

type repositoryPersonalAccessTokenMods struct{}

func (m repositoryPersonalAccessTokenMods) RandomizeAllColumns(f *faker.Faker) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModSlice{
		RepositoryPersonalAccessTokenMods.RandomRepositoryID(f),
		RepositoryPersonalAccessTokenMods.RandomPersonalAccessTokenID(f),
		RepositoryPersonalAccessTokenMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m repositoryPersonalAccessTokenMods) RepositoryID(val uuid.UUID) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.RepositoryID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m repositoryPersonalAccessTokenMods) RepositoryIDFunc(f func() uuid.UUID) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.RepositoryID = f
	})
}

// Clear any values for the column
func (m repositoryPersonalAccessTokenMods) UnsetRepositoryID() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.RepositoryID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m repositoryPersonalAccessTokenMods) RandomRepositoryID(f *faker.Faker) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.RepositoryID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m repositoryPersonalAccessTokenMods) PersonalAccessTokenID(val uuid.UUID) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.PersonalAccessTokenID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m repositoryPersonalAccessTokenMods) PersonalAccessTokenIDFunc(f func() uuid.UUID) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.PersonalAccessTokenID = f
	})
}

// Clear any values for the column
func (m repositoryPersonalAccessTokenMods) UnsetPersonalAccessTokenID() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.PersonalAccessTokenID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m repositoryPersonalAccessTokenMods) RandomPersonalAccessTokenID(f *faker.Faker) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.PersonalAccessTokenID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m repositoryPersonalAccessTokenMods) CreatedAt(val time.Time) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m repositoryPersonalAccessTokenMods) CreatedAtFunc(f func() time.Time) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m repositoryPersonalAccessTokenMods) UnsetCreatedAt() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m repositoryPersonalAccessTokenMods) RandomCreatedAt(f *faker.Faker) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(_ context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithParentsCascading() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		if isDone, _ := repositoryPersonalAccessTokenWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = repositoryPersonalAccessTokenWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewPersonalAccessTokenWithContext(ctx, PersonalAccessTokenMods.WithParentsCascading())
			m.WithPersonalAccessToken(related).Apply(ctx, o)
		}
		{

			related := o.f.NewRepositoryWithContext(ctx, RepositoryMods.WithParentsCascading())
			m.WithRepository(related).Apply(ctx, o)
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithPersonalAccessToken(rel *PersonalAccessTokenTemplate) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.PersonalAccessToken = &repositoryPersonalAccessTokenRPersonalAccessTokenR{
			o: rel,
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithNewPersonalAccessToken(mods ...PersonalAccessTokenMod) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		related := o.f.NewPersonalAccessTokenWithContext(ctx, mods...)

		m.WithPersonalAccessToken(related).Apply(ctx, o)
	})
}

func (m repositoryPersonalAccessTokenMods) WithExistingPersonalAccessToken(em *models.PersonalAccessToken) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.PersonalAccessToken = &repositoryPersonalAccessTokenRPersonalAccessTokenR{
			o: o.f.FromExistingPersonalAccessToken(em),
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithoutPersonalAccessToken() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.PersonalAccessToken = nil
	})
}

func (m repositoryPersonalAccessTokenMods) WithRepository(rel *RepositoryTemplate) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.Repository = &repositoryPersonalAccessTokenRRepositoryR{
			o: rel,
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithNewRepository(mods ...RepositoryMod) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		related := o.f.NewRepositoryWithContext(ctx, mods...)

		m.WithRepository(related).Apply(ctx, o)
	})
}

func (m repositoryPersonalAccessTokenMods) WithExistingRepository(em *models.Repository) RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.Repository = &repositoryPersonalAccessTokenRRepositoryR{
			o: o.f.FromExistingRepository(em),
		}
	})
}

func (m repositoryPersonalAccessTokenMods) WithoutRepository() RepositoryPersonalAccessTokenMod {
	return RepositoryPersonalAccessTokenModFunc(func(ctx context.Context, o *RepositoryPersonalAccessTokenTemplate) {
		o.r.Repository = nil
	})
}
