// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

type SandboxObjectMod interface {
	Apply(context.Context, *SandboxObjectTemplate)
}

type SandboxObjectModFunc func(context.Context, *SandboxObjectTemplate)

func (f SandboxObjectModFunc) Apply(ctx context.Context, n *SandboxObjectTemplate) {
	f(ctx, n)
}

type SandboxObjectModSlice []SandboxObjectMod

func (mods SandboxObjectModSlice) Apply(ctx context.Context, n *SandboxObjectTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SandboxObjectTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SandboxObjectTemplate struct {
	SandboxID       func() uuid.UUID
	ID              func() uuid.UUID
	Namespace       func() string
	Name            func() string
	ResourceVersion func() string
	Kind            func() string
	Raw             func() null.Val[types.JSON[json.RawMessage]]
	CreatedAt       func() time.Time

	r sandboxObjectR
	f *Factory

	alreadyPersisted bool
}

type sandboxObjectR struct {
	Sandbox *sandboxObjectRSandboxR
}

type sandboxObjectRSandboxR struct {
	o *SandboxTemplate
}

// Apply mods to the SandboxObjectTemplate
func (o *SandboxObjectTemplate) Apply(ctx context.Context, mods ...SandboxObjectMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.SandboxObject
// according to the relationships in the template. Nothing is inserted into the db
func (t SandboxObjectTemplate) setModelRels(o *models.SandboxObject) {
	if t.r.Sandbox != nil {
		rel := t.r.Sandbox.o.Build()
		rel.R.SandboxObjects = append(rel.R.SandboxObjects, o)
		o.SandboxID = rel.ID // h2
		o.R.Sandbox = rel
	}
}

// BuildSetter returns an *models.SandboxObjectSetter
// this does nothing with the relationship templates
func (o SandboxObjectTemplate) BuildSetter() *models.SandboxObjectSetter {
	m := &models.SandboxObjectSetter{}

	if o.SandboxID != nil {
		val := o.SandboxID()
		m.SandboxID = omit.From(val)
	}
	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Namespace != nil {
		val := o.Namespace()
		m.Namespace = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.ResourceVersion != nil {
		val := o.ResourceVersion()
		m.ResourceVersion = omit.From(val)
	}
	if o.Kind != nil {
		val := o.Kind()
		m.Kind = omit.From(val)
	}
	if o.Raw != nil {
		val := o.Raw()
		m.Raw = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SandboxObjectSetter
// this does nothing with the relationship templates
func (o SandboxObjectTemplate) BuildManySetter(number int) []*models.SandboxObjectSetter {
	m := make([]*models.SandboxObjectSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.SandboxObject
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SandboxObjectTemplate.Create
func (o SandboxObjectTemplate) Build() *models.SandboxObject {
	m := &models.SandboxObject{}

	if o.SandboxID != nil {
		m.SandboxID = o.SandboxID()
	}
	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Namespace != nil {
		m.Namespace = o.Namespace()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.ResourceVersion != nil {
		m.ResourceVersion = o.ResourceVersion()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.Raw != nil {
		m.Raw = o.Raw()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SandboxObjectSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SandboxObjectTemplate.CreateMany
func (o SandboxObjectTemplate) BuildMany(number int) models.SandboxObjectSlice {
	m := make(models.SandboxObjectSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSandboxObject(m *models.SandboxObjectSetter) {
	if !(m.SandboxID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.SandboxID = omit.From(val)
	}
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.ResourceVersion.IsValue()) {
		val := random_string(nil)
		m.ResourceVersion = omit.From(val)
	}
	if !(m.Kind.IsValue()) {
		val := random_string(nil)
		m.Kind = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.SandboxObject
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SandboxObjectTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.SandboxObject) error {
	var err error

	return err
}

// Create builds a sandboxObject and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SandboxObjectTemplate) Create(ctx context.Context, exec bob.Executor) (*models.SandboxObject, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSandboxObject(opt)

	if o.r.Sandbox == nil {
		SandboxObjectMods.WithNewSandbox().Apply(ctx, o)
	}

	var rel0 *models.Sandbox

	if o.r.Sandbox.o.alreadyPersisted {
		rel0 = o.r.Sandbox.o.Build()
	} else {
		rel0, err = o.r.Sandbox.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.SandboxID = omit.From(rel0.ID)

	m, err := models.SandboxObjects.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Sandbox = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a sandboxObject and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SandboxObjectTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.SandboxObject {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a sandboxObject and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SandboxObjectTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.SandboxObject {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple sandboxObjects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SandboxObjectTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SandboxObjectSlice, error) {
	var err error
	m := make(models.SandboxObjectSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple sandboxObjects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SandboxObjectTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SandboxObjectSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple sandboxObjects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SandboxObjectTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SandboxObjectSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// SandboxObject has methods that act as mods for the SandboxObjectTemplate
var SandboxObjectMods sandboxObjectMods

type sandboxObjectMods struct{}

func (m sandboxObjectMods) RandomizeAllColumns(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModSlice{
		SandboxObjectMods.RandomSandboxID(f),
		SandboxObjectMods.RandomID(f),
		SandboxObjectMods.RandomNamespace(f),
		SandboxObjectMods.RandomName(f),
		SandboxObjectMods.RandomResourceVersion(f),
		SandboxObjectMods.RandomKind(f),
		SandboxObjectMods.RandomRaw(f),
		SandboxObjectMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m sandboxObjectMods) SandboxID(val uuid.UUID) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.SandboxID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) SandboxIDFunc(f func() uuid.UUID) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.SandboxID = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetSandboxID() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.SandboxID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomSandboxID(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.SandboxID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) ID(val uuid.UUID) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) IDFunc(f func() uuid.UUID) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetID() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomID(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) Namespace(val string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Namespace = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) NamespaceFunc(f func() string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Namespace = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetNamespace() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Namespace = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomNamespace(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Namespace = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) Name(val string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) NameFunc(f func() string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetName() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomName(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) ResourceVersion(val string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ResourceVersion = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) ResourceVersionFunc(f func() string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ResourceVersion = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetResourceVersion() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ResourceVersion = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomResourceVersion(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.ResourceVersion = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) Kind(val string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) KindFunc(f func() string) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetKind() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomKind(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) Raw(val null.Val[types.JSON[json.RawMessage]]) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Raw = func() null.Val[types.JSON[json.RawMessage]] { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) RawFunc(f func() null.Val[types.JSON[json.RawMessage]]) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Raw = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetRaw() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Raw = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m sandboxObjectMods) RandomRaw(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Raw = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m sandboxObjectMods) RandomRawNotNull(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.Raw = func() null.Val[types.JSON[json.RawMessage]] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_types_JSON_json_RawMessage_(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m sandboxObjectMods) CreatedAt(val time.Time) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m sandboxObjectMods) CreatedAtFunc(f func() time.Time) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m sandboxObjectMods) UnsetCreatedAt() SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxObjectMods) RandomCreatedAt(f *faker.Faker) SandboxObjectMod {
	return SandboxObjectModFunc(func(_ context.Context, o *SandboxObjectTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m sandboxObjectMods) WithParentsCascading() SandboxObjectMod {
	return SandboxObjectModFunc(func(ctx context.Context, o *SandboxObjectTemplate) {
		if isDone, _ := sandboxObjectWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = sandboxObjectWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewSandboxWithContext(ctx, SandboxMods.WithParentsCascading())
			m.WithSandbox(related).Apply(ctx, o)
		}
	})
}

func (m sandboxObjectMods) WithSandbox(rel *SandboxTemplate) SandboxObjectMod {
	return SandboxObjectModFunc(func(ctx context.Context, o *SandboxObjectTemplate) {
		o.r.Sandbox = &sandboxObjectRSandboxR{
			o: rel,
		}
	})
}

func (m sandboxObjectMods) WithNewSandbox(mods ...SandboxMod) SandboxObjectMod {
	return SandboxObjectModFunc(func(ctx context.Context, o *SandboxObjectTemplate) {
		related := o.f.NewSandboxWithContext(ctx, mods...)

		m.WithSandbox(related).Apply(ctx, o)
	})
}

func (m sandboxObjectMods) WithExistingSandbox(em *models.Sandbox) SandboxObjectMod {
	return SandboxObjectModFunc(func(ctx context.Context, o *SandboxObjectTemplate) {
		o.r.Sandbox = &sandboxObjectRSandboxR{
			o: o.f.FromExistingSandbox(em),
		}
	})
}

func (m sandboxObjectMods) WithoutSandbox() SandboxObjectMod {
	return SandboxObjectModFunc(func(ctx context.Context, o *SandboxObjectTemplate) {
		o.r.Sandbox = nil
	})
}
