// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type SandboxClusterInfoMod interface {
	Apply(context.Context, *SandboxClusterInfoTemplate)
}

type SandboxClusterInfoModFunc func(context.Context, *SandboxClusterInfoTemplate)

func (f SandboxClusterInfoModFunc) Apply(ctx context.Context, n *SandboxClusterInfoTemplate) {
	f(ctx, n)
}

type SandboxClusterInfoModSlice []SandboxClusterInfoMod

func (mods SandboxClusterInfoModSlice) Apply(ctx context.Context, n *SandboxClusterInfoTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// SandboxClusterInfoTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type SandboxClusterInfoTemplate struct {
	SandboxID func() uuid.UUID
	Name      func() string
	Version   func() string
	Platform  func() string

	r sandboxClusterInfoR
	f *Factory

	alreadyPersisted bool
}

type sandboxClusterInfoR struct {
	Sandbox *sandboxClusterInfoRSandboxR
}

type sandboxClusterInfoRSandboxR struct {
	o *SandboxTemplate
}

// Apply mods to the SandboxClusterInfoTemplate
func (o *SandboxClusterInfoTemplate) Apply(ctx context.Context, mods ...SandboxClusterInfoMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.SandboxClusterInfo
// according to the relationships in the template. Nothing is inserted into the db
func (t SandboxClusterInfoTemplate) setModelRels(o *models.SandboxClusterInfo) {
	if t.r.Sandbox != nil {
		rel := t.r.Sandbox.o.Build()
		rel.R.SandboxClusterInfo = o
		o.SandboxID = rel.ID // h2
		o.R.Sandbox = rel
	}
}

// BuildSetter returns an *models.SandboxClusterInfoSetter
// this does nothing with the relationship templates
func (o SandboxClusterInfoTemplate) BuildSetter() *models.SandboxClusterInfoSetter {
	m := &models.SandboxClusterInfoSetter{}

	if o.SandboxID != nil {
		val := o.SandboxID()
		m.SandboxID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Version != nil {
		val := o.Version()
		m.Version = omit.From(val)
	}
	if o.Platform != nil {
		val := o.Platform()
		m.Platform = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.SandboxClusterInfoSetter
// this does nothing with the relationship templates
func (o SandboxClusterInfoTemplate) BuildManySetter(number int) []*models.SandboxClusterInfoSetter {
	m := make([]*models.SandboxClusterInfoSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.SandboxClusterInfo
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SandboxClusterInfoTemplate.Create
func (o SandboxClusterInfoTemplate) Build() *models.SandboxClusterInfo {
	m := &models.SandboxClusterInfo{}

	if o.SandboxID != nil {
		m.SandboxID = o.SandboxID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Version != nil {
		m.Version = o.Version()
	}
	if o.Platform != nil {
		m.Platform = o.Platform()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.SandboxClusterInfoSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use SandboxClusterInfoTemplate.CreateMany
func (o SandboxClusterInfoTemplate) BuildMany(number int) models.SandboxClusterInfoSlice {
	m := make(models.SandboxClusterInfoSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableSandboxClusterInfo(m *models.SandboxClusterInfoSetter) {
	if !(m.SandboxID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.SandboxID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
	if !(m.Version.IsValue()) {
		val := random_string(nil)
		m.Version = omit.From(val)
	}
	if !(m.Platform.IsValue()) {
		val := random_string(nil)
		m.Platform = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.SandboxClusterInfo
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *SandboxClusterInfoTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.SandboxClusterInfo) error {
	var err error

	return err
}

// Create builds a sandboxClusterInfo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *SandboxClusterInfoTemplate) Create(ctx context.Context, exec bob.Executor) (*models.SandboxClusterInfo, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableSandboxClusterInfo(opt)

	if o.r.Sandbox == nil {
		SandboxClusterInfoMods.WithNewSandbox().Apply(ctx, o)
	}

	var rel0 *models.Sandbox

	if o.r.Sandbox.o.alreadyPersisted {
		rel0 = o.r.Sandbox.o.Build()
	} else {
		rel0, err = o.r.Sandbox.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.SandboxID = omit.From(rel0.ID)

	m, err := models.SandboxClusterInfos.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Sandbox = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a sandboxClusterInfo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *SandboxClusterInfoTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.SandboxClusterInfo {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a sandboxClusterInfo and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *SandboxClusterInfoTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.SandboxClusterInfo {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple sandboxClusterInfos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o SandboxClusterInfoTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.SandboxClusterInfoSlice, error) {
	var err error
	m := make(models.SandboxClusterInfoSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple sandboxClusterInfos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o SandboxClusterInfoTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.SandboxClusterInfoSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple sandboxClusterInfos and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o SandboxClusterInfoTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.SandboxClusterInfoSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// SandboxClusterInfo has methods that act as mods for the SandboxClusterInfoTemplate
var SandboxClusterInfoMods sandboxClusterInfoMods

type sandboxClusterInfoMods struct{}

func (m sandboxClusterInfoMods) RandomizeAllColumns(f *faker.Faker) SandboxClusterInfoMod {
	return SandboxClusterInfoModSlice{
		SandboxClusterInfoMods.RandomSandboxID(f),
		SandboxClusterInfoMods.RandomName(f),
		SandboxClusterInfoMods.RandomVersion(f),
		SandboxClusterInfoMods.RandomPlatform(f),
	}
}

// Set the model columns to this value
func (m sandboxClusterInfoMods) SandboxID(val uuid.UUID) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.SandboxID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m sandboxClusterInfoMods) SandboxIDFunc(f func() uuid.UUID) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.SandboxID = f
	})
}

// Clear any values for the column
func (m sandboxClusterInfoMods) UnsetSandboxID() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.SandboxID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxClusterInfoMods) RandomSandboxID(f *faker.Faker) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.SandboxID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxClusterInfoMods) Name(val string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxClusterInfoMods) NameFunc(f func() string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m sandboxClusterInfoMods) UnsetName() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxClusterInfoMods) RandomName(f *faker.Faker) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxClusterInfoMods) Version(val string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Version = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxClusterInfoMods) VersionFunc(f func() string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Version = f
	})
}

// Clear any values for the column
func (m sandboxClusterInfoMods) UnsetVersion() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Version = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxClusterInfoMods) RandomVersion(f *faker.Faker) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Version = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m sandboxClusterInfoMods) Platform(val string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Platform = func() string { return val }
	})
}

// Set the Column from the function
func (m sandboxClusterInfoMods) PlatformFunc(f func() string) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Platform = f
	})
}

// Clear any values for the column
func (m sandboxClusterInfoMods) UnsetPlatform() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Platform = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m sandboxClusterInfoMods) RandomPlatform(f *faker.Faker) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(_ context.Context, o *SandboxClusterInfoTemplate) {
		o.Platform = func() string {
			return random_string(f)
		}
	})
}

func (m sandboxClusterInfoMods) WithParentsCascading() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(ctx context.Context, o *SandboxClusterInfoTemplate) {
		if isDone, _ := sandboxClusterInfoWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = sandboxClusterInfoWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewSandboxWithContext(ctx, SandboxMods.WithParentsCascading())
			m.WithSandbox(related).Apply(ctx, o)
		}
	})
}

func (m sandboxClusterInfoMods) WithSandbox(rel *SandboxTemplate) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(ctx context.Context, o *SandboxClusterInfoTemplate) {
		o.r.Sandbox = &sandboxClusterInfoRSandboxR{
			o: rel,
		}
	})
}

func (m sandboxClusterInfoMods) WithNewSandbox(mods ...SandboxMod) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(ctx context.Context, o *SandboxClusterInfoTemplate) {
		related := o.f.NewSandboxWithContext(ctx, mods...)

		m.WithSandbox(related).Apply(ctx, o)
	})
}

func (m sandboxClusterInfoMods) WithExistingSandbox(em *models.Sandbox) SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(ctx context.Context, o *SandboxClusterInfoTemplate) {
		o.r.Sandbox = &sandboxClusterInfoRSandboxR{
			o: o.f.FromExistingSandbox(em),
		}
	})
}

func (m sandboxClusterInfoMods) WithoutSandbox() SandboxClusterInfoMod {
	return SandboxClusterInfoModFunc(func(ctx context.Context, o *SandboxClusterInfoTemplate) {
		o.r.Sandbox = nil
	})
}
