// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/jaswdr/faker/v2"
	models "github.com/kubegrade/matrix/postgres/bobmodel"
	"github.com/stephenafamo/bob"
)

type UserAccountMod interface {
	Apply(context.Context, *UserAccountTemplate)
}

type UserAccountModFunc func(context.Context, *UserAccountTemplate)

func (f UserAccountModFunc) Apply(ctx context.Context, n *UserAccountTemplate) {
	f(ctx, n)
}

type UserAccountModSlice []UserAccountMod

func (mods UserAccountModSlice) Apply(ctx context.Context, n *UserAccountTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserAccountTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserAccountTemplate struct {
	ID             func() uuid.UUID
	OrganizationID func() uuid.UUID
	RoleName       func() string
	Email          func() string
	Verified       func() bool
	FirstName      func() string
	LastName       func() string
	CreatedAt      func() time.Time
	UpdatedAt      func() time.Time

	r userAccountR
	f *Factory

	alreadyPersisted bool
}

type userAccountR struct {
	UserForgotPasswordToken       *userAccountRUserForgotPasswordTokenR
	CreatedByPersonalAccessTokens []*userAccountRCreatedByPersonalAccessTokensR
	UpdatedByPersonalAccessTokens []*userAccountRUpdatedByPersonalAccessTokensR
	CreatedByRepositories         []*userAccountRCreatedByRepositoriesR
	UpdatedByRepositories         []*userAccountRUpdatedByRepositoriesR
	Organization                  *userAccountROrganizationR
}

type userAccountRUserForgotPasswordTokenR struct {
	o *ForgotPasswordTokenTemplate
}
type userAccountRCreatedByPersonalAccessTokensR struct {
	number int
	o      *PersonalAccessTokenTemplate
}
type userAccountRUpdatedByPersonalAccessTokensR struct {
	number int
	o      *PersonalAccessTokenTemplate
}
type userAccountRCreatedByRepositoriesR struct {
	number int
	o      *RepositoryTemplate
}
type userAccountRUpdatedByRepositoriesR struct {
	number int
	o      *RepositoryTemplate
}
type userAccountROrganizationR struct {
	o *OrganizationTemplate
}

// Apply mods to the UserAccountTemplate
func (o *UserAccountTemplate) Apply(ctx context.Context, mods ...UserAccountMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.UserAccount
// according to the relationships in the template. Nothing is inserted into the db
func (t UserAccountTemplate) setModelRels(o *models.UserAccount) {
	if t.r.UserForgotPasswordToken != nil {
		rel := t.r.UserForgotPasswordToken.o.Build()
		rel.R.UserUserAccount = o
		rel.UserID = o.ID // h2
		o.R.UserForgotPasswordToken = rel
	}

	if t.r.CreatedByPersonalAccessTokens != nil {
		rel := models.PersonalAccessTokenSlice{}
		for _, r := range t.r.CreatedByPersonalAccessTokens {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedBy = null.From(o.ID) // h2
				rel.R.CreatedByUserAccount = o
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByPersonalAccessTokens = rel
	}

	if t.r.UpdatedByPersonalAccessTokens != nil {
		rel := models.PersonalAccessTokenSlice{}
		for _, r := range t.r.UpdatedByPersonalAccessTokens {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedBy = null.From(o.ID) // h2
				rel.R.UpdatedByUserAccount = o
			}
			rel = append(rel, related...)
		}
		o.R.UpdatedByPersonalAccessTokens = rel
	}

	if t.r.CreatedByRepositories != nil {
		rel := models.RepositorySlice{}
		for _, r := range t.r.CreatedByRepositories {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedBy = null.From(o.ID) // h2
				rel.R.CreatedByUserAccount = o
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByRepositories = rel
	}

	if t.r.UpdatedByRepositories != nil {
		rel := models.RepositorySlice{}
		for _, r := range t.r.UpdatedByRepositories {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UpdatedBy = null.From(o.ID) // h2
				rel.R.UpdatedByUserAccount = o
			}
			rel = append(rel, related...)
		}
		o.R.UpdatedByRepositories = rel
	}

	if t.r.Organization != nil {
		rel := t.r.Organization.o.Build()
		rel.R.UserAccounts = append(rel.R.UserAccounts, o)
		o.OrganizationID = rel.ID // h2
		o.R.Organization = rel
	}
}

// BuildSetter returns an *models.UserAccountSetter
// this does nothing with the relationship templates
func (o UserAccountTemplate) BuildSetter() *models.UserAccountSetter {
	m := &models.UserAccountSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrganizationID != nil {
		val := o.OrganizationID()
		m.OrganizationID = omit.From(val)
	}
	if o.RoleName != nil {
		val := o.RoleName()
		m.RoleName = omit.From(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omit.From(val)
	}
	if o.Verified != nil {
		val := o.Verified()
		m.Verified = omit.From(val)
	}
	if o.FirstName != nil {
		val := o.FirstName()
		m.FirstName = omit.From(val)
	}
	if o.LastName != nil {
		val := o.LastName()
		m.LastName = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omit.From(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.UserAccountSetter
// this does nothing with the relationship templates
func (o UserAccountTemplate) BuildManySetter(number int) []*models.UserAccountSetter {
	m := make([]*models.UserAccountSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.UserAccount
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserAccountTemplate.Create
func (o UserAccountTemplate) Build() *models.UserAccount {
	m := &models.UserAccount{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrganizationID != nil {
		m.OrganizationID = o.OrganizationID()
	}
	if o.RoleName != nil {
		m.RoleName = o.RoleName()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Verified != nil {
		m.Verified = o.Verified()
	}
	if o.FirstName != nil {
		m.FirstName = o.FirstName()
	}
	if o.LastName != nil {
		m.LastName = o.LastName()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserAccountSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserAccountTemplate.CreateMany
func (o UserAccountTemplate) BuildMany(number int) models.UserAccountSlice {
	m := make(models.UserAccountSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUserAccount(m *models.UserAccountSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.OrganizationID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.OrganizationID = omit.From(val)
	}
	if !(m.RoleName.IsValue()) {
		val := random_string(nil)
		m.RoleName = omit.From(val)
	}
	if !(m.Email.IsValue()) {
		val := random_string(nil)
		m.Email = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.UserAccount
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserAccountTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.UserAccount) error {
	var err error

	isUserForgotPasswordTokenDone, _ := userAccountRelUserForgotPasswordTokenCtx.Value(ctx)
	if !isUserForgotPasswordTokenDone && o.r.UserForgotPasswordToken != nil {
		ctx = userAccountRelUserForgotPasswordTokenCtx.WithValue(ctx, true)
		if o.r.UserForgotPasswordToken.o.alreadyPersisted {
			m.R.UserForgotPasswordToken = o.r.UserForgotPasswordToken.o.Build()
		} else {
			var rel0 *models.ForgotPasswordToken
			rel0, err = o.r.UserForgotPasswordToken.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachUserForgotPasswordToken(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	isCreatedByPersonalAccessTokensDone, _ := userAccountRelCreatedByPersonalAccessTokensCtx.Value(ctx)
	if !isCreatedByPersonalAccessTokensDone && o.r.CreatedByPersonalAccessTokens != nil {
		ctx = userAccountRelCreatedByPersonalAccessTokensCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByPersonalAccessTokens {
			if r.o.alreadyPersisted {
				m.R.CreatedByPersonalAccessTokens = append(m.R.CreatedByPersonalAccessTokens, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByPersonalAccessTokens(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpdatedByPersonalAccessTokensDone, _ := userAccountRelUpdatedByPersonalAccessTokensCtx.Value(ctx)
	if !isUpdatedByPersonalAccessTokensDone && o.r.UpdatedByPersonalAccessTokens != nil {
		ctx = userAccountRelUpdatedByPersonalAccessTokensCtx.WithValue(ctx, true)
		for _, r := range o.r.UpdatedByPersonalAccessTokens {
			if r.o.alreadyPersisted {
				m.R.UpdatedByPersonalAccessTokens = append(m.R.UpdatedByPersonalAccessTokens, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpdatedByPersonalAccessTokens(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCreatedByRepositoriesDone, _ := userAccountRelCreatedByRepositoriesCtx.Value(ctx)
	if !isCreatedByRepositoriesDone && o.r.CreatedByRepositories != nil {
		ctx = userAccountRelCreatedByRepositoriesCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByRepositories {
			if r.o.alreadyPersisted {
				m.R.CreatedByRepositories = append(m.R.CreatedByRepositories, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByRepositories(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isUpdatedByRepositoriesDone, _ := userAccountRelUpdatedByRepositoriesCtx.Value(ctx)
	if !isUpdatedByRepositoriesDone && o.r.UpdatedByRepositories != nil {
		ctx = userAccountRelUpdatedByRepositoriesCtx.WithValue(ctx, true)
		for _, r := range o.r.UpdatedByRepositories {
			if r.o.alreadyPersisted {
				m.R.UpdatedByRepositories = append(m.R.UpdatedByRepositories, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachUpdatedByRepositories(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a userAccount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserAccountTemplate) Create(ctx context.Context, exec bob.Executor) (*models.UserAccount, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUserAccount(opt)

	if o.r.Organization == nil {
		UserAccountMods.WithNewOrganization().Apply(ctx, o)
	}

	var rel5 *models.Organization

	if o.r.Organization.o.alreadyPersisted {
		rel5 = o.r.Organization.o.Build()
	} else {
		rel5, err = o.r.Organization.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.OrganizationID = omit.From(rel5.ID)

	m, err := models.UserAccounts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Organization = rel5

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a userAccount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserAccountTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.UserAccount {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a userAccount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserAccountTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.UserAccount {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple userAccounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserAccountTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserAccountSlice, error) {
	var err error
	m := make(models.UserAccountSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple userAccounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserAccountTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserAccountSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple userAccounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserAccountTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserAccountSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// UserAccount has methods that act as mods for the UserAccountTemplate
var UserAccountMods userAccountMods

type userAccountMods struct{}

func (m userAccountMods) RandomizeAllColumns(f *faker.Faker) UserAccountMod {
	return UserAccountModSlice{
		UserAccountMods.RandomID(f),
		UserAccountMods.RandomOrganizationID(f),
		UserAccountMods.RandomRoleName(f),
		UserAccountMods.RandomEmail(f),
		UserAccountMods.RandomVerified(f),
		UserAccountMods.RandomFirstName(f),
		UserAccountMods.RandomLastName(f),
		UserAccountMods.RandomCreatedAt(f),
		UserAccountMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m userAccountMods) ID(val uuid.UUID) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) IDFunc(f func() uuid.UUID) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetID() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomID(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) OrganizationID(val uuid.UUID) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.OrganizationID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) OrganizationIDFunc(f func() uuid.UUID) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.OrganizationID = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetOrganizationID() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.OrganizationID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomOrganizationID(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.OrganizationID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) RoleName(val string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.RoleName = func() string { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) RoleNameFunc(f func() string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.RoleName = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetRoleName() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.RoleName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomRoleName(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.RoleName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) Email(val string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) EmailFunc(f func() string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetEmail() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomEmail(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Email = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) Verified(val bool) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Verified = func() bool { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) VerifiedFunc(f func() bool) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Verified = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetVerified() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Verified = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomVerified(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.Verified = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) FirstName(val string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.FirstName = func() string { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) FirstNameFunc(f func() string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.FirstName = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetFirstName() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.FirstName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomFirstName(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.FirstName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) LastName(val string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.LastName = func() string { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) LastNameFunc(f func() string) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.LastName = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetLastName() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.LastName = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomLastName(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.LastName = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) CreatedAt(val time.Time) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) CreatedAtFunc(f func() time.Time) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetCreatedAt() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomCreatedAt(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userAccountMods) UpdatedAt(val time.Time) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userAccountMods) UpdatedAtFunc(f func() time.Time) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userAccountMods) UnsetUpdatedAt() UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userAccountMods) RandomUpdatedAt(f *faker.Faker) UserAccountMod {
	return UserAccountModFunc(func(_ context.Context, o *UserAccountTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m userAccountMods) WithParentsCascading() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		if isDone, _ := userAccountWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userAccountWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewForgotPasswordTokenWithContext(ctx, ForgotPasswordTokenMods.WithParentsCascading())
			m.WithUserForgotPasswordToken(related).Apply(ctx, o)
		}
		{

			related := o.f.NewOrganizationWithContext(ctx, OrganizationMods.WithParentsCascading())
			m.WithOrganization(related).Apply(ctx, o)
		}
	})
}

func (m userAccountMods) WithUserForgotPasswordToken(rel *ForgotPasswordTokenTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UserForgotPasswordToken = &userAccountRUserForgotPasswordTokenR{
			o: rel,
		}
	})
}

func (m userAccountMods) WithNewUserForgotPasswordToken(mods ...ForgotPasswordTokenMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewForgotPasswordTokenWithContext(ctx, mods...)

		m.WithUserForgotPasswordToken(related).Apply(ctx, o)
	})
}

func (m userAccountMods) WithExistingUserForgotPasswordToken(em *models.ForgotPasswordToken) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UserForgotPasswordToken = &userAccountRUserForgotPasswordTokenR{
			o: o.f.FromExistingForgotPasswordToken(em),
		}
	})
}

func (m userAccountMods) WithoutUserForgotPasswordToken() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UserForgotPasswordToken = nil
	})
}

func (m userAccountMods) WithOrganization(rel *OrganizationTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.Organization = &userAccountROrganizationR{
			o: rel,
		}
	})
}

func (m userAccountMods) WithNewOrganization(mods ...OrganizationMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewOrganizationWithContext(ctx, mods...)

		m.WithOrganization(related).Apply(ctx, o)
	})
}

func (m userAccountMods) WithExistingOrganization(em *models.Organization) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.Organization = &userAccountROrganizationR{
			o: o.f.FromExistingOrganization(em),
		}
	})
}

func (m userAccountMods) WithoutOrganization() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.Organization = nil
	})
}

func (m userAccountMods) WithCreatedByPersonalAccessTokens(number int, related *PersonalAccessTokenTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByPersonalAccessTokens = []*userAccountRCreatedByPersonalAccessTokensR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userAccountMods) WithNewCreatedByPersonalAccessTokens(number int, mods ...PersonalAccessTokenMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewPersonalAccessTokenWithContext(ctx, mods...)
		m.WithCreatedByPersonalAccessTokens(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddCreatedByPersonalAccessTokens(number int, related *PersonalAccessTokenTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByPersonalAccessTokens = append(o.r.CreatedByPersonalAccessTokens, &userAccountRCreatedByPersonalAccessTokensR{
			number: number,
			o:      related,
		})
	})
}

func (m userAccountMods) AddNewCreatedByPersonalAccessTokens(number int, mods ...PersonalAccessTokenMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewPersonalAccessTokenWithContext(ctx, mods...)
		m.AddCreatedByPersonalAccessTokens(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddExistingCreatedByPersonalAccessTokens(existingModels ...*models.PersonalAccessToken) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByPersonalAccessTokens = append(o.r.CreatedByPersonalAccessTokens, &userAccountRCreatedByPersonalAccessTokensR{
				o: o.f.FromExistingPersonalAccessToken(em),
			})
		}
	})
}

func (m userAccountMods) WithoutCreatedByPersonalAccessTokens() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByPersonalAccessTokens = nil
	})
}

func (m userAccountMods) WithUpdatedByPersonalAccessTokens(number int, related *PersonalAccessTokenTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByPersonalAccessTokens = []*userAccountRUpdatedByPersonalAccessTokensR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userAccountMods) WithNewUpdatedByPersonalAccessTokens(number int, mods ...PersonalAccessTokenMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewPersonalAccessTokenWithContext(ctx, mods...)
		m.WithUpdatedByPersonalAccessTokens(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddUpdatedByPersonalAccessTokens(number int, related *PersonalAccessTokenTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByPersonalAccessTokens = append(o.r.UpdatedByPersonalAccessTokens, &userAccountRUpdatedByPersonalAccessTokensR{
			number: number,
			o:      related,
		})
	})
}

func (m userAccountMods) AddNewUpdatedByPersonalAccessTokens(number int, mods ...PersonalAccessTokenMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewPersonalAccessTokenWithContext(ctx, mods...)
		m.AddUpdatedByPersonalAccessTokens(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddExistingUpdatedByPersonalAccessTokens(existingModels ...*models.PersonalAccessToken) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		for _, em := range existingModels {
			o.r.UpdatedByPersonalAccessTokens = append(o.r.UpdatedByPersonalAccessTokens, &userAccountRUpdatedByPersonalAccessTokensR{
				o: o.f.FromExistingPersonalAccessToken(em),
			})
		}
	})
}

func (m userAccountMods) WithoutUpdatedByPersonalAccessTokens() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByPersonalAccessTokens = nil
	})
}

func (m userAccountMods) WithCreatedByRepositories(number int, related *RepositoryTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByRepositories = []*userAccountRCreatedByRepositoriesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userAccountMods) WithNewCreatedByRepositories(number int, mods ...RepositoryMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewRepositoryWithContext(ctx, mods...)
		m.WithCreatedByRepositories(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddCreatedByRepositories(number int, related *RepositoryTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByRepositories = append(o.r.CreatedByRepositories, &userAccountRCreatedByRepositoriesR{
			number: number,
			o:      related,
		})
	})
}

func (m userAccountMods) AddNewCreatedByRepositories(number int, mods ...RepositoryMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewRepositoryWithContext(ctx, mods...)
		m.AddCreatedByRepositories(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddExistingCreatedByRepositories(existingModels ...*models.Repository) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByRepositories = append(o.r.CreatedByRepositories, &userAccountRCreatedByRepositoriesR{
				o: o.f.FromExistingRepository(em),
			})
		}
	})
}

func (m userAccountMods) WithoutCreatedByRepositories() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.CreatedByRepositories = nil
	})
}

func (m userAccountMods) WithUpdatedByRepositories(number int, related *RepositoryTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByRepositories = []*userAccountRUpdatedByRepositoriesR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userAccountMods) WithNewUpdatedByRepositories(number int, mods ...RepositoryMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewRepositoryWithContext(ctx, mods...)
		m.WithUpdatedByRepositories(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddUpdatedByRepositories(number int, related *RepositoryTemplate) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByRepositories = append(o.r.UpdatedByRepositories, &userAccountRUpdatedByRepositoriesR{
			number: number,
			o:      related,
		})
	})
}

func (m userAccountMods) AddNewUpdatedByRepositories(number int, mods ...RepositoryMod) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		related := o.f.NewRepositoryWithContext(ctx, mods...)
		m.AddUpdatedByRepositories(number, related).Apply(ctx, o)
	})
}

func (m userAccountMods) AddExistingUpdatedByRepositories(existingModels ...*models.Repository) UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		for _, em := range existingModels {
			o.r.UpdatedByRepositories = append(o.r.UpdatedByRepositories, &userAccountRUpdatedByRepositoriesR{
				o: o.f.FromExistingRepository(em),
			})
		}
	})
}

func (m userAccountMods) WithoutUpdatedByRepositories() UserAccountMod {
	return UserAccountModFunc(func(ctx context.Context, o *UserAccountTemplate) {
		o.r.UpdatedByRepositories = nil
	})
}
