// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ClusterUpgradeErrors = &clusterUpgradeErrors{
	ErrUniqueClusterUpgradePkey: &UniqueConstraintError{
		schema:  "",
		table:   "cluster_upgrade",
		columns: []string{"cluster_id"},
		s:       "cluster_upgrade_pkey",
	},
}

type clusterUpgradeErrors struct {
	ErrUniqueClusterUpgradePkey *UniqueConstraintError
}
