// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var DeprecatedAPIErrors = &deprecatedAPIErrors{
	ErrUniqueDeprecatedApiPkey: &UniqueConstraintError{
		schema:  "",
		table:   "deprecated_api",
		columns: []string{"cluster_id", "current_group_version", "kind"},
		s:       "deprecated_api_pkey",
	},
}

type deprecatedAPIErrors struct {
	ErrUniqueDeprecatedApiPkey *UniqueConstraintError
}
