// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ForgotPasswordTokenErrors = &forgotPasswordTokenErrors{
	ErrUniqueForgotPasswordTokenPkey: &UniqueConstraintError{
		schema:  "",
		table:   "forgot_password_token",
		columns: []string{"user_id"},
		s:       "forgot_password_token_pkey",
	},
}

type forgotPasswordTokenErrors struct {
	ErrUniqueForgotPasswordTokenPkey *UniqueConstraintError
}
