// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PasswordAuthErrors = &passwordAuthErrors{
	ErrUniquePasswordAuthPkey: &UniqueConstraintError{
		schema:  "",
		table:   "password_auth",
		columns: []string{"email"},
		s:       "password_auth_pkey",
	},
}

type passwordAuthErrors struct {
	ErrUniquePasswordAuthPkey *UniqueConstraintError
}
