// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RepositoryPersonalAccessTokenErrors = &repositoryPersonalAccessTokenErrors{
	ErrUniqueRepositoryPersonalAccessTokenPkey: &UniqueConstraintError{
		schema:  "",
		table:   "repository_personal_access_token",
		columns: []string{"repository_id", "personal_access_token_id"},
		s:       "repository_personal_access_token_pkey",
	},
}

type repositoryPersonalAccessTokenErrors struct {
	ErrUniqueRepositoryPersonalAccessTokenPkey *UniqueConstraintError
}
