// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SandboxErrors = &sandboxErrors{
	ErrUniqueSandboxPkey: &UniqueConstraintError{
		schema:  "",
		table:   "sandbox",
		columns: []string{"id"},
		s:       "sandbox_pkey",
	},
}

type sandboxErrors struct {
	ErrUniqueSandboxPkey *UniqueConstraintError
}
