// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SandboxClusterInfoErrors = &sandboxClusterInfoErrors{
	ErrUniqueSandboxClusterInfoPkey: &UniqueConstraintError{
		schema:  "",
		table:   "sandbox_cluster_info",
		columns: []string{"sandbox_id"},
		s:       "sandbox_cluster_info_pkey",
	},
}

type sandboxClusterInfoErrors struct {
	ErrUniqueSandboxClusterInfoPkey *UniqueConstraintError
}
