// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UnmatchedComponentErrors = &unmatchedComponentErrors{
	ErrUniqueUnmatchedComponentPkey: &UniqueConstraintError{
		schema:  "",
		table:   "unmatched_component",
		columns: []string{"cluster_id", "object_id", "name"},
		s:       "unmatched_component_pkey",
	},
}

type unmatchedComponentErrors struct {
	ErrUniqueUnmatchedComponentPkey *UniqueConstraintError
}
