// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var UpgradeableComponentErrors = &upgradeableComponentErrors{
	ErrUniqueUpgradeableComponentPkey: &UniqueConstraintError{
		schema:  "",
		table:   "upgradeable_component",
		columns: []string{"cluster_id", "object_id", "name"},
		s:       "upgradeable_component_pkey",
	},
}

type upgradeableComponentErrors struct {
	ErrUniqueUpgradeableComponentPkey *UniqueConstraintError
}
