// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ClusterInfos = Table[
	clusterInfoColumns,
	clusterInfoIndexes,
	clusterInfoForeignKeys,
	clusterInfoUniques,
	clusterInfoChecks,
]{
	Schema: "",
	Name:   "cluster_info",
	Columns: clusterInfoColumns{
		ClusterID: column{
			Name:      "cluster_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Version: column{
			Name:      "version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Platform: column{
			Name:      "platform",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "'unknown'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: clusterInfoIndexes{
		ClusterInfoPkey: index{
			Type: "btree",
			Name: "cluster_info_pkey",
			Columns: []indexColumn{
				{
					Name:         "cluster_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "cluster_info_pkey",
		Columns: []string{"cluster_id"},
		Comment: "",
	},
	ForeignKeys: clusterInfoForeignKeys{
		ClusterInfoClusterInfoClusterIDFkey: foreignKey{
			constraint: constraint{
				Name:    "cluster_info.cluster_info_cluster_id_fkey",
				Columns: []string{"cluster_id"},
				Comment: "",
			},
			ForeignTable:   "cluster",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type clusterInfoColumns struct {
	ClusterID column
	Name      column
	Version   column
	Platform  column
	CreatedAt column
	UpdatedAt column
	Provider  column
}

func (c clusterInfoColumns) AsSlice() []column {
	return []column{
		c.ClusterID, c.Name, c.Version, c.Platform, c.CreatedAt, c.UpdatedAt, c.Provider,
	}
}

type clusterInfoIndexes struct {
	ClusterInfoPkey index
}

func (i clusterInfoIndexes) AsSlice() []index {
	return []index{
		i.ClusterInfoPkey,
	}
}

type clusterInfoForeignKeys struct {
	ClusterInfoClusterInfoClusterIDFkey foreignKey
}

func (f clusterInfoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ClusterInfoClusterInfoClusterIDFkey,
	}
}

type clusterInfoUniques struct{}

func (u clusterInfoUniques) AsSlice() []constraint {
	return []constraint{}
}

type clusterInfoChecks struct{}

func (c clusterInfoChecks) AsSlice() []check {
	return []check{}
}
