// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ClusterResourceCounts = Table[
	clusterResourceCountColumns,
	clusterResourceCountIndexes,
	clusterResourceCountForeignKeys,
	clusterResourceCountUniques,
	clusterResourceCountChecks,
]{
	Schema:  "",
	Name:    "cluster_resource_count",
	Columns: clusterResourceCountColumns{},
	Indexes: clusterResourceCountIndexes{
		UniqIdxClusterResourceCountClusterID: index{
			Type: "btree",
			Name: "uniq_idx_cluster_resource_count_cluster_id",
			Columns: []indexColumn{
				{
					Name:         "cluster_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},

	Comment: "",
}

type clusterResourceCountColumns struct{}

func (c clusterResourceCountColumns) AsSlice() []column {
	return []column{}
}

type clusterResourceCountIndexes struct {
	UniqIdxClusterResourceCountClusterID index
}

func (i clusterResourceCountIndexes) AsSlice() []index {
	return []index{
		i.UniqIdxClusterResourceCountClusterID,
	}
}

type clusterResourceCountForeignKeys struct{}

func (f clusterResourceCountForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type clusterResourceCountUniques struct{}

func (u clusterResourceCountUniques) AsSlice() []constraint {
	return []constraint{}
}

type clusterResourceCountChecks struct{}

func (c clusterResourceCountChecks) AsSlice() []check {
	return []check{}
}
