// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ClusterUpgrades = Table[
	clusterUpgradeColumns,
	clusterUpgradeIndexes,
	clusterUpgradeForeignKeys,
	clusterUpgradeUniques,
	clusterUpgradeChecks,
]{
	Schema: "",
	Name:   "cluster_upgrade",
	Columns: clusterUpgradeColumns{
		ClusterID: column{
			Name:      "cluster_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		NextVersion: column{
			Name:      "next_version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: clusterUpgradeIndexes{
		ClusterUpgradePkey: index{
			Type: "btree",
			Name: "cluster_upgrade_pkey",
			Columns: []indexColumn{
				{
					Name:         "cluster_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "cluster_upgrade_pkey",
		Columns: []string{"cluster_id"},
		Comment: "",
	},
	ForeignKeys: clusterUpgradeForeignKeys{
		ClusterUpgradeClusterUpgradeClusterIDFkey: foreignKey{
			constraint: constraint{
				Name:    "cluster_upgrade.cluster_upgrade_cluster_id_fkey",
				Columns: []string{"cluster_id"},
				Comment: "",
			},
			ForeignTable:   "cluster",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type clusterUpgradeColumns struct {
	ClusterID   column
	NextVersion column
	CreatedAt   column
	UpdatedAt   column
}

func (c clusterUpgradeColumns) AsSlice() []column {
	return []column{
		c.ClusterID, c.NextVersion, c.CreatedAt, c.UpdatedAt,
	}
}

type clusterUpgradeIndexes struct {
	ClusterUpgradePkey index
}

func (i clusterUpgradeIndexes) AsSlice() []index {
	return []index{
		i.ClusterUpgradePkey,
	}
}

type clusterUpgradeForeignKeys struct {
	ClusterUpgradeClusterUpgradeClusterIDFkey foreignKey
}

func (f clusterUpgradeForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ClusterUpgradeClusterUpgradeClusterIDFkey,
	}
}

type clusterUpgradeUniques struct{}

func (u clusterUpgradeUniques) AsSlice() []constraint {
	return []constraint{}
}

type clusterUpgradeChecks struct{}

func (c clusterUpgradeChecks) AsSlice() []check {
	return []check{}
}
