// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var DeprecatedApis = Table[
	deprecatedAPIColumns,
	deprecatedAPIIndexes,
	deprecatedAPIForeignKeys,
	deprecatedAPIUniques,
	deprecatedAPIChecks,
]{
	Schema: "",
	Name:   "deprecated_api",
	Columns: deprecatedAPIColumns{
		ClusterID: column{
			Name:      "cluster_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CurrentGroupVersion: column{
			Name:      "current_group_version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Kind: column{
			Name:      "kind",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ClusterK8SVersion: column{
			Name:      "cluster_k8s_version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Deprecated: column{
			Name:      "deprecated",
			DBType:    "boolean",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeprecatedIn: column{
			Name:      "deprecated_in",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RemovedIn: column{
			Name:      "removed_in",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReplacementVersion: column{
			Name:      "replacement_version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: deprecatedAPIIndexes{
		DeprecatedAPIPkey: index{
			Type: "btree",
			Name: "deprecated_api_pkey",
			Columns: []indexColumn{
				{
					Name:         "cluster_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "current_group_version",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "kind",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "deprecated_api_pkey",
		Columns: []string{"cluster_id", "current_group_version", "kind"},
		Comment: "",
	},
	ForeignKeys: deprecatedAPIForeignKeys{
		DeprecatedAPIDeprecatedAPIClusterIDFkey: foreignKey{
			constraint: constraint{
				Name:    "deprecated_api.deprecated_api_cluster_id_fkey",
				Columns: []string{"cluster_id"},
				Comment: "",
			},
			ForeignTable:   "cluster",
			ForeignColumns: []string{"id"},
		},
		DeprecatedAPIDeprecatedAPIOrganizationIDFkey: foreignKey{
			constraint: constraint{
				Name:    "deprecated_api.deprecated_api_organization_id_fkey",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organization",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type deprecatedAPIColumns struct {
	ClusterID           column
	OrganizationID      column
	CurrentGroupVersion column
	Kind                column
	Name                column
	ClusterK8SVersion   column
	Deprecated          column
	DeprecatedIn        column
	RemovedIn           column
	ReplacementVersion  column
}

func (c deprecatedAPIColumns) AsSlice() []column {
	return []column{
		c.ClusterID, c.OrganizationID, c.CurrentGroupVersion, c.Kind, c.Name, c.ClusterK8SVersion, c.Deprecated, c.DeprecatedIn, c.RemovedIn, c.ReplacementVersion,
	}
}

type deprecatedAPIIndexes struct {
	DeprecatedAPIPkey index
}

func (i deprecatedAPIIndexes) AsSlice() []index {
	return []index{
		i.DeprecatedAPIPkey,
	}
}

type deprecatedAPIForeignKeys struct {
	DeprecatedAPIDeprecatedAPIClusterIDFkey      foreignKey
	DeprecatedAPIDeprecatedAPIOrganizationIDFkey foreignKey
}

func (f deprecatedAPIForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.DeprecatedAPIDeprecatedAPIClusterIDFkey, f.DeprecatedAPIDeprecatedAPIOrganizationIDFkey,
	}
}

type deprecatedAPIUniques struct{}

func (u deprecatedAPIUniques) AsSlice() []constraint {
	return []constraint{}
}

type deprecatedAPIChecks struct{}

func (c deprecatedAPIChecks) AsSlice() []check {
	return []check{}
}
