// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var OAuths = Table[
	oauthColumns,
	oauthIndexes,
	oauthForeignKeys,
	oauthUniques,
	oauthChecks,
]{
	Schema: "",
	Name:   "oauth",
	Columns: oauthColumns{
		Email: column{
			Name:      "email",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: oauthIndexes{
		OauthPkey: index{
			Type: "btree",
			Name: "oauth_pkey",
			Columns: []indexColumn{
				{
					Name:         "email",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "oauth_pkey",
		Columns: []string{"email"},
		Comment: "",
	},

	Comment: "",
}

type oauthColumns struct {
	Email     column
	Provider  column
	CreatedAt column
	UpdatedAt column
}

func (c oauthColumns) AsSlice() []column {
	return []column{
		c.Email, c.Provider, c.CreatedAt, c.UpdatedAt,
	}
}

type oauthIndexes struct {
	OauthPkey index
}

func (i oauthIndexes) AsSlice() []index {
	return []index{
		i.OauthPkey,
	}
}

type oauthForeignKeys struct{}

func (f oauthForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type oauthUniques struct{}

func (u oauthUniques) AsSlice() []constraint {
	return []constraint{}
}

type oauthChecks struct{}

func (c oauthChecks) AsSlice() []check {
	return []check{}
}
