// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PersonalAccessTokens = Table[
	personalAccessTokenColumns,
	personalAccessTokenIndexes,
	personalAccessTokenForeignKeys,
	personalAccessTokenUniques,
	personalAccessTokenChecks,
]{
	Schema: "",
	Name:   "personal_access_token",
	Columns: personalAccessTokenColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		EncryptedValue: column{
			Name:      "encrypted_value",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ExpiredAt: column{
			Name:      "expired_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Owner: column{
			Name:      "owner",
			DBType:    "text",
			Default:   "'unknown'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: personalAccessTokenIndexes{
		CredentialPkey: index{
			Type: "btree",
			Name: "credential_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		UniqPersonalAccessTokenOrgName: index{
			Type: "btree",
			Name: "uniq_personal_access_token_org_name",
			Columns: []indexColumn{
				{
					Name:         "organization_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "provider",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
				{
					Name:         "name",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false, false, false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "credential_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: personalAccessTokenForeignKeys{
		PersonalAccessTokenCredentialOrganizationIDFkey: foreignKey{
			constraint: constraint{
				Name:    "personal_access_token.credential_organization_id_fkey",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organization",
			ForeignColumns: []string{"id"},
		},
		PersonalAccessTokenPersonalAccessTokenCreatedByFkey: foreignKey{
			constraint: constraint{
				Name:    "personal_access_token.personal_access_token_created_by_fkey",
				Columns: []string{"created_by"},
				Comment: "",
			},
			ForeignTable:   "user_account",
			ForeignColumns: []string{"id"},
		},
		PersonalAccessTokenPersonalAccessTokenUpdatedByFkey: foreignKey{
			constraint: constraint{
				Name:    "personal_access_token.personal_access_token_updated_by_fkey",
				Columns: []string{"updated_by"},
				Comment: "",
			},
			ForeignTable:   "user_account",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: personalAccessTokenUniques{
		UniqPersonalAccessTokenOrgName: constraint{
			Name:    "uniq_personal_access_token_org_name",
			Columns: []string{"organization_id", "provider", "name"},
			Comment: "",
		},
	},

	Comment: "",
}

type personalAccessTokenColumns struct {
	ID             column
	OrganizationID column
	Provider       column
	Name           column
	EncryptedValue column
	ExpiredAt      column
	CreatedAt      column
	UpdatedAt      column
	Owner          column
	CreatedBy      column
	UpdatedBy      column
}

func (c personalAccessTokenColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrganizationID, c.Provider, c.Name, c.EncryptedValue, c.ExpiredAt, c.CreatedAt, c.UpdatedAt, c.Owner, c.CreatedBy, c.UpdatedBy,
	}
}

type personalAccessTokenIndexes struct {
	CredentialPkey                 index
	UniqPersonalAccessTokenOrgName index
}

func (i personalAccessTokenIndexes) AsSlice() []index {
	return []index{
		i.CredentialPkey, i.UniqPersonalAccessTokenOrgName,
	}
}

type personalAccessTokenForeignKeys struct {
	PersonalAccessTokenCredentialOrganizationIDFkey     foreignKey
	PersonalAccessTokenPersonalAccessTokenCreatedByFkey foreignKey
	PersonalAccessTokenPersonalAccessTokenUpdatedByFkey foreignKey
}

func (f personalAccessTokenForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PersonalAccessTokenCredentialOrganizationIDFkey, f.PersonalAccessTokenPersonalAccessTokenCreatedByFkey, f.PersonalAccessTokenPersonalAccessTokenUpdatedByFkey,
	}
}

type personalAccessTokenUniques struct {
	UniqPersonalAccessTokenOrgName constraint
}

func (u personalAccessTokenUniques) AsSlice() []constraint {
	return []constraint{
		u.UniqPersonalAccessTokenOrgName,
	}
}

type personalAccessTokenChecks struct{}

func (c personalAccessTokenChecks) AsSlice() []check {
	return []check{}
}
