// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Repositories = Table[
	repositoryColumns,
	repositoryIndexes,
	repositoryForeignKeys,
	repositoryUniques,
	repositoryChecks,
]{
	Schema: "",
	Name:   "repository",
	Columns: repositoryColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrganizationID: column{
			Name:      "organization_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Description: column{
			Name:      "description",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Provider: column{
			Name:      "provider",
			DBType:    "text",
			Default:   "'github'::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedBy: column{
			Name:      "created_by",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedBy: column{
			Name:      "updated_by",
			DBType:    "uuid",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Namespace: column{
			Name:      "namespace",
			DBType:    "text",
			Default:   "''::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: repositoryIndexes{
		RepositoryPkey: index{
			Type: "btree",
			Name: "repository_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "repository_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: repositoryForeignKeys{
		RepositoryRepositoryCreatedByFkey: foreignKey{
			constraint: constraint{
				Name:    "repository.repository_created_by_fkey",
				Columns: []string{"created_by"},
				Comment: "",
			},
			ForeignTable:   "user_account",
			ForeignColumns: []string{"id"},
		},
		RepositoryRepositoryOrganizationIDFkey: foreignKey{
			constraint: constraint{
				Name:    "repository.repository_organization_id_fkey",
				Columns: []string{"organization_id"},
				Comment: "",
			},
			ForeignTable:   "organization",
			ForeignColumns: []string{"id"},
		},
		RepositoryRepositoryUpdatedByFkey: foreignKey{
			constraint: constraint{
				Name:    "repository.repository_updated_by_fkey",
				Columns: []string{"updated_by"},
				Comment: "",
			},
			ForeignTable:   "user_account",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type repositoryColumns struct {
	ID             column
	OrganizationID column
	Name           column
	Description    column
	CreatedAt      column
	UpdatedAt      column
	Provider       column
	CreatedBy      column
	UpdatedBy      column
	Namespace      column
}

func (c repositoryColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrganizationID, c.Name, c.Description, c.CreatedAt, c.UpdatedAt, c.Provider, c.CreatedBy, c.UpdatedBy, c.Namespace,
	}
}

type repositoryIndexes struct {
	RepositoryPkey index
}

func (i repositoryIndexes) AsSlice() []index {
	return []index{
		i.RepositoryPkey,
	}
}

type repositoryForeignKeys struct {
	RepositoryRepositoryCreatedByFkey      foreignKey
	RepositoryRepositoryOrganizationIDFkey foreignKey
	RepositoryRepositoryUpdatedByFkey      foreignKey
}

func (f repositoryForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.RepositoryRepositoryCreatedByFkey, f.RepositoryRepositoryOrganizationIDFkey, f.RepositoryRepositoryUpdatedByFkey,
	}
}

type repositoryUniques struct{}

func (u repositoryUniques) AsSlice() []constraint {
	return []constraint{}
}

type repositoryChecks struct{}

func (c repositoryChecks) AsSlice() []check {
	return []check{}
}
