// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Sandboxes = Table[
	sandboxColumns,
	sandboxIndexes,
	sandboxForeignKeys,
	sandboxUniques,
	sandboxChecks,
]{
	Schema: "",
	Name:   "sandbox",
	Columns: sandboxColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sandboxIndexes{
		SandboxPkey: index{
			Type: "btree",
			Name: "sandbox_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "sandbox_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type sandboxColumns struct {
	ID   column
	Name column
}

func (c sandboxColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name,
	}
}

type sandboxIndexes struct {
	SandboxPkey index
}

func (i sandboxIndexes) AsSlice() []index {
	return []index{
		i.SandboxPkey,
	}
}

type sandboxForeignKeys struct{}

func (f sandboxForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type sandboxUniques struct{}

func (u sandboxUniques) AsSlice() []constraint {
	return []constraint{}
}

type sandboxChecks struct{}

func (c sandboxChecks) AsSlice() []check {
	return []check{}
}
