// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SandboxDeprecatedAPIGroups = Table[
	sandboxDeprecatedAPIGroupColumns,
	sandboxDeprecatedAPIGroupIndexes,
	sandboxDeprecatedAPIGroupForeignKeys,
	sandboxDeprecatedAPIGroupUniques,
	sandboxDeprecatedAPIGroupChecks,
]{
	Schema: "",
	Name:   "sandbox_deprecated_api_group",
	Columns: sandboxDeprecatedAPIGroupColumns{
		SandboxID: column{
			Name:      "sandbox_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DeprecatedApis: column{
			Name:      "deprecated_apis",
			DBType:    "jsonb",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sandboxDeprecatedAPIGroupIndexes{
		SandboxDeprecatedAPIGroupPkey: index{
			Type: "btree",
			Name: "sandbox_deprecated_api_group_pkey",
			Columns: []indexColumn{
				{
					Name:         "sandbox_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "sandbox_deprecated_api_group_pkey",
		Columns: []string{"sandbox_id"},
		Comment: "",
	},
	ForeignKeys: sandboxDeprecatedAPIGroupForeignKeys{
		SandboxDeprecatedAPIGroupSandboxDeprecatedAPIGroupSandboxIDFkey: foreignKey{
			constraint: constraint{
				Name:    "sandbox_deprecated_api_group.sandbox_deprecated_api_group_sandbox_id_fkey",
				Columns: []string{"sandbox_id"},
				Comment: "",
			},
			ForeignTable:   "sandbox",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type sandboxDeprecatedAPIGroupColumns struct {
	SandboxID      column
	DeprecatedApis column
}

func (c sandboxDeprecatedAPIGroupColumns) AsSlice() []column {
	return []column{
		c.SandboxID, c.DeprecatedApis,
	}
}

type sandboxDeprecatedAPIGroupIndexes struct {
	SandboxDeprecatedAPIGroupPkey index
}

func (i sandboxDeprecatedAPIGroupIndexes) AsSlice() []index {
	return []index{
		i.SandboxDeprecatedAPIGroupPkey,
	}
}

type sandboxDeprecatedAPIGroupForeignKeys struct {
	SandboxDeprecatedAPIGroupSandboxDeprecatedAPIGroupSandboxIDFkey foreignKey
}

func (f sandboxDeprecatedAPIGroupForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.SandboxDeprecatedAPIGroupSandboxDeprecatedAPIGroupSandboxIDFkey,
	}
}

type sandboxDeprecatedAPIGroupUniques struct{}

func (u sandboxDeprecatedAPIGroupUniques) AsSlice() []constraint {
	return []constraint{}
}

type sandboxDeprecatedAPIGroupChecks struct{}

func (c sandboxDeprecatedAPIGroupChecks) AsSlice() []check {
	return []check{}
}
