// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var SandboxClusterInfos = Table[
	sandboxClusterInfoColumns,
	sandboxClusterInfoIndexes,
	sandboxClusterInfoForeignKeys,
	sandboxClusterInfoUniques,
	sandboxClusterInfoChecks,
]{
	Schema: "",
	Name:   "sandbox_cluster_info",
	Columns: sandboxClusterInfoColumns{
		SandboxID: column{
			Name:      "sandbox_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Version: column{
			Name:      "version",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Platform: column{
			Name:      "platform",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: sandboxClusterInfoIndexes{
		SandboxClusterInfoPkey: index{
			Type: "btree",
			Name: "sandbox_cluster_info_pkey",
			Columns: []indexColumn{
				{
					Name:         "sandbox_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "sandbox_cluster_info_pkey",
		Columns: []string{"sandbox_id"},
		Comment: "",
	},
	ForeignKeys: sandboxClusterInfoForeignKeys{
		SandboxClusterInfoSandboxClusterInfoSandboxIDFkey: foreignKey{
			constraint: constraint{
				Name:    "sandbox_cluster_info.sandbox_cluster_info_sandbox_id_fkey",
				Columns: []string{"sandbox_id"},
				Comment: "",
			},
			ForeignTable:   "sandbox",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type sandboxClusterInfoColumns struct {
	SandboxID column
	Name      column
	Version   column
	Platform  column
}

func (c sandboxClusterInfoColumns) AsSlice() []column {
	return []column{
		c.SandboxID, c.Name, c.Version, c.Platform,
	}
}

type sandboxClusterInfoIndexes struct {
	SandboxClusterInfoPkey index
}

func (i sandboxClusterInfoIndexes) AsSlice() []index {
	return []index{
		i.SandboxClusterInfoPkey,
	}
}

type sandboxClusterInfoForeignKeys struct {
	SandboxClusterInfoSandboxClusterInfoSandboxIDFkey foreignKey
}

func (f sandboxClusterInfoForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.SandboxClusterInfoSandboxClusterInfoSandboxIDFkey,
	}
}

type sandboxClusterInfoUniques struct{}

func (u sandboxClusterInfoUniques) AsSlice() []constraint {
	return []constraint{}
}

type sandboxClusterInfoChecks struct{}

func (c sandboxClusterInfoChecks) AsSlice() []check {
	return []check{}
}
