// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ClusterTag is an object representing the database table.
type ClusterTag struct {
	ClusterID uuid.UUID `db:"cluster_id,pk" `
	Name      string    `db:"name,pk" `

	R clusterTagR `db:"-" `
}

// ClusterTagSlice is an alias for a slice of pointers to ClusterTag.
// This should almost always be used instead of []*ClusterTag.
type ClusterTagSlice []*ClusterTag

// ClusterTags contains methods to work with the cluster_tag table
var ClusterTags = psql.NewTablex[*ClusterTag, ClusterTagSlice, *ClusterTagSetter]("", "cluster_tag", buildClusterTagColumns("cluster_tag"))

// ClusterTagsQuery is a query on the cluster_tag table
type ClusterTagsQuery = *psql.ViewQuery[*ClusterTag, ClusterTagSlice]

// clusterTagR is where relationships are stored.
type clusterTagR struct {
	Cluster *Cluster // cluster_tag.cluster_tag_cluster_id_fkey
}

func buildClusterTagColumns(alias string) clusterTagColumns {
	return clusterTagColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"cluster_id", "name",
		).WithParent("cluster_tag"),
		tableAlias: alias,
		ClusterID:  psql.Quote(alias, "cluster_id"),
		Name:       psql.Quote(alias, "name"),
	}
}

type clusterTagColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ClusterID  psql.Expression
	Name       psql.Expression
}

func (c clusterTagColumns) Alias() string {
	return c.tableAlias
}

func (clusterTagColumns) AliasedAs(alias string) clusterTagColumns {
	return buildClusterTagColumns(alias)
}

// ClusterTagSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ClusterTagSetter struct {
	ClusterID omit.Val[uuid.UUID] `db:"cluster_id,pk" `
	Name      omit.Val[string]    `db:"name,pk" `
}

func (s ClusterTagSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.ClusterID.IsValue() {
		vals = append(vals, "cluster_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	return vals
}

func (s ClusterTagSetter) Overwrite(t *ClusterTag) {
	if s.ClusterID.IsValue() {
		t.ClusterID = s.ClusterID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
}

func (s *ClusterTagSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ClusterTags.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.ClusterID.IsValue() {
			vals[0] = psql.Arg(s.ClusterID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ClusterTagSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ClusterTagSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.ClusterID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cluster_id")...),
			psql.Arg(s.ClusterID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	return exprs
}

// FindClusterTag retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindClusterTag(ctx context.Context, exec bob.Executor, ClusterIDPK uuid.UUID, NamePK string, cols ...string) (*ClusterTag, error) {
	if len(cols) == 0 {
		return ClusterTags.Query(
			sm.Where(ClusterTags.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
			sm.Where(ClusterTags.Columns.Name.EQ(psql.Arg(NamePK))),
		).One(ctx, exec)
	}

	return ClusterTags.Query(
		sm.Where(ClusterTags.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
		sm.Where(ClusterTags.Columns.Name.EQ(psql.Arg(NamePK))),
		sm.Columns(ClusterTags.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ClusterTagExists checks the presence of a single record by primary key
func ClusterTagExists(ctx context.Context, exec bob.Executor, ClusterIDPK uuid.UUID, NamePK string) (bool, error) {
	return ClusterTags.Query(
		sm.Where(ClusterTags.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
		sm.Where(ClusterTags.Columns.Name.EQ(psql.Arg(NamePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ClusterTag is retrieved from the database
func (o *ClusterTag) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClusterTags.AfterSelectHooks.RunHooks(ctx, exec, ClusterTagSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ClusterTags.AfterInsertHooks.RunHooks(ctx, exec, ClusterTagSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ClusterTags.AfterUpdateHooks.RunHooks(ctx, exec, ClusterTagSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ClusterTags.AfterDeleteHooks.RunHooks(ctx, exec, ClusterTagSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ClusterTag
func (o *ClusterTag) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.ClusterID,
		o.Name,
	)
}

func (o *ClusterTag) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("cluster_tag", "cluster_id"), psql.Quote("cluster_tag", "name")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ClusterTag
func (o *ClusterTag) Update(ctx context.Context, exec bob.Executor, s *ClusterTagSetter) error {
	v, err := ClusterTags.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ClusterTag record with an executor
func (o *ClusterTag) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ClusterTags.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ClusterTag using the executor
func (o *ClusterTag) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ClusterTags.Query(
		sm.Where(ClusterTags.Columns.ClusterID.EQ(psql.Arg(o.ClusterID))),
		sm.Where(ClusterTags.Columns.Name.EQ(psql.Arg(o.Name))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ClusterTagSlice is retrieved from the database
func (o ClusterTagSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClusterTags.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ClusterTags.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ClusterTags.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ClusterTags.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ClusterTagSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("cluster_tag", "cluster_id"), psql.Quote("cluster_tag", "name")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ClusterTagSlice) copyMatchingRows(from ...*ClusterTag) {
	for i, old := range o {
		for _, new := range from {
			if new.ClusterID != old.ClusterID {
				continue
			}
			if new.Name != old.Name {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ClusterTagSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClusterTags.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClusterTag:
				o.copyMatchingRows(retrieved)
			case []*ClusterTag:
				o.copyMatchingRows(retrieved...)
			case ClusterTagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClusterTag or a slice of ClusterTag
				// then run the AfterUpdateHooks on the slice
				_, err = ClusterTags.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ClusterTagSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClusterTags.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClusterTag:
				o.copyMatchingRows(retrieved)
			case []*ClusterTag:
				o.copyMatchingRows(retrieved...)
			case ClusterTagSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClusterTag or a slice of ClusterTag
				// then run the AfterDeleteHooks on the slice
				_, err = ClusterTags.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ClusterTagSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ClusterTagSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClusterTags.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ClusterTagSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClusterTags.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ClusterTagSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ClusterTags.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Cluster starts a query for related objects on cluster
func (o *ClusterTag) Cluster(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	return Clusters.Query(append(mods,
		sm.Where(Clusters.Columns.ID.EQ(psql.Arg(o.ClusterID))),
	)...)
}

func (os ClusterTagSlice) Cluster(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	pkClusterID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkClusterID = append(pkClusterID, o.ClusterID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkClusterID), "uuid[]")),
	))

	return Clusters.Query(append(mods,
		sm.Where(psql.Group(Clusters.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachClusterTagCluster0(ctx context.Context, exec bob.Executor, count int, clusterTag0 *ClusterTag, cluster1 *Cluster) (*ClusterTag, error) {
	setter := &ClusterTagSetter{
		ClusterID: omit.From(cluster1.ID),
	}

	err := clusterTag0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterTagCluster0: %w", err)
	}

	return clusterTag0, nil
}

func (clusterTag0 *ClusterTag) InsertCluster(ctx context.Context, exec bob.Executor, related *ClusterSetter) error {
	var err error

	cluster1, err := Clusters.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachClusterTagCluster0(ctx, exec, 1, clusterTag0, cluster1)
	if err != nil {
		return err
	}

	clusterTag0.R.Cluster = cluster1

	cluster1.R.ClusterTags = append(cluster1.R.ClusterTags, clusterTag0)

	return nil
}

func (clusterTag0 *ClusterTag) AttachCluster(ctx context.Context, exec bob.Executor, cluster1 *Cluster) error {
	var err error

	_, err = attachClusterTagCluster0(ctx, exec, 1, clusterTag0, cluster1)
	if err != nil {
		return err
	}

	clusterTag0.R.Cluster = cluster1

	cluster1.R.ClusterTags = append(cluster1.R.ClusterTags, clusterTag0)

	return nil
}

type clusterTagWhere[Q psql.Filterable] struct {
	ClusterID psql.WhereMod[Q, uuid.UUID]
	Name      psql.WhereMod[Q, string]
}

func (clusterTagWhere[Q]) AliasedAs(alias string) clusterTagWhere[Q] {
	return buildClusterTagWhere[Q](buildClusterTagColumns(alias))
}

func buildClusterTagWhere[Q psql.Filterable](cols clusterTagColumns) clusterTagWhere[Q] {
	return clusterTagWhere[Q]{
		ClusterID: psql.Where[Q, uuid.UUID](cols.ClusterID),
		Name:      psql.Where[Q, string](cols.Name),
	}
}

func (o *ClusterTag) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Cluster":
		rel, ok := retrieved.(*Cluster)
		if !ok {
			return fmt.Errorf("clusterTag cannot load %T as %q", retrieved, name)
		}

		o.R.Cluster = rel

		if rel != nil {
			rel.R.ClusterTags = ClusterTagSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("clusterTag has no relationship %q", name)
	}
}

type clusterTagPreloader struct {
	Cluster func(...psql.PreloadOption) psql.Preloader
}

func buildClusterTagPreloader() clusterTagPreloader {
	return clusterTagPreloader{
		Cluster: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Cluster, ClusterSlice](psql.PreloadRel{
				Name: "Cluster",
				Sides: []psql.PreloadSide{
					{
						From:        ClusterTags,
						To:          Clusters,
						FromColumns: []string{"cluster_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Clusters.Columns.Names(), opts...)
		},
	}
}

type clusterTagThenLoader[Q orm.Loadable] struct {
	Cluster func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildClusterTagThenLoader[Q orm.Loadable]() clusterTagThenLoader[Q] {
	type ClusterLoadInterface interface {
		LoadCluster(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return clusterTagThenLoader[Q]{
		Cluster: thenLoadBuilder[Q](
			"Cluster",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCluster(ctx, exec, mods...)
			},
		),
	}
}

// LoadCluster loads the clusterTag's Cluster into the .R struct
func (o *ClusterTag) LoadCluster(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Cluster = nil

	related, err := o.Cluster(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ClusterTags = ClusterTagSlice{o}

	o.R.Cluster = related
	return nil
}

// LoadCluster loads the clusterTag's Cluster into the .R struct
func (os ClusterTagSlice) LoadCluster(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusters, err := os.Cluster(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusters {

			if !(o.ClusterID == rel.ID) {
				continue
			}

			rel.R.ClusterTags = append(rel.R.ClusterTags, o)

			o.R.Cluster = rel
			break
		}
	}

	return nil
}

type clusterTagJoins[Q dialect.Joinable] struct {
	typ     string
	Cluster modAs[Q, clusterColumns]
}

func (j clusterTagJoins[Q]) aliasedAs(alias string) clusterTagJoins[Q] {
	return buildClusterTagJoins[Q](buildClusterTagColumns(alias), j.typ)
}

func buildClusterTagJoins[Q dialect.Joinable](cols clusterTagColumns, typ string) clusterTagJoins[Q] {
	return clusterTagJoins[Q]{
		typ: typ,
		Cluster: modAs[Q, clusterColumns]{
			c: Clusters.Columns,
			f: func(to clusterColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Clusters.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ClusterID),
					))
				}

				return mods
			},
		},
	}
}
