// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Cluster is an object representing the database table.
type Cluster struct {
	ID             uuid.UUID `db:"id,pk" `
	OrganizationID uuid.UUID `db:"organization_id" `
	ClusterGroupID uuid.UUID `db:"cluster_group_id" `
	CreatedAt      time.Time `db:"created_at" `
	UpdatedAt      time.Time `db:"updated_at" `
	LastObserved   time.Time `db:"last_observed" `

	R clusterR `db:"-" `
}

// ClusterSlice is an alias for a slice of pointers to Cluster.
// This should almost always be used instead of []*Cluster.
type ClusterSlice []*Cluster

// Clusters contains methods to work with the cluster table
var Clusters = psql.NewTablex[*Cluster, ClusterSlice, *ClusterSetter]("", "cluster", buildClusterColumns("cluster"))

// ClustersQuery is a query on the cluster table
type ClustersQuery = *psql.ViewQuery[*Cluster, ClusterSlice]

// clusterR is where relationships are stored.
type clusterR struct {
	ClusterGroup          *ClusterGroup             // cluster.cluster_cluster_group_id_fkey
	Organization          *Organization             // cluster.cluster_organization_id_fkey
	ClusterInfo           *ClusterInfo              // cluster_info.cluster_info_cluster_id_fkey
	ClusterTags           ClusterTagSlice           // cluster_tag.cluster_tag_cluster_id_fkey
	ClusterUpgrade        *ClusterUpgrade           // cluster_upgrade.cluster_upgrade_cluster_id_fkey
	DeprecatedApis        DeprecatedAPISlice        // deprecated_api.deprecated_api_cluster_id_fkey
	Objects               ObjectSlice               // object.object_cluster_id_fkey
	UnmatchedComponents   UnmatchedComponentSlice   // unmatched_component.unmatched_component_cluster_id_fkey
	UpgradeableComponents UpgradeableComponentSlice // upgradeable_component.upgradeable_component_cluster_id_fkey
}

func buildClusterColumns(alias string) clusterColumns {
	return clusterColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "organization_id", "cluster_group_id", "created_at", "updated_at", "last_observed",
		).WithParent("cluster"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		OrganizationID: psql.Quote(alias, "organization_id"),
		ClusterGroupID: psql.Quote(alias, "cluster_group_id"),
		CreatedAt:      psql.Quote(alias, "created_at"),
		UpdatedAt:      psql.Quote(alias, "updated_at"),
		LastObserved:   psql.Quote(alias, "last_observed"),
	}
}

type clusterColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	OrganizationID psql.Expression
	ClusterGroupID psql.Expression
	CreatedAt      psql.Expression
	UpdatedAt      psql.Expression
	LastObserved   psql.Expression
}

func (c clusterColumns) Alias() string {
	return c.tableAlias
}

func (clusterColumns) AliasedAs(alias string) clusterColumns {
	return buildClusterColumns(alias)
}

// ClusterSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ClusterSetter struct {
	ID             omit.Val[uuid.UUID] `db:"id,pk" `
	OrganizationID omit.Val[uuid.UUID] `db:"organization_id" `
	ClusterGroupID omit.Val[uuid.UUID] `db:"cluster_group_id" `
	CreatedAt      omit.Val[time.Time] `db:"created_at" `
	UpdatedAt      omit.Val[time.Time] `db:"updated_at" `
	LastObserved   omit.Val[time.Time] `db:"last_observed" `
}

func (s ClusterSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.OrganizationID.IsValue() {
		vals = append(vals, "organization_id")
	}
	if s.ClusterGroupID.IsValue() {
		vals = append(vals, "cluster_group_id")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.LastObserved.IsValue() {
		vals = append(vals, "last_observed")
	}
	return vals
}

func (s ClusterSetter) Overwrite(t *Cluster) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.OrganizationID.IsValue() {
		t.OrganizationID = s.OrganizationID.MustGet()
	}
	if s.ClusterGroupID.IsValue() {
		t.ClusterGroupID = s.ClusterGroupID.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.LastObserved.IsValue() {
		t.LastObserved = s.LastObserved.MustGet()
	}
}

func (s *ClusterSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Clusters.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.OrganizationID.IsValue() {
			vals[1] = psql.Arg(s.OrganizationID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.ClusterGroupID.IsValue() {
			vals[2] = psql.Arg(s.ClusterGroupID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.LastObserved.IsValue() {
			vals[5] = psql.Arg(s.LastObserved.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ClusterSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ClusterSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.OrganizationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "organization_id")...),
			psql.Arg(s.OrganizationID),
		}})
	}

	if s.ClusterGroupID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cluster_group_id")...),
			psql.Arg(s.ClusterGroupID),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.LastObserved.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "last_observed")...),
			psql.Arg(s.LastObserved),
		}})
	}

	return exprs
}

// FindCluster retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCluster(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Cluster, error) {
	if len(cols) == 0 {
		return Clusters.Query(
			sm.Where(Clusters.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Clusters.Query(
		sm.Where(Clusters.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Clusters.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ClusterExists checks the presence of a single record by primary key
func ClusterExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Clusters.Query(
		sm.Where(Clusters.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Cluster is retrieved from the database
func (o *Cluster) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Clusters.AfterSelectHooks.RunHooks(ctx, exec, ClusterSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Clusters.AfterInsertHooks.RunHooks(ctx, exec, ClusterSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Clusters.AfterUpdateHooks.RunHooks(ctx, exec, ClusterSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Clusters.AfterDeleteHooks.RunHooks(ctx, exec, ClusterSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Cluster
func (o *Cluster) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Cluster) pkEQ() dialect.Expression {
	return psql.Quote("cluster", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Cluster
func (o *Cluster) Update(ctx context.Context, exec bob.Executor, s *ClusterSetter) error {
	v, err := Clusters.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Cluster record with an executor
func (o *Cluster) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Clusters.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Cluster using the executor
func (o *Cluster) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Clusters.Query(
		sm.Where(Clusters.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ClusterSlice is retrieved from the database
func (o ClusterSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Clusters.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Clusters.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Clusters.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Clusters.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ClusterSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("cluster", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ClusterSlice) copyMatchingRows(from ...*Cluster) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ClusterSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Clusters.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cluster:
				o.copyMatchingRows(retrieved)
			case []*Cluster:
				o.copyMatchingRows(retrieved...)
			case ClusterSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cluster or a slice of Cluster
				// then run the AfterUpdateHooks on the slice
				_, err = Clusters.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ClusterSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Clusters.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Cluster:
				o.copyMatchingRows(retrieved)
			case []*Cluster:
				o.copyMatchingRows(retrieved...)
			case ClusterSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Cluster or a slice of Cluster
				// then run the AfterDeleteHooks on the slice
				_, err = Clusters.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ClusterSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ClusterSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Clusters.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ClusterSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Clusters.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ClusterSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Clusters.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// ClusterGroup starts a query for related objects on cluster_group
func (o *Cluster) ClusterGroup(mods ...bob.Mod[*dialect.SelectQuery]) ClusterGroupsQuery {
	return ClusterGroups.Query(append(mods,
		sm.Where(ClusterGroups.Columns.ID.EQ(psql.Arg(o.ClusterGroupID))),
	)...)
}

func (os ClusterSlice) ClusterGroup(mods ...bob.Mod[*dialect.SelectQuery]) ClusterGroupsQuery {
	pkClusterGroupID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkClusterGroupID = append(pkClusterGroupID, o.ClusterGroupID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkClusterGroupID), "uuid[]")),
	))

	return ClusterGroups.Query(append(mods,
		sm.Where(psql.Group(ClusterGroups.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Organization starts a query for related objects on organization
func (o *Cluster) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	return Organizations.Query(append(mods,
		sm.Where(Organizations.Columns.ID.EQ(psql.Arg(o.OrganizationID))),
	)...)
}

func (os ClusterSlice) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	pkOrganizationID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkOrganizationID = append(pkOrganizationID, o.OrganizationID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkOrganizationID), "uuid[]")),
	))

	return Organizations.Query(append(mods,
		sm.Where(psql.Group(Organizations.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ClusterInfo starts a query for related objects on cluster_info
func (o *Cluster) ClusterInfo(mods ...bob.Mod[*dialect.SelectQuery]) ClusterInfosQuery {
	return ClusterInfos.Query(append(mods,
		sm.Where(ClusterInfos.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) ClusterInfo(mods ...bob.Mod[*dialect.SelectQuery]) ClusterInfosQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return ClusterInfos.Query(append(mods,
		sm.Where(psql.Group(ClusterInfos.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// ClusterTags starts a query for related objects on cluster_tag
func (o *Cluster) ClusterTags(mods ...bob.Mod[*dialect.SelectQuery]) ClusterTagsQuery {
	return ClusterTags.Query(append(mods,
		sm.Where(ClusterTags.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) ClusterTags(mods ...bob.Mod[*dialect.SelectQuery]) ClusterTagsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return ClusterTags.Query(append(mods,
		sm.Where(psql.Group(ClusterTags.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// ClusterUpgrade starts a query for related objects on cluster_upgrade
func (o *Cluster) ClusterUpgrade(mods ...bob.Mod[*dialect.SelectQuery]) ClusterUpgradesQuery {
	return ClusterUpgrades.Query(append(mods,
		sm.Where(ClusterUpgrades.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) ClusterUpgrade(mods ...bob.Mod[*dialect.SelectQuery]) ClusterUpgradesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return ClusterUpgrades.Query(append(mods,
		sm.Where(psql.Group(ClusterUpgrades.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// DeprecatedApis starts a query for related objects on deprecated_api
func (o *Cluster) DeprecatedApis(mods ...bob.Mod[*dialect.SelectQuery]) DeprecatedApisQuery {
	return DeprecatedApis.Query(append(mods,
		sm.Where(DeprecatedApis.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) DeprecatedApis(mods ...bob.Mod[*dialect.SelectQuery]) DeprecatedApisQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return DeprecatedApis.Query(append(mods,
		sm.Where(psql.Group(DeprecatedApis.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// Objects starts a query for related objects on object
func (o *Cluster) Objects(mods ...bob.Mod[*dialect.SelectQuery]) ObjectsQuery {
	return Objects.Query(append(mods,
		sm.Where(Objects.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) Objects(mods ...bob.Mod[*dialect.SelectQuery]) ObjectsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Objects.Query(append(mods,
		sm.Where(psql.Group(Objects.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// UnmatchedComponents starts a query for related objects on unmatched_component
func (o *Cluster) UnmatchedComponents(mods ...bob.Mod[*dialect.SelectQuery]) UnmatchedComponentsQuery {
	return UnmatchedComponents.Query(append(mods,
		sm.Where(UnmatchedComponents.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) UnmatchedComponents(mods ...bob.Mod[*dialect.SelectQuery]) UnmatchedComponentsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return UnmatchedComponents.Query(append(mods,
		sm.Where(psql.Group(UnmatchedComponents.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

// UpgradeableComponents starts a query for related objects on upgradeable_component
func (o *Cluster) UpgradeableComponents(mods ...bob.Mod[*dialect.SelectQuery]) UpgradeableComponentsQuery {
	return UpgradeableComponents.Query(append(mods,
		sm.Where(UpgradeableComponents.Columns.ClusterID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterSlice) UpgradeableComponents(mods ...bob.Mod[*dialect.SelectQuery]) UpgradeableComponentsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return UpgradeableComponents.Query(append(mods,
		sm.Where(psql.Group(UpgradeableComponents.Columns.ClusterID).OP("IN", PKArgExpr)),
	)...)
}

func attachClusterClusterGroup0(ctx context.Context, exec bob.Executor, count int, cluster0 *Cluster, clusterGroup1 *ClusterGroup) (*Cluster, error) {
	setter := &ClusterSetter{
		ClusterGroupID: omit.From(clusterGroup1.ID),
	}

	err := cluster0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterClusterGroup0: %w", err)
	}

	return cluster0, nil
}

func (cluster0 *Cluster) InsertClusterGroup(ctx context.Context, exec bob.Executor, related *ClusterGroupSetter) error {
	var err error

	clusterGroup1, err := ClusterGroups.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachClusterClusterGroup0(ctx, exec, 1, cluster0, clusterGroup1)
	if err != nil {
		return err
	}

	cluster0.R.ClusterGroup = clusterGroup1

	clusterGroup1.R.Clusters = append(clusterGroup1.R.Clusters, cluster0)

	return nil
}

func (cluster0 *Cluster) AttachClusterGroup(ctx context.Context, exec bob.Executor, clusterGroup1 *ClusterGroup) error {
	var err error

	_, err = attachClusterClusterGroup0(ctx, exec, 1, cluster0, clusterGroup1)
	if err != nil {
		return err
	}

	cluster0.R.ClusterGroup = clusterGroup1

	clusterGroup1.R.Clusters = append(clusterGroup1.R.Clusters, cluster0)

	return nil
}

func attachClusterOrganization0(ctx context.Context, exec bob.Executor, count int, cluster0 *Cluster, organization1 *Organization) (*Cluster, error) {
	setter := &ClusterSetter{
		OrganizationID: omit.From(organization1.ID),
	}

	err := cluster0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterOrganization0: %w", err)
	}

	return cluster0, nil
}

func (cluster0 *Cluster) InsertOrganization(ctx context.Context, exec bob.Executor, related *OrganizationSetter) error {
	var err error

	organization1, err := Organizations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachClusterOrganization0(ctx, exec, 1, cluster0, organization1)
	if err != nil {
		return err
	}

	cluster0.R.Organization = organization1

	organization1.R.Clusters = append(organization1.R.Clusters, cluster0)

	return nil
}

func (cluster0 *Cluster) AttachOrganization(ctx context.Context, exec bob.Executor, organization1 *Organization) error {
	var err error

	_, err = attachClusterOrganization0(ctx, exec, 1, cluster0, organization1)
	if err != nil {
		return err
	}

	cluster0.R.Organization = organization1

	organization1.R.Clusters = append(organization1.R.Clusters, cluster0)

	return nil
}

func insertClusterClusterInfo0(ctx context.Context, exec bob.Executor, clusterInfo1 *ClusterInfoSetter, cluster0 *Cluster) (*ClusterInfo, error) {
	clusterInfo1.ClusterID = omit.From(cluster0.ID)

	ret, err := ClusterInfos.Insert(clusterInfo1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterClusterInfo0: %w", err)
	}

	return ret, nil
}

func attachClusterClusterInfo0(ctx context.Context, exec bob.Executor, count int, clusterInfo1 *ClusterInfo, cluster0 *Cluster) (*ClusterInfo, error) {
	setter := &ClusterInfoSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := clusterInfo1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterClusterInfo0: %w", err)
	}

	return clusterInfo1, nil
}

func (cluster0 *Cluster) InsertClusterInfo(ctx context.Context, exec bob.Executor, related *ClusterInfoSetter) error {
	var err error

	clusterInfo1, err := insertClusterClusterInfo0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterInfo = clusterInfo1

	clusterInfo1.R.Cluster = cluster0

	return nil
}

func (cluster0 *Cluster) AttachClusterInfo(ctx context.Context, exec bob.Executor, clusterInfo1 *ClusterInfo) error {
	var err error

	_, err = attachClusterClusterInfo0(ctx, exec, 1, clusterInfo1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterInfo = clusterInfo1

	clusterInfo1.R.Cluster = cluster0

	return nil
}

func insertClusterClusterTags0(ctx context.Context, exec bob.Executor, clusterTags1 []*ClusterTagSetter, cluster0 *Cluster) (ClusterTagSlice, error) {
	for i := range clusterTags1 {
		clusterTags1[i].ClusterID = omit.From(cluster0.ID)
	}

	ret, err := ClusterTags.Insert(bob.ToMods(clusterTags1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterClusterTags0: %w", err)
	}

	return ret, nil
}

func attachClusterClusterTags0(ctx context.Context, exec bob.Executor, count int, clusterTags1 ClusterTagSlice, cluster0 *Cluster) (ClusterTagSlice, error) {
	setter := &ClusterTagSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := clusterTags1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterClusterTags0: %w", err)
	}

	return clusterTags1, nil
}

func (cluster0 *Cluster) InsertClusterTags(ctx context.Context, exec bob.Executor, related ...*ClusterTagSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	clusterTags1, err := insertClusterClusterTags0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterTags = append(cluster0.R.ClusterTags, clusterTags1...)

	for _, rel := range clusterTags1 {
		rel.R.Cluster = cluster0
	}
	return nil
}

func (cluster0 *Cluster) AttachClusterTags(ctx context.Context, exec bob.Executor, related ...*ClusterTag) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	clusterTags1 := ClusterTagSlice(related)

	_, err = attachClusterClusterTags0(ctx, exec, len(related), clusterTags1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterTags = append(cluster0.R.ClusterTags, clusterTags1...)

	for _, rel := range related {
		rel.R.Cluster = cluster0
	}

	return nil
}

func insertClusterClusterUpgrade0(ctx context.Context, exec bob.Executor, clusterUpgrade1 *ClusterUpgradeSetter, cluster0 *Cluster) (*ClusterUpgrade, error) {
	clusterUpgrade1.ClusterID = omit.From(cluster0.ID)

	ret, err := ClusterUpgrades.Insert(clusterUpgrade1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterClusterUpgrade0: %w", err)
	}

	return ret, nil
}

func attachClusterClusterUpgrade0(ctx context.Context, exec bob.Executor, count int, clusterUpgrade1 *ClusterUpgrade, cluster0 *Cluster) (*ClusterUpgrade, error) {
	setter := &ClusterUpgradeSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := clusterUpgrade1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterClusterUpgrade0: %w", err)
	}

	return clusterUpgrade1, nil
}

func (cluster0 *Cluster) InsertClusterUpgrade(ctx context.Context, exec bob.Executor, related *ClusterUpgradeSetter) error {
	var err error

	clusterUpgrade1, err := insertClusterClusterUpgrade0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterUpgrade = clusterUpgrade1

	clusterUpgrade1.R.Cluster = cluster0

	return nil
}

func (cluster0 *Cluster) AttachClusterUpgrade(ctx context.Context, exec bob.Executor, clusterUpgrade1 *ClusterUpgrade) error {
	var err error

	_, err = attachClusterClusterUpgrade0(ctx, exec, 1, clusterUpgrade1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.ClusterUpgrade = clusterUpgrade1

	clusterUpgrade1.R.Cluster = cluster0

	return nil
}

func insertClusterDeprecatedApis0(ctx context.Context, exec bob.Executor, deprecatedApis1 []*DeprecatedAPISetter, cluster0 *Cluster) (DeprecatedAPISlice, error) {
	for i := range deprecatedApis1 {
		deprecatedApis1[i].ClusterID = omit.From(cluster0.ID)
	}

	ret, err := DeprecatedApis.Insert(bob.ToMods(deprecatedApis1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterDeprecatedApis0: %w", err)
	}

	return ret, nil
}

func attachClusterDeprecatedApis0(ctx context.Context, exec bob.Executor, count int, deprecatedApis1 DeprecatedAPISlice, cluster0 *Cluster) (DeprecatedAPISlice, error) {
	setter := &DeprecatedAPISetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := deprecatedApis1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterDeprecatedApis0: %w", err)
	}

	return deprecatedApis1, nil
}

func (cluster0 *Cluster) InsertDeprecatedApis(ctx context.Context, exec bob.Executor, related ...*DeprecatedAPISetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	deprecatedApis1, err := insertClusterDeprecatedApis0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.DeprecatedApis = append(cluster0.R.DeprecatedApis, deprecatedApis1...)

	for _, rel := range deprecatedApis1 {
		rel.R.Cluster = cluster0
	}
	return nil
}

func (cluster0 *Cluster) AttachDeprecatedApis(ctx context.Context, exec bob.Executor, related ...*DeprecatedAPI) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	deprecatedApis1 := DeprecatedAPISlice(related)

	_, err = attachClusterDeprecatedApis0(ctx, exec, len(related), deprecatedApis1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.DeprecatedApis = append(cluster0.R.DeprecatedApis, deprecatedApis1...)

	for _, rel := range related {
		rel.R.Cluster = cluster0
	}

	return nil
}

func insertClusterObjects0(ctx context.Context, exec bob.Executor, objects1 []*ObjectSetter, cluster0 *Cluster) (ObjectSlice, error) {
	for i := range objects1 {
		objects1[i].ClusterID = omit.From(cluster0.ID)
	}

	ret, err := Objects.Insert(bob.ToMods(objects1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterObjects0: %w", err)
	}

	return ret, nil
}

func attachClusterObjects0(ctx context.Context, exec bob.Executor, count int, objects1 ObjectSlice, cluster0 *Cluster) (ObjectSlice, error) {
	setter := &ObjectSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := objects1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterObjects0: %w", err)
	}

	return objects1, nil
}

func (cluster0 *Cluster) InsertObjects(ctx context.Context, exec bob.Executor, related ...*ObjectSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	objects1, err := insertClusterObjects0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.Objects = append(cluster0.R.Objects, objects1...)

	for _, rel := range objects1 {
		rel.R.Cluster = cluster0
	}
	return nil
}

func (cluster0 *Cluster) AttachObjects(ctx context.Context, exec bob.Executor, related ...*Object) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	objects1 := ObjectSlice(related)

	_, err = attachClusterObjects0(ctx, exec, len(related), objects1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.Objects = append(cluster0.R.Objects, objects1...)

	for _, rel := range related {
		rel.R.Cluster = cluster0
	}

	return nil
}

func insertClusterUnmatchedComponents0(ctx context.Context, exec bob.Executor, unmatchedComponents1 []*UnmatchedComponentSetter, cluster0 *Cluster) (UnmatchedComponentSlice, error) {
	for i := range unmatchedComponents1 {
		unmatchedComponents1[i].ClusterID = omit.From(cluster0.ID)
	}

	ret, err := UnmatchedComponents.Insert(bob.ToMods(unmatchedComponents1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterUnmatchedComponents0: %w", err)
	}

	return ret, nil
}

func attachClusterUnmatchedComponents0(ctx context.Context, exec bob.Executor, count int, unmatchedComponents1 UnmatchedComponentSlice, cluster0 *Cluster) (UnmatchedComponentSlice, error) {
	setter := &UnmatchedComponentSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := unmatchedComponents1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterUnmatchedComponents0: %w", err)
	}

	return unmatchedComponents1, nil
}

func (cluster0 *Cluster) InsertUnmatchedComponents(ctx context.Context, exec bob.Executor, related ...*UnmatchedComponentSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	unmatchedComponents1, err := insertClusterUnmatchedComponents0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.UnmatchedComponents = append(cluster0.R.UnmatchedComponents, unmatchedComponents1...)

	for _, rel := range unmatchedComponents1 {
		rel.R.Cluster = cluster0
	}
	return nil
}

func (cluster0 *Cluster) AttachUnmatchedComponents(ctx context.Context, exec bob.Executor, related ...*UnmatchedComponent) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	unmatchedComponents1 := UnmatchedComponentSlice(related)

	_, err = attachClusterUnmatchedComponents0(ctx, exec, len(related), unmatchedComponents1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.UnmatchedComponents = append(cluster0.R.UnmatchedComponents, unmatchedComponents1...)

	for _, rel := range related {
		rel.R.Cluster = cluster0
	}

	return nil
}

func insertClusterUpgradeableComponents0(ctx context.Context, exec bob.Executor, upgradeableComponents1 []*UpgradeableComponentSetter, cluster0 *Cluster) (UpgradeableComponentSlice, error) {
	for i := range upgradeableComponents1 {
		upgradeableComponents1[i].ClusterID = omit.From(cluster0.ID)
	}

	ret, err := UpgradeableComponents.Insert(bob.ToMods(upgradeableComponents1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterUpgradeableComponents0: %w", err)
	}

	return ret, nil
}

func attachClusterUpgradeableComponents0(ctx context.Context, exec bob.Executor, count int, upgradeableComponents1 UpgradeableComponentSlice, cluster0 *Cluster) (UpgradeableComponentSlice, error) {
	setter := &UpgradeableComponentSetter{
		ClusterID: omit.From(cluster0.ID),
	}

	err := upgradeableComponents1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterUpgradeableComponents0: %w", err)
	}

	return upgradeableComponents1, nil
}

func (cluster0 *Cluster) InsertUpgradeableComponents(ctx context.Context, exec bob.Executor, related ...*UpgradeableComponentSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	upgradeableComponents1, err := insertClusterUpgradeableComponents0(ctx, exec, related, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.UpgradeableComponents = append(cluster0.R.UpgradeableComponents, upgradeableComponents1...)

	for _, rel := range upgradeableComponents1 {
		rel.R.Cluster = cluster0
	}
	return nil
}

func (cluster0 *Cluster) AttachUpgradeableComponents(ctx context.Context, exec bob.Executor, related ...*UpgradeableComponent) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	upgradeableComponents1 := UpgradeableComponentSlice(related)

	_, err = attachClusterUpgradeableComponents0(ctx, exec, len(related), upgradeableComponents1, cluster0)
	if err != nil {
		return err
	}

	cluster0.R.UpgradeableComponents = append(cluster0.R.UpgradeableComponents, upgradeableComponents1...)

	for _, rel := range related {
		rel.R.Cluster = cluster0
	}

	return nil
}

type clusterWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	OrganizationID psql.WhereMod[Q, uuid.UUID]
	ClusterGroupID psql.WhereMod[Q, uuid.UUID]
	CreatedAt      psql.WhereMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
	LastObserved   psql.WhereMod[Q, time.Time]
}

func (clusterWhere[Q]) AliasedAs(alias string) clusterWhere[Q] {
	return buildClusterWhere[Q](buildClusterColumns(alias))
}

func buildClusterWhere[Q psql.Filterable](cols clusterColumns) clusterWhere[Q] {
	return clusterWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](cols.ID),
		OrganizationID: psql.Where[Q, uuid.UUID](cols.OrganizationID),
		ClusterGroupID: psql.Where[Q, uuid.UUID](cols.ClusterGroupID),
		CreatedAt:      psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      psql.Where[Q, time.Time](cols.UpdatedAt),
		LastObserved:   psql.Where[Q, time.Time](cols.LastObserved),
	}
}

func (o *Cluster) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "ClusterGroup":
		rel, ok := retrieved.(*ClusterGroup)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.ClusterGroup = rel

		if rel != nil {
			rel.R.Clusters = ClusterSlice{o}
		}
		return nil
	case "Organization":
		rel, ok := retrieved.(*Organization)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.Organization = rel

		if rel != nil {
			rel.R.Clusters = ClusterSlice{o}
		}
		return nil
	case "ClusterInfo":
		rel, ok := retrieved.(*ClusterInfo)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.ClusterInfo = rel

		if rel != nil {
			rel.R.Cluster = o
		}
		return nil
	case "ClusterTags":
		rels, ok := retrieved.(ClusterTagSlice)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.ClusterTags = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cluster = o
			}
		}
		return nil
	case "ClusterUpgrade":
		rel, ok := retrieved.(*ClusterUpgrade)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.ClusterUpgrade = rel

		if rel != nil {
			rel.R.Cluster = o
		}
		return nil
	case "DeprecatedApis":
		rels, ok := retrieved.(DeprecatedAPISlice)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.DeprecatedApis = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cluster = o
			}
		}
		return nil
	case "Objects":
		rels, ok := retrieved.(ObjectSlice)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.Objects = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cluster = o
			}
		}
		return nil
	case "UnmatchedComponents":
		rels, ok := retrieved.(UnmatchedComponentSlice)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.UnmatchedComponents = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cluster = o
			}
		}
		return nil
	case "UpgradeableComponents":
		rels, ok := retrieved.(UpgradeableComponentSlice)
		if !ok {
			return fmt.Errorf("cluster cannot load %T as %q", retrieved, name)
		}

		o.R.UpgradeableComponents = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Cluster = o
			}
		}
		return nil
	default:
		return fmt.Errorf("cluster has no relationship %q", name)
	}
}

type clusterPreloader struct {
	ClusterGroup   func(...psql.PreloadOption) psql.Preloader
	Organization   func(...psql.PreloadOption) psql.Preloader
	ClusterInfo    func(...psql.PreloadOption) psql.Preloader
	ClusterUpgrade func(...psql.PreloadOption) psql.Preloader
}

func buildClusterPreloader() clusterPreloader {
	return clusterPreloader{
		ClusterGroup: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ClusterGroup, ClusterGroupSlice](psql.PreloadRel{
				Name: "ClusterGroup",
				Sides: []psql.PreloadSide{
					{
						From:        Clusters,
						To:          ClusterGroups,
						FromColumns: []string{"cluster_group_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, ClusterGroups.Columns.Names(), opts...)
		},
		Organization: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Organization, OrganizationSlice](psql.PreloadRel{
				Name: "Organization",
				Sides: []psql.PreloadSide{
					{
						From:        Clusters,
						To:          Organizations,
						FromColumns: []string{"organization_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Organizations.Columns.Names(), opts...)
		},
		ClusterInfo: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ClusterInfo, ClusterInfoSlice](psql.PreloadRel{
				Name: "ClusterInfo",
				Sides: []psql.PreloadSide{
					{
						From:        Clusters,
						To:          ClusterInfos,
						FromColumns: []string{"id"},
						ToColumns:   []string{"cluster_id"},
					},
				},
			}, ClusterInfos.Columns.Names(), opts...)
		},
		ClusterUpgrade: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*ClusterUpgrade, ClusterUpgradeSlice](psql.PreloadRel{
				Name: "ClusterUpgrade",
				Sides: []psql.PreloadSide{
					{
						From:        Clusters,
						To:          ClusterUpgrades,
						FromColumns: []string{"id"},
						ToColumns:   []string{"cluster_id"},
					},
				},
			}, ClusterUpgrades.Columns.Names(), opts...)
		},
	}
}

type clusterThenLoader[Q orm.Loadable] struct {
	ClusterGroup          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Organization          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ClusterInfo           func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ClusterTags           func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ClusterUpgrade        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	DeprecatedApis        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Objects               func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UnmatchedComponents   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	UpgradeableComponents func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildClusterThenLoader[Q orm.Loadable]() clusterThenLoader[Q] {
	type ClusterGroupLoadInterface interface {
		LoadClusterGroup(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationLoadInterface interface {
		LoadOrganization(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ClusterInfoLoadInterface interface {
		LoadClusterInfo(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ClusterTagsLoadInterface interface {
		LoadClusterTags(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ClusterUpgradeLoadInterface interface {
		LoadClusterUpgrade(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type DeprecatedApisLoadInterface interface {
		LoadDeprecatedApis(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ObjectsLoadInterface interface {
		LoadObjects(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UnmatchedComponentsLoadInterface interface {
		LoadUnmatchedComponents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type UpgradeableComponentsLoadInterface interface {
		LoadUpgradeableComponents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return clusterThenLoader[Q]{
		ClusterGroup: thenLoadBuilder[Q](
			"ClusterGroup",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterGroupLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadClusterGroup(ctx, exec, mods...)
			},
		),
		Organization: thenLoadBuilder[Q](
			"Organization",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganization(ctx, exec, mods...)
			},
		),
		ClusterInfo: thenLoadBuilder[Q](
			"ClusterInfo",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterInfoLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadClusterInfo(ctx, exec, mods...)
			},
		),
		ClusterTags: thenLoadBuilder[Q](
			"ClusterTags",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterTagsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadClusterTags(ctx, exec, mods...)
			},
		),
		ClusterUpgrade: thenLoadBuilder[Q](
			"ClusterUpgrade",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterUpgradeLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadClusterUpgrade(ctx, exec, mods...)
			},
		),
		DeprecatedApis: thenLoadBuilder[Q](
			"DeprecatedApis",
			func(ctx context.Context, exec bob.Executor, retrieved DeprecatedApisLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadDeprecatedApis(ctx, exec, mods...)
			},
		),
		Objects: thenLoadBuilder[Q](
			"Objects",
			func(ctx context.Context, exec bob.Executor, retrieved ObjectsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadObjects(ctx, exec, mods...)
			},
		),
		UnmatchedComponents: thenLoadBuilder[Q](
			"UnmatchedComponents",
			func(ctx context.Context, exec bob.Executor, retrieved UnmatchedComponentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUnmatchedComponents(ctx, exec, mods...)
			},
		),
		UpgradeableComponents: thenLoadBuilder[Q](
			"UpgradeableComponents",
			func(ctx context.Context, exec bob.Executor, retrieved UpgradeableComponentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadUpgradeableComponents(ctx, exec, mods...)
			},
		),
	}
}

// LoadClusterGroup loads the cluster's ClusterGroup into the .R struct
func (o *Cluster) LoadClusterGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ClusterGroup = nil

	related, err := o.ClusterGroup(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Clusters = ClusterSlice{o}

	o.R.ClusterGroup = related
	return nil
}

// LoadClusterGroup loads the cluster's ClusterGroup into the .R struct
func (os ClusterSlice) LoadClusterGroup(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusterGroups, err := os.ClusterGroup(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusterGroups {

			if !(o.ClusterGroupID == rel.ID) {
				continue
			}

			rel.R.Clusters = append(rel.R.Clusters, o)

			o.R.ClusterGroup = rel
			break
		}
	}

	return nil
}

// LoadOrganization loads the cluster's Organization into the .R struct
func (o *Cluster) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Organization = nil

	related, err := o.Organization(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Clusters = ClusterSlice{o}

	o.R.Organization = related
	return nil
}

// LoadOrganization loads the cluster's Organization into the .R struct
func (os ClusterSlice) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizations, err := os.Organization(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizations {

			if !(o.OrganizationID == rel.ID) {
				continue
			}

			rel.R.Clusters = append(rel.R.Clusters, o)

			o.R.Organization = rel
			break
		}
	}

	return nil
}

// LoadClusterInfo loads the cluster's ClusterInfo into the .R struct
func (o *Cluster) LoadClusterInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ClusterInfo = nil

	related, err := o.ClusterInfo(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Cluster = o

	o.R.ClusterInfo = related
	return nil
}

// LoadClusterInfo loads the cluster's ClusterInfo into the .R struct
func (os ClusterSlice) LoadClusterInfo(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusterInfos, err := os.ClusterInfo(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusterInfos {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.ClusterInfo = rel
			break
		}
	}

	return nil
}

// LoadClusterTags loads the cluster's ClusterTags into the .R struct
func (o *Cluster) LoadClusterTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ClusterTags = nil

	related, err := o.ClusterTags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cluster = o
	}

	o.R.ClusterTags = related
	return nil
}

// LoadClusterTags loads the cluster's ClusterTags into the .R struct
func (os ClusterSlice) LoadClusterTags(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusterTags, err := os.ClusterTags(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ClusterTags = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusterTags {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.ClusterTags = append(o.R.ClusterTags, rel)
		}
	}

	return nil
}

// LoadClusterUpgrade loads the cluster's ClusterUpgrade into the .R struct
func (o *Cluster) LoadClusterUpgrade(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ClusterUpgrade = nil

	related, err := o.ClusterUpgrade(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Cluster = o

	o.R.ClusterUpgrade = related
	return nil
}

// LoadClusterUpgrade loads the cluster's ClusterUpgrade into the .R struct
func (os ClusterSlice) LoadClusterUpgrade(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusterUpgrades, err := os.ClusterUpgrade(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusterUpgrades {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.ClusterUpgrade = rel
			break
		}
	}

	return nil
}

// LoadDeprecatedApis loads the cluster's DeprecatedApis into the .R struct
func (o *Cluster) LoadDeprecatedApis(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.DeprecatedApis = nil

	related, err := o.DeprecatedApis(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cluster = o
	}

	o.R.DeprecatedApis = related
	return nil
}

// LoadDeprecatedApis loads the cluster's DeprecatedApis into the .R struct
func (os ClusterSlice) LoadDeprecatedApis(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	deprecatedApis, err := os.DeprecatedApis(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.DeprecatedApis = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range deprecatedApis {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.DeprecatedApis = append(o.R.DeprecatedApis, rel)
		}
	}

	return nil
}

// LoadObjects loads the cluster's Objects into the .R struct
func (o *Cluster) LoadObjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Objects = nil

	related, err := o.Objects(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cluster = o
	}

	o.R.Objects = related
	return nil
}

// LoadObjects loads the cluster's Objects into the .R struct
func (os ClusterSlice) LoadObjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	objects, err := os.Objects(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Objects = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range objects {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.Objects = append(o.R.Objects, rel)
		}
	}

	return nil
}

// LoadUnmatchedComponents loads the cluster's UnmatchedComponents into the .R struct
func (o *Cluster) LoadUnmatchedComponents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UnmatchedComponents = nil

	related, err := o.UnmatchedComponents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cluster = o
	}

	o.R.UnmatchedComponents = related
	return nil
}

// LoadUnmatchedComponents loads the cluster's UnmatchedComponents into the .R struct
func (os ClusterSlice) LoadUnmatchedComponents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	unmatchedComponents, err := os.UnmatchedComponents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UnmatchedComponents = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range unmatchedComponents {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.UnmatchedComponents = append(o.R.UnmatchedComponents, rel)
		}
	}

	return nil
}

// LoadUpgradeableComponents loads the cluster's UpgradeableComponents into the .R struct
func (o *Cluster) LoadUpgradeableComponents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.UpgradeableComponents = nil

	related, err := o.UpgradeableComponents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Cluster = o
	}

	o.R.UpgradeableComponents = related
	return nil
}

// LoadUpgradeableComponents loads the cluster's UpgradeableComponents into the .R struct
func (os ClusterSlice) LoadUpgradeableComponents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	upgradeableComponents, err := os.UpgradeableComponents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.UpgradeableComponents = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range upgradeableComponents {

			if !(o.ID == rel.ClusterID) {
				continue
			}

			rel.R.Cluster = o

			o.R.UpgradeableComponents = append(o.R.UpgradeableComponents, rel)
		}
	}

	return nil
}

type clusterJoins[Q dialect.Joinable] struct {
	typ                   string
	ClusterGroup          modAs[Q, clusterGroupColumns]
	Organization          modAs[Q, organizationColumns]
	ClusterInfo           modAs[Q, clusterInfoColumns]
	ClusterTags           modAs[Q, clusterTagColumns]
	ClusterUpgrade        modAs[Q, clusterUpgradeColumns]
	DeprecatedApis        modAs[Q, deprecatedAPIColumns]
	Objects               modAs[Q, objectColumns]
	UnmatchedComponents   modAs[Q, unmatchedComponentColumns]
	UpgradeableComponents modAs[Q, upgradeableComponentColumns]
}

func (j clusterJoins[Q]) aliasedAs(alias string) clusterJoins[Q] {
	return buildClusterJoins[Q](buildClusterColumns(alias), j.typ)
}

func buildClusterJoins[Q dialect.Joinable](cols clusterColumns, typ string) clusterJoins[Q] {
	return clusterJoins[Q]{
		typ: typ,
		ClusterGroup: modAs[Q, clusterGroupColumns]{
			c: ClusterGroups.Columns,
			f: func(to clusterGroupColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ClusterGroups.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ClusterGroupID),
					))
				}

				return mods
			},
		},
		Organization: modAs[Q, organizationColumns]{
			c: Organizations.Columns,
			f: func(to organizationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Organizations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrganizationID),
					))
				}

				return mods
			},
		},
		ClusterInfo: modAs[Q, clusterInfoColumns]{
			c: ClusterInfos.Columns,
			f: func(to clusterInfoColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ClusterInfos.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ClusterTags: modAs[Q, clusterTagColumns]{
			c: ClusterTags.Columns,
			f: func(to clusterTagColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ClusterTags.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ClusterUpgrade: modAs[Q, clusterUpgradeColumns]{
			c: ClusterUpgrades.Columns,
			f: func(to clusterUpgradeColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ClusterUpgrades.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		DeprecatedApis: modAs[Q, deprecatedAPIColumns]{
			c: DeprecatedApis.Columns,
			f: func(to deprecatedAPIColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, DeprecatedApis.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Objects: modAs[Q, objectColumns]{
			c: Objects.Columns,
			f: func(to objectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Objects.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UnmatchedComponents: modAs[Q, unmatchedComponentColumns]{
			c: UnmatchedComponents.Columns,
			f: func(to unmatchedComponentColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UnmatchedComponents.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		UpgradeableComponents: modAs[Q, upgradeableComponentColumns]{
			c: UpgradeableComponents.Columns,
			f: func(to upgradeableComponentColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, UpgradeableComponents.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
