// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// ClusterGroup is an object representing the database table.
type ClusterGroup struct {
	ID             uuid.UUID `db:"id,pk" `
	OrganizationID uuid.UUID `db:"organization_id" `
	Name           string    `db:"name" `
	CreatedAt      time.Time `db:"created_at" `
	UpdatedAt      time.Time `db:"updated_at" `

	R clusterGroupR `db:"-" `
}

// ClusterGroupSlice is an alias for a slice of pointers to ClusterGroup.
// This should almost always be used instead of []*ClusterGroup.
type ClusterGroupSlice []*ClusterGroup

// ClusterGroups contains methods to work with the cluster_group table
var ClusterGroups = psql.NewTablex[*ClusterGroup, ClusterGroupSlice, *ClusterGroupSetter]("", "cluster_group", buildClusterGroupColumns("cluster_group"))

// ClusterGroupsQuery is a query on the cluster_group table
type ClusterGroupsQuery = *psql.ViewQuery[*ClusterGroup, ClusterGroupSlice]

// clusterGroupR is where relationships are stored.
type clusterGroupR struct {
	Clusters     ClusterSlice  // cluster.cluster_cluster_group_id_fkey
	Organization *Organization // cluster_group.cluster_group_organization_id_fkey
}

func buildClusterGroupColumns(alias string) clusterGroupColumns {
	return clusterGroupColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "organization_id", "name", "created_at", "updated_at",
		).WithParent("cluster_group"),
		tableAlias:     alias,
		ID:             psql.Quote(alias, "id"),
		OrganizationID: psql.Quote(alias, "organization_id"),
		Name:           psql.Quote(alias, "name"),
		CreatedAt:      psql.Quote(alias, "created_at"),
		UpdatedAt:      psql.Quote(alias, "updated_at"),
	}
}

type clusterGroupColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             psql.Expression
	OrganizationID psql.Expression
	Name           psql.Expression
	CreatedAt      psql.Expression
	UpdatedAt      psql.Expression
}

func (c clusterGroupColumns) Alias() string {
	return c.tableAlias
}

func (clusterGroupColumns) AliasedAs(alias string) clusterGroupColumns {
	return buildClusterGroupColumns(alias)
}

// ClusterGroupSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ClusterGroupSetter struct {
	ID             omit.Val[uuid.UUID] `db:"id,pk" `
	OrganizationID omit.Val[uuid.UUID] `db:"organization_id" `
	Name           omit.Val[string]    `db:"name" `
	CreatedAt      omit.Val[time.Time] `db:"created_at" `
	UpdatedAt      omit.Val[time.Time] `db:"updated_at" `
}

func (s ClusterGroupSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.OrganizationID.IsValue() {
		vals = append(vals, "organization_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ClusterGroupSetter) Overwrite(t *ClusterGroup) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.OrganizationID.IsValue() {
		t.OrganizationID = s.OrganizationID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *ClusterGroupSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ClusterGroups.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.OrganizationID.IsValue() {
			vals[1] = psql.Arg(s.OrganizationID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ClusterGroupSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ClusterGroupSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.OrganizationID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "organization_id")...),
			psql.Arg(s.OrganizationID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindClusterGroup retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindClusterGroup(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*ClusterGroup, error) {
	if len(cols) == 0 {
		return ClusterGroups.Query(
			sm.Where(ClusterGroups.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ClusterGroups.Query(
		sm.Where(ClusterGroups.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(ClusterGroups.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ClusterGroupExists checks the presence of a single record by primary key
func ClusterGroupExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return ClusterGroups.Query(
		sm.Where(ClusterGroups.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ClusterGroup is retrieved from the database
func (o *ClusterGroup) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClusterGroups.AfterSelectHooks.RunHooks(ctx, exec, ClusterGroupSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ClusterGroups.AfterInsertHooks.RunHooks(ctx, exec, ClusterGroupSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ClusterGroups.AfterUpdateHooks.RunHooks(ctx, exec, ClusterGroupSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ClusterGroups.AfterDeleteHooks.RunHooks(ctx, exec, ClusterGroupSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ClusterGroup
func (o *ClusterGroup) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *ClusterGroup) pkEQ() dialect.Expression {
	return psql.Quote("cluster_group", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ClusterGroup
func (o *ClusterGroup) Update(ctx context.Context, exec bob.Executor, s *ClusterGroupSetter) error {
	v, err := ClusterGroups.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single ClusterGroup record with an executor
func (o *ClusterGroup) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ClusterGroups.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ClusterGroup using the executor
func (o *ClusterGroup) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ClusterGroups.Query(
		sm.Where(ClusterGroups.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ClusterGroupSlice is retrieved from the database
func (o ClusterGroupSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ClusterGroups.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ClusterGroups.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ClusterGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ClusterGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ClusterGroupSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("cluster_group", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ClusterGroupSlice) copyMatchingRows(from ...*ClusterGroup) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ClusterGroupSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClusterGroups.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClusterGroup:
				o.copyMatchingRows(retrieved)
			case []*ClusterGroup:
				o.copyMatchingRows(retrieved...)
			case ClusterGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClusterGroup or a slice of ClusterGroup
				// then run the AfterUpdateHooks on the slice
				_, err = ClusterGroups.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ClusterGroupSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ClusterGroups.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ClusterGroup:
				o.copyMatchingRows(retrieved)
			case []*ClusterGroup:
				o.copyMatchingRows(retrieved...)
			case ClusterGroupSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ClusterGroup or a slice of ClusterGroup
				// then run the AfterDeleteHooks on the slice
				_, err = ClusterGroups.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ClusterGroupSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ClusterGroupSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClusterGroups.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ClusterGroupSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ClusterGroups.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ClusterGroupSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ClusterGroups.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Clusters starts a query for related objects on cluster
func (o *ClusterGroup) Clusters(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	return Clusters.Query(append(mods,
		sm.Where(Clusters.Columns.ClusterGroupID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ClusterGroupSlice) Clusters(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Clusters.Query(append(mods,
		sm.Where(psql.Group(Clusters.Columns.ClusterGroupID).OP("IN", PKArgExpr)),
	)...)
}

// Organization starts a query for related objects on organization
func (o *ClusterGroup) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	return Organizations.Query(append(mods,
		sm.Where(Organizations.Columns.ID.EQ(psql.Arg(o.OrganizationID))),
	)...)
}

func (os ClusterGroupSlice) Organization(mods ...bob.Mod[*dialect.SelectQuery]) OrganizationsQuery {
	pkOrganizationID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkOrganizationID = append(pkOrganizationID, o.OrganizationID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkOrganizationID), "uuid[]")),
	))

	return Organizations.Query(append(mods,
		sm.Where(psql.Group(Organizations.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertClusterGroupClusters0(ctx context.Context, exec bob.Executor, clusters1 []*ClusterSetter, clusterGroup0 *ClusterGroup) (ClusterSlice, error) {
	for i := range clusters1 {
		clusters1[i].ClusterGroupID = omit.From(clusterGroup0.ID)
	}

	ret, err := Clusters.Insert(bob.ToMods(clusters1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertClusterGroupClusters0: %w", err)
	}

	return ret, nil
}

func attachClusterGroupClusters0(ctx context.Context, exec bob.Executor, count int, clusters1 ClusterSlice, clusterGroup0 *ClusterGroup) (ClusterSlice, error) {
	setter := &ClusterSetter{
		ClusterGroupID: omit.From(clusterGroup0.ID),
	}

	err := clusters1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterGroupClusters0: %w", err)
	}

	return clusters1, nil
}

func (clusterGroup0 *ClusterGroup) InsertClusters(ctx context.Context, exec bob.Executor, related ...*ClusterSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	clusters1, err := insertClusterGroupClusters0(ctx, exec, related, clusterGroup0)
	if err != nil {
		return err
	}

	clusterGroup0.R.Clusters = append(clusterGroup0.R.Clusters, clusters1...)

	for _, rel := range clusters1 {
		rel.R.ClusterGroup = clusterGroup0
	}
	return nil
}

func (clusterGroup0 *ClusterGroup) AttachClusters(ctx context.Context, exec bob.Executor, related ...*Cluster) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	clusters1 := ClusterSlice(related)

	_, err = attachClusterGroupClusters0(ctx, exec, len(related), clusters1, clusterGroup0)
	if err != nil {
		return err
	}

	clusterGroup0.R.Clusters = append(clusterGroup0.R.Clusters, clusters1...)

	for _, rel := range related {
		rel.R.ClusterGroup = clusterGroup0
	}

	return nil
}

func attachClusterGroupOrganization0(ctx context.Context, exec bob.Executor, count int, clusterGroup0 *ClusterGroup, organization1 *Organization) (*ClusterGroup, error) {
	setter := &ClusterGroupSetter{
		OrganizationID: omit.From(organization1.ID),
	}

	err := clusterGroup0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachClusterGroupOrganization0: %w", err)
	}

	return clusterGroup0, nil
}

func (clusterGroup0 *ClusterGroup) InsertOrganization(ctx context.Context, exec bob.Executor, related *OrganizationSetter) error {
	var err error

	organization1, err := Organizations.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachClusterGroupOrganization0(ctx, exec, 1, clusterGroup0, organization1)
	if err != nil {
		return err
	}

	clusterGroup0.R.Organization = organization1

	organization1.R.ClusterGroups = append(organization1.R.ClusterGroups, clusterGroup0)

	return nil
}

func (clusterGroup0 *ClusterGroup) AttachOrganization(ctx context.Context, exec bob.Executor, organization1 *Organization) error {
	var err error

	_, err = attachClusterGroupOrganization0(ctx, exec, 1, clusterGroup0, organization1)
	if err != nil {
		return err
	}

	clusterGroup0.R.Organization = organization1

	organization1.R.ClusterGroups = append(organization1.R.ClusterGroups, clusterGroup0)

	return nil
}

type clusterGroupWhere[Q psql.Filterable] struct {
	ID             psql.WhereMod[Q, uuid.UUID]
	OrganizationID psql.WhereMod[Q, uuid.UUID]
	Name           psql.WhereMod[Q, string]
	CreatedAt      psql.WhereMod[Q, time.Time]
	UpdatedAt      psql.WhereMod[Q, time.Time]
}

func (clusterGroupWhere[Q]) AliasedAs(alias string) clusterGroupWhere[Q] {
	return buildClusterGroupWhere[Q](buildClusterGroupColumns(alias))
}

func buildClusterGroupWhere[Q psql.Filterable](cols clusterGroupColumns) clusterGroupWhere[Q] {
	return clusterGroupWhere[Q]{
		ID:             psql.Where[Q, uuid.UUID](cols.ID),
		OrganizationID: psql.Where[Q, uuid.UUID](cols.OrganizationID),
		Name:           psql.Where[Q, string](cols.Name),
		CreatedAt:      psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *ClusterGroup) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Clusters":
		rels, ok := retrieved.(ClusterSlice)
		if !ok {
			return fmt.Errorf("clusterGroup cannot load %T as %q", retrieved, name)
		}

		o.R.Clusters = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ClusterGroup = o
			}
		}
		return nil
	case "Organization":
		rel, ok := retrieved.(*Organization)
		if !ok {
			return fmt.Errorf("clusterGroup cannot load %T as %q", retrieved, name)
		}

		o.R.Organization = rel

		if rel != nil {
			rel.R.ClusterGroups = ClusterGroupSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("clusterGroup has no relationship %q", name)
	}
}

type clusterGroupPreloader struct {
	Organization func(...psql.PreloadOption) psql.Preloader
}

func buildClusterGroupPreloader() clusterGroupPreloader {
	return clusterGroupPreloader{
		Organization: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Organization, OrganizationSlice](psql.PreloadRel{
				Name: "Organization",
				Sides: []psql.PreloadSide{
					{
						From:        ClusterGroups,
						To:          Organizations,
						FromColumns: []string{"organization_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Organizations.Columns.Names(), opts...)
		},
	}
}

type clusterGroupThenLoader[Q orm.Loadable] struct {
	Clusters     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Organization func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildClusterGroupThenLoader[Q orm.Loadable]() clusterGroupThenLoader[Q] {
	type ClustersLoadInterface interface {
		LoadClusters(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrganizationLoadInterface interface {
		LoadOrganization(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return clusterGroupThenLoader[Q]{
		Clusters: thenLoadBuilder[Q](
			"Clusters",
			func(ctx context.Context, exec bob.Executor, retrieved ClustersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadClusters(ctx, exec, mods...)
			},
		),
		Organization: thenLoadBuilder[Q](
			"Organization",
			func(ctx context.Context, exec bob.Executor, retrieved OrganizationLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrganization(ctx, exec, mods...)
			},
		),
	}
}

// LoadClusters loads the clusterGroup's Clusters into the .R struct
func (o *ClusterGroup) LoadClusters(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Clusters = nil

	related, err := o.Clusters(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ClusterGroup = o
	}

	o.R.Clusters = related
	return nil
}

// LoadClusters loads the clusterGroup's Clusters into the .R struct
func (os ClusterGroupSlice) LoadClusters(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusters, err := os.Clusters(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Clusters = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusters {

			if !(o.ID == rel.ClusterGroupID) {
				continue
			}

			rel.R.ClusterGroup = o

			o.R.Clusters = append(o.R.Clusters, rel)
		}
	}

	return nil
}

// LoadOrganization loads the clusterGroup's Organization into the .R struct
func (o *ClusterGroup) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Organization = nil

	related, err := o.Organization(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ClusterGroups = ClusterGroupSlice{o}

	o.R.Organization = related
	return nil
}

// LoadOrganization loads the clusterGroup's Organization into the .R struct
func (os ClusterGroupSlice) LoadOrganization(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	organizations, err := os.Organization(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range organizations {

			if !(o.OrganizationID == rel.ID) {
				continue
			}

			rel.R.ClusterGroups = append(rel.R.ClusterGroups, o)

			o.R.Organization = rel
			break
		}
	}

	return nil
}

type clusterGroupJoins[Q dialect.Joinable] struct {
	typ          string
	Clusters     modAs[Q, clusterColumns]
	Organization modAs[Q, organizationColumns]
}

func (j clusterGroupJoins[Q]) aliasedAs(alias string) clusterGroupJoins[Q] {
	return buildClusterGroupJoins[Q](buildClusterGroupColumns(alias), j.typ)
}

func buildClusterGroupJoins[Q dialect.Joinable](cols clusterGroupColumns, typ string) clusterGroupJoins[Q] {
	return clusterGroupJoins[Q]{
		typ: typ,
		Clusters: modAs[Q, clusterColumns]{
			c: Clusters.Columns,
			f: func(to clusterColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Clusters.Name().As(to.Alias())).On(
						to.ClusterGroupID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Organization: modAs[Q, organizationColumns]{
			c: Organizations.Columns,
			f: func(to organizationColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Organizations.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrganizationID),
					))
				}

				return mods
			},
		},
	}
}
