// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// OAuth is an object representing the database table.
type OAuth struct {
	Email     string    `db:"email,pk" `
	Provider  string    `db:"provider" `
	CreatedAt time.Time `db:"created_at" `
	UpdatedAt time.Time `db:"updated_at" `
}

// OAuthSlice is an alias for a slice of pointers to OAuth.
// This should almost always be used instead of []*OAuth.
type OAuthSlice []*OAuth

// OAuths contains methods to work with the oauth table
var OAuths = psql.NewTablex[*OAuth, OAuthSlice, *OAuthSetter]("", "oauth", buildOAuthColumns("oauth"))

// OAuthsQuery is a query on the oauth table
type OAuthsQuery = *psql.ViewQuery[*OAuth, OAuthSlice]

func buildOAuthColumns(alias string) oauthColumns {
	return oauthColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"email", "provider", "created_at", "updated_at",
		).WithParent("oauth"),
		tableAlias: alias,
		Email:      psql.Quote(alias, "email"),
		Provider:   psql.Quote(alias, "provider"),
		CreatedAt:  psql.Quote(alias, "created_at"),
		UpdatedAt:  psql.Quote(alias, "updated_at"),
	}
}

type oauthColumns struct {
	expr.ColumnsExpr
	tableAlias string
	Email      psql.Expression
	Provider   psql.Expression
	CreatedAt  psql.Expression
	UpdatedAt  psql.Expression
}

func (c oauthColumns) Alias() string {
	return c.tableAlias
}

func (oauthColumns) AliasedAs(alias string) oauthColumns {
	return buildOAuthColumns(alias)
}

// OAuthSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OAuthSetter struct {
	Email     omit.Val[string]    `db:"email,pk" `
	Provider  omit.Val[string]    `db:"provider" `
	CreatedAt omit.Val[time.Time] `db:"created_at" `
	UpdatedAt omit.Val[time.Time] `db:"updated_at" `
}

func (s OAuthSetter) SetColumns() []string {
	vals := make([]string, 0, 4)
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Provider.IsValue() {
		vals = append(vals, "provider")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OAuthSetter) Overwrite(t *OAuth) {
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Provider.IsValue() {
		t.Provider = s.Provider.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *OAuthSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OAuths.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 4)
		if s.Email.IsValue() {
			vals[0] = psql.Arg(s.Email.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Provider.IsValue() {
			vals[1] = psql.Arg(s.Provider.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[2] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[3] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s OAuthSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s OAuthSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 4)

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Provider.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "provider")...),
			psql.Arg(s.Provider),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOAuth retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOAuth(ctx context.Context, exec bob.Executor, EmailPK string, cols ...string) (*OAuth, error) {
	if len(cols) == 0 {
		return OAuths.Query(
			sm.Where(OAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
		).One(ctx, exec)
	}

	return OAuths.Query(
		sm.Where(OAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
		sm.Columns(OAuths.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OAuthExists checks the presence of a single record by primary key
func OAuthExists(ctx context.Context, exec bob.Executor, EmailPK string) (bool, error) {
	return OAuths.Query(
		sm.Where(OAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OAuth is retrieved from the database
func (o *OAuth) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OAuths.AfterSelectHooks.RunHooks(ctx, exec, OAuthSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OAuths.AfterInsertHooks.RunHooks(ctx, exec, OAuthSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OAuths.AfterUpdateHooks.RunHooks(ctx, exec, OAuthSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OAuths.AfterDeleteHooks.RunHooks(ctx, exec, OAuthSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OAuth
func (o *OAuth) primaryKeyVals() bob.Expression {
	return psql.Arg(o.Email)
}

func (o *OAuth) pkEQ() dialect.Expression {
	return psql.Quote("oauth", "email").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OAuth
func (o *OAuth) Update(ctx context.Context, exec bob.Executor, s *OAuthSetter) error {
	v, err := OAuths.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single OAuth record with an executor
func (o *OAuth) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OAuths.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OAuth using the executor
func (o *OAuth) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OAuths.Query(
		sm.Where(OAuths.Columns.Email.EQ(psql.Arg(o.Email))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after OAuthSlice is retrieved from the database
func (o OAuthSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OAuths.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OAuths.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OAuths.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OAuths.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OAuthSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("oauth", "email").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OAuthSlice) copyMatchingRows(from ...*OAuth) {
	for i, old := range o {
		for _, new := range from {
			if new.Email != old.Email {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OAuthSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OAuths.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OAuth:
				o.copyMatchingRows(retrieved)
			case []*OAuth:
				o.copyMatchingRows(retrieved...)
			case OAuthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OAuth or a slice of OAuth
				// then run the AfterUpdateHooks on the slice
				_, err = OAuths.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OAuthSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OAuths.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OAuth:
				o.copyMatchingRows(retrieved)
			case []*OAuth:
				o.copyMatchingRows(retrieved...)
			case OAuthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OAuth or a slice of OAuth
				// then run the AfterDeleteHooks on the slice
				_, err = OAuths.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OAuthSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OAuthSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OAuths.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o OAuthSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OAuths.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OAuthSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OAuths.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type oauthWhere[Q psql.Filterable] struct {
	Email     psql.WhereMod[Q, string]
	Provider  psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
	UpdatedAt psql.WhereMod[Q, time.Time]
}

func (oauthWhere[Q]) AliasedAs(alias string) oauthWhere[Q] {
	return buildOAuthWhere[Q](buildOAuthColumns(alias))
}

func buildOAuthWhere[Q psql.Filterable](cols oauthColumns) oauthWhere[Q] {
	return oauthWhere[Q]{
		Email:     psql.Where[Q, string](cols.Email),
		Provider:  psql.Where[Q, string](cols.Provider),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt: psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
