// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// PasswordAuth is an object representing the database table.
type PasswordAuth struct {
	Email        string    `db:"email,pk" `
	PasswordHash string    `db:"password_hash" `
	PasswordSalt string    `db:"password_salt" `
	CreatedAt    time.Time `db:"created_at" `
	UpdatedAt    time.Time `db:"updated_at" `
}

// PasswordAuthSlice is an alias for a slice of pointers to PasswordAuth.
// This should almost always be used instead of []*PasswordAuth.
type PasswordAuthSlice []*PasswordAuth

// PasswordAuths contains methods to work with the password_auth table
var PasswordAuths = psql.NewTablex[*PasswordAuth, PasswordAuthSlice, *PasswordAuthSetter]("", "password_auth", buildPasswordAuthColumns("password_auth"))

// PasswordAuthsQuery is a query on the password_auth table
type PasswordAuthsQuery = *psql.ViewQuery[*PasswordAuth, PasswordAuthSlice]

func buildPasswordAuthColumns(alias string) passwordAuthColumns {
	return passwordAuthColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"email", "password_hash", "password_salt", "created_at", "updated_at",
		).WithParent("password_auth"),
		tableAlias:   alias,
		Email:        psql.Quote(alias, "email"),
		PasswordHash: psql.Quote(alias, "password_hash"),
		PasswordSalt: psql.Quote(alias, "password_salt"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type passwordAuthColumns struct {
	expr.ColumnsExpr
	tableAlias   string
	Email        psql.Expression
	PasswordHash psql.Expression
	PasswordSalt psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c passwordAuthColumns) Alias() string {
	return c.tableAlias
}

func (passwordAuthColumns) AliasedAs(alias string) passwordAuthColumns {
	return buildPasswordAuthColumns(alias)
}

// PasswordAuthSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PasswordAuthSetter struct {
	Email        omit.Val[string]    `db:"email,pk" `
	PasswordHash omit.Val[string]    `db:"password_hash" `
	PasswordSalt omit.Val[string]    `db:"password_salt" `
	CreatedAt    omit.Val[time.Time] `db:"created_at" `
	UpdatedAt    omit.Val[time.Time] `db:"updated_at" `
}

func (s PasswordAuthSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.PasswordHash.IsValue() {
		vals = append(vals, "password_hash")
	}
	if s.PasswordSalt.IsValue() {
		vals = append(vals, "password_salt")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s PasswordAuthSetter) Overwrite(t *PasswordAuth) {
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.PasswordHash.IsValue() {
		t.PasswordHash = s.PasswordHash.MustGet()
	}
	if s.PasswordSalt.IsValue() {
		t.PasswordSalt = s.PasswordSalt.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
}

func (s *PasswordAuthSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PasswordAuths.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.Email.IsValue() {
			vals[0] = psql.Arg(s.Email.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.PasswordHash.IsValue() {
			vals[1] = psql.Arg(s.PasswordHash.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.PasswordSalt.IsValue() {
			vals[2] = psql.Arg(s.PasswordSalt.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[3] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[4] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PasswordAuthSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PasswordAuthSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.PasswordHash.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password_hash")...),
			psql.Arg(s.PasswordHash),
		}})
	}

	if s.PasswordSalt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "password_salt")...),
			psql.Arg(s.PasswordSalt),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindPasswordAuth retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPasswordAuth(ctx context.Context, exec bob.Executor, EmailPK string, cols ...string) (*PasswordAuth, error) {
	if len(cols) == 0 {
		return PasswordAuths.Query(
			sm.Where(PasswordAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
		).One(ctx, exec)
	}

	return PasswordAuths.Query(
		sm.Where(PasswordAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
		sm.Columns(PasswordAuths.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PasswordAuthExists checks the presence of a single record by primary key
func PasswordAuthExists(ctx context.Context, exec bob.Executor, EmailPK string) (bool, error) {
	return PasswordAuths.Query(
		sm.Where(PasswordAuths.Columns.Email.EQ(psql.Arg(EmailPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PasswordAuth is retrieved from the database
func (o *PasswordAuth) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PasswordAuths.AfterSelectHooks.RunHooks(ctx, exec, PasswordAuthSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PasswordAuths.AfterInsertHooks.RunHooks(ctx, exec, PasswordAuthSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PasswordAuths.AfterUpdateHooks.RunHooks(ctx, exec, PasswordAuthSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PasswordAuths.AfterDeleteHooks.RunHooks(ctx, exec, PasswordAuthSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PasswordAuth
func (o *PasswordAuth) primaryKeyVals() bob.Expression {
	return psql.Arg(o.Email)
}

func (o *PasswordAuth) pkEQ() dialect.Expression {
	return psql.Quote("password_auth", "email").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PasswordAuth
func (o *PasswordAuth) Update(ctx context.Context, exec bob.Executor, s *PasswordAuthSetter) error {
	v, err := PasswordAuths.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single PasswordAuth record with an executor
func (o *PasswordAuth) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PasswordAuths.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PasswordAuth using the executor
func (o *PasswordAuth) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PasswordAuths.Query(
		sm.Where(PasswordAuths.Columns.Email.EQ(psql.Arg(o.Email))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after PasswordAuthSlice is retrieved from the database
func (o PasswordAuthSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PasswordAuths.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PasswordAuths.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PasswordAuths.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PasswordAuths.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PasswordAuthSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("password_auth", "email").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PasswordAuthSlice) copyMatchingRows(from ...*PasswordAuth) {
	for i, old := range o {
		for _, new := range from {
			if new.Email != old.Email {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PasswordAuthSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PasswordAuths.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PasswordAuth:
				o.copyMatchingRows(retrieved)
			case []*PasswordAuth:
				o.copyMatchingRows(retrieved...)
			case PasswordAuthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PasswordAuth or a slice of PasswordAuth
				// then run the AfterUpdateHooks on the slice
				_, err = PasswordAuths.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PasswordAuthSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PasswordAuths.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PasswordAuth:
				o.copyMatchingRows(retrieved)
			case []*PasswordAuth:
				o.copyMatchingRows(retrieved...)
			case PasswordAuthSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PasswordAuth or a slice of PasswordAuth
				// then run the AfterDeleteHooks on the slice
				_, err = PasswordAuths.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PasswordAuthSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PasswordAuthSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PasswordAuths.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PasswordAuthSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PasswordAuths.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PasswordAuthSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PasswordAuths.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type passwordAuthWhere[Q psql.Filterable] struct {
	Email        psql.WhereMod[Q, string]
	PasswordHash psql.WhereMod[Q, string]
	PasswordSalt psql.WhereMod[Q, string]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (passwordAuthWhere[Q]) AliasedAs(alias string) passwordAuthWhere[Q] {
	return buildPasswordAuthWhere[Q](buildPasswordAuthColumns(alias))
}

func buildPasswordAuthWhere[Q psql.Filterable](cols passwordAuthColumns) passwordAuthWhere[Q] {
	return passwordAuthWhere[Q]{
		Email:        psql.Where[Q, string](cols.Email),
		PasswordHash: psql.Where[Q, string](cols.PasswordHash),
		PasswordSalt: psql.Where[Q, string](cols.PasswordSalt),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}
