// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobmodel

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// UpgradeableComponent is an object representing the database table.
type UpgradeableComponent struct {
	ClusterID            uuid.UUID `db:"cluster_id,pk" `
	ObjectID             uuid.UUID `db:"object_id,pk" `
	Name                 string    `db:"name,pk" `
	Version              string    `db:"version" `
	NextCompatible       bool      `db:"next_compatible" `
	MinCompatibleVersion string    `db:"min_compatible_version" `
	MaxCompatibleVersion string    `db:"max_compatible_version" `
	CreatedAt            time.Time `db:"created_at" `
	UpdatedAt            time.Time `db:"updated_at" `
	RunVersion           uuid.UUID `db:"run_version" `

	R upgradeableComponentR `db:"-" `
}

// UpgradeableComponentSlice is an alias for a slice of pointers to UpgradeableComponent.
// This should almost always be used instead of []*UpgradeableComponent.
type UpgradeableComponentSlice []*UpgradeableComponent

// UpgradeableComponents contains methods to work with the upgradeable_component table
var UpgradeableComponents = psql.NewTablex[*UpgradeableComponent, UpgradeableComponentSlice, *UpgradeableComponentSetter]("", "upgradeable_component", buildUpgradeableComponentColumns("upgradeable_component"))

// UpgradeableComponentsQuery is a query on the upgradeable_component table
type UpgradeableComponentsQuery = *psql.ViewQuery[*UpgradeableComponent, UpgradeableComponentSlice]

// upgradeableComponentR is where relationships are stored.
type upgradeableComponentR struct {
	Cluster *Cluster // upgradeable_component.upgradeable_component_cluster_id_fkey
	Object  *Object  // upgradeable_component.upgradeable_component_cluster_id_object_id_fkey
}

func buildUpgradeableComponentColumns(alias string) upgradeableComponentColumns {
	return upgradeableComponentColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"cluster_id", "object_id", "name", "version", "next_compatible", "min_compatible_version", "max_compatible_version", "created_at", "updated_at", "run_version",
		).WithParent("upgradeable_component"),
		tableAlias:           alias,
		ClusterID:            psql.Quote(alias, "cluster_id"),
		ObjectID:             psql.Quote(alias, "object_id"),
		Name:                 psql.Quote(alias, "name"),
		Version:              psql.Quote(alias, "version"),
		NextCompatible:       psql.Quote(alias, "next_compatible"),
		MinCompatibleVersion: psql.Quote(alias, "min_compatible_version"),
		MaxCompatibleVersion: psql.Quote(alias, "max_compatible_version"),
		CreatedAt:            psql.Quote(alias, "created_at"),
		UpdatedAt:            psql.Quote(alias, "updated_at"),
		RunVersion:           psql.Quote(alias, "run_version"),
	}
}

type upgradeableComponentColumns struct {
	expr.ColumnsExpr
	tableAlias           string
	ClusterID            psql.Expression
	ObjectID             psql.Expression
	Name                 psql.Expression
	Version              psql.Expression
	NextCompatible       psql.Expression
	MinCompatibleVersion psql.Expression
	MaxCompatibleVersion psql.Expression
	CreatedAt            psql.Expression
	UpdatedAt            psql.Expression
	RunVersion           psql.Expression
}

func (c upgradeableComponentColumns) Alias() string {
	return c.tableAlias
}

func (upgradeableComponentColumns) AliasedAs(alias string) upgradeableComponentColumns {
	return buildUpgradeableComponentColumns(alias)
}

// UpgradeableComponentSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UpgradeableComponentSetter struct {
	ClusterID            omit.Val[uuid.UUID] `db:"cluster_id,pk" `
	ObjectID             omit.Val[uuid.UUID] `db:"object_id,pk" `
	Name                 omit.Val[string]    `db:"name,pk" `
	Version              omit.Val[string]    `db:"version" `
	NextCompatible       omit.Val[bool]      `db:"next_compatible" `
	MinCompatibleVersion omit.Val[string]    `db:"min_compatible_version" `
	MaxCompatibleVersion omit.Val[string]    `db:"max_compatible_version" `
	CreatedAt            omit.Val[time.Time] `db:"created_at" `
	UpdatedAt            omit.Val[time.Time] `db:"updated_at" `
	RunVersion           omit.Val[uuid.UUID] `db:"run_version" `
}

func (s UpgradeableComponentSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ClusterID.IsValue() {
		vals = append(vals, "cluster_id")
	}
	if s.ObjectID.IsValue() {
		vals = append(vals, "object_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Version.IsValue() {
		vals = append(vals, "version")
	}
	if s.NextCompatible.IsValue() {
		vals = append(vals, "next_compatible")
	}
	if s.MinCompatibleVersion.IsValue() {
		vals = append(vals, "min_compatible_version")
	}
	if s.MaxCompatibleVersion.IsValue() {
		vals = append(vals, "max_compatible_version")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt.IsValue() {
		vals = append(vals, "updated_at")
	}
	if s.RunVersion.IsValue() {
		vals = append(vals, "run_version")
	}
	return vals
}

func (s UpgradeableComponentSetter) Overwrite(t *UpgradeableComponent) {
	if s.ClusterID.IsValue() {
		t.ClusterID = s.ClusterID.MustGet()
	}
	if s.ObjectID.IsValue() {
		t.ObjectID = s.ObjectID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Version.IsValue() {
		t.Version = s.Version.MustGet()
	}
	if s.NextCompatible.IsValue() {
		t.NextCompatible = s.NextCompatible.MustGet()
	}
	if s.MinCompatibleVersion.IsValue() {
		t.MinCompatibleVersion = s.MinCompatibleVersion.MustGet()
	}
	if s.MaxCompatibleVersion.IsValue() {
		t.MaxCompatibleVersion = s.MaxCompatibleVersion.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.UpdatedAt.IsValue() {
		t.UpdatedAt = s.UpdatedAt.MustGet()
	}
	if s.RunVersion.IsValue() {
		t.RunVersion = s.RunVersion.MustGet()
	}
}

func (s *UpgradeableComponentSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UpgradeableComponents.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ClusterID.IsValue() {
			vals[0] = psql.Arg(s.ClusterID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ObjectID.IsValue() {
			vals[1] = psql.Arg(s.ObjectID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Version.IsValue() {
			vals[3] = psql.Arg(s.Version.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.NextCompatible.IsValue() {
			vals[4] = psql.Arg(s.NextCompatible.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.MinCompatibleVersion.IsValue() {
			vals[5] = psql.Arg(s.MinCompatibleVersion.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.MaxCompatibleVersion.IsValue() {
			vals[6] = psql.Arg(s.MaxCompatibleVersion.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt.IsValue() {
			vals[8] = psql.Arg(s.UpdatedAt.MustGet())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.RunVersion.IsValue() {
			vals[9] = psql.Arg(s.RunVersion.MustGet())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UpgradeableComponentSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UpgradeableComponentSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ClusterID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cluster_id")...),
			psql.Arg(s.ClusterID),
		}})
	}

	if s.ObjectID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "object_id")...),
			psql.Arg(s.ObjectID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Version.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "version")...),
			psql.Arg(s.Version),
		}})
	}

	if s.NextCompatible.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "next_compatible")...),
			psql.Arg(s.NextCompatible),
		}})
	}

	if s.MinCompatibleVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "min_compatible_version")...),
			psql.Arg(s.MinCompatibleVersion),
		}})
	}

	if s.MaxCompatibleVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "max_compatible_version")...),
			psql.Arg(s.MaxCompatibleVersion),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.RunVersion.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "run_version")...),
			psql.Arg(s.RunVersion),
		}})
	}

	return exprs
}

// FindUpgradeableComponent retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUpgradeableComponent(ctx context.Context, exec bob.Executor, ClusterIDPK uuid.UUID, ObjectIDPK uuid.UUID, NamePK string, cols ...string) (*UpgradeableComponent, error) {
	if len(cols) == 0 {
		return UpgradeableComponents.Query(
			sm.Where(UpgradeableComponents.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
			sm.Where(UpgradeableComponents.Columns.ObjectID.EQ(psql.Arg(ObjectIDPK))),
			sm.Where(UpgradeableComponents.Columns.Name.EQ(psql.Arg(NamePK))),
		).One(ctx, exec)
	}

	return UpgradeableComponents.Query(
		sm.Where(UpgradeableComponents.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
		sm.Where(UpgradeableComponents.Columns.ObjectID.EQ(psql.Arg(ObjectIDPK))),
		sm.Where(UpgradeableComponents.Columns.Name.EQ(psql.Arg(NamePK))),
		sm.Columns(UpgradeableComponents.Columns.Only(cols...)),
	).One(ctx, exec)
}

// UpgradeableComponentExists checks the presence of a single record by primary key
func UpgradeableComponentExists(ctx context.Context, exec bob.Executor, ClusterIDPK uuid.UUID, ObjectIDPK uuid.UUID, NamePK string) (bool, error) {
	return UpgradeableComponents.Query(
		sm.Where(UpgradeableComponents.Columns.ClusterID.EQ(psql.Arg(ClusterIDPK))),
		sm.Where(UpgradeableComponents.Columns.ObjectID.EQ(psql.Arg(ObjectIDPK))),
		sm.Where(UpgradeableComponents.Columns.Name.EQ(psql.Arg(NamePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UpgradeableComponent is retrieved from the database
func (o *UpgradeableComponent) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UpgradeableComponents.AfterSelectHooks.RunHooks(ctx, exec, UpgradeableComponentSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UpgradeableComponents.AfterInsertHooks.RunHooks(ctx, exec, UpgradeableComponentSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UpgradeableComponents.AfterUpdateHooks.RunHooks(ctx, exec, UpgradeableComponentSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UpgradeableComponents.AfterDeleteHooks.RunHooks(ctx, exec, UpgradeableComponentSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the UpgradeableComponent
func (o *UpgradeableComponent) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.ClusterID,
		o.ObjectID,
		o.Name,
	)
}

func (o *UpgradeableComponent) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("upgradeable_component", "cluster_id"), psql.Quote("upgradeable_component", "object_id"), psql.Quote("upgradeable_component", "name")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UpgradeableComponent
func (o *UpgradeableComponent) Update(ctx context.Context, exec bob.Executor, s *UpgradeableComponentSetter) error {
	v, err := UpgradeableComponents.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UpgradeableComponent record with an executor
func (o *UpgradeableComponent) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UpgradeableComponents.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UpgradeableComponent using the executor
func (o *UpgradeableComponent) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UpgradeableComponents.Query(
		sm.Where(UpgradeableComponents.Columns.ClusterID.EQ(psql.Arg(o.ClusterID))),
		sm.Where(UpgradeableComponents.Columns.ObjectID.EQ(psql.Arg(o.ObjectID))),
		sm.Where(UpgradeableComponents.Columns.Name.EQ(psql.Arg(o.Name))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UpgradeableComponentSlice is retrieved from the database
func (o UpgradeableComponentSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UpgradeableComponents.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UpgradeableComponents.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UpgradeableComponents.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UpgradeableComponents.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UpgradeableComponentSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("upgradeable_component", "cluster_id"), psql.Quote("upgradeable_component", "object_id"), psql.Quote("upgradeable_component", "name")).In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UpgradeableComponentSlice) copyMatchingRows(from ...*UpgradeableComponent) {
	for i, old := range o {
		for _, new := range from {
			if new.ClusterID != old.ClusterID {
				continue
			}
			if new.ObjectID != old.ObjectID {
				continue
			}
			if new.Name != old.Name {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UpgradeableComponentSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UpgradeableComponents.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UpgradeableComponent:
				o.copyMatchingRows(retrieved)
			case []*UpgradeableComponent:
				o.copyMatchingRows(retrieved...)
			case UpgradeableComponentSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UpgradeableComponent or a slice of UpgradeableComponent
				// then run the AfterUpdateHooks on the slice
				_, err = UpgradeableComponents.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UpgradeableComponentSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UpgradeableComponents.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UpgradeableComponent:
				o.copyMatchingRows(retrieved)
			case []*UpgradeableComponent:
				o.copyMatchingRows(retrieved...)
			case UpgradeableComponentSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UpgradeableComponent or a slice of UpgradeableComponent
				// then run the AfterDeleteHooks on the slice
				_, err = UpgradeableComponents.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UpgradeableComponentSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UpgradeableComponentSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UpgradeableComponents.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UpgradeableComponentSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UpgradeableComponents.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UpgradeableComponentSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UpgradeableComponents.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Cluster starts a query for related objects on cluster
func (o *UpgradeableComponent) Cluster(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	return Clusters.Query(append(mods,
		sm.Where(Clusters.Columns.ID.EQ(psql.Arg(o.ClusterID))),
	)...)
}

func (os UpgradeableComponentSlice) Cluster(mods ...bob.Mod[*dialect.SelectQuery]) ClustersQuery {
	pkClusterID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkClusterID = append(pkClusterID, o.ClusterID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkClusterID), "uuid[]")),
	))

	return Clusters.Query(append(mods,
		sm.Where(psql.Group(Clusters.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Object starts a query for related objects on object
func (o *UpgradeableComponent) Object(mods ...bob.Mod[*dialect.SelectQuery]) ObjectsQuery {
	return Objects.Query(append(mods,
		sm.Where(Objects.Columns.ClusterID.EQ(psql.Arg(o.ClusterID))), sm.Where(Objects.Columns.ID.EQ(psql.Arg(o.ObjectID))),
	)...)
}

func (os UpgradeableComponentSlice) Object(mods ...bob.Mod[*dialect.SelectQuery]) ObjectsQuery {
	pkClusterID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkObjectID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkClusterID = append(pkClusterID, o.ClusterID)
		pkObjectID = append(pkObjectID, o.ObjectID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkClusterID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkObjectID), "uuid[]")),
	))

	return Objects.Query(append(mods,
		sm.Where(psql.Group(Objects.Columns.ClusterID, Objects.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachUpgradeableComponentCluster0(ctx context.Context, exec bob.Executor, count int, upgradeableComponent0 *UpgradeableComponent, cluster1 *Cluster) (*UpgradeableComponent, error) {
	setter := &UpgradeableComponentSetter{
		ClusterID: omit.From(cluster1.ID),
	}

	err := upgradeableComponent0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUpgradeableComponentCluster0: %w", err)
	}

	return upgradeableComponent0, nil
}

func (upgradeableComponent0 *UpgradeableComponent) InsertCluster(ctx context.Context, exec bob.Executor, related *ClusterSetter) error {
	var err error

	cluster1, err := Clusters.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUpgradeableComponentCluster0(ctx, exec, 1, upgradeableComponent0, cluster1)
	if err != nil {
		return err
	}

	upgradeableComponent0.R.Cluster = cluster1

	cluster1.R.UpgradeableComponents = append(cluster1.R.UpgradeableComponents, upgradeableComponent0)

	return nil
}

func (upgradeableComponent0 *UpgradeableComponent) AttachCluster(ctx context.Context, exec bob.Executor, cluster1 *Cluster) error {
	var err error

	_, err = attachUpgradeableComponentCluster0(ctx, exec, 1, upgradeableComponent0, cluster1)
	if err != nil {
		return err
	}

	upgradeableComponent0.R.Cluster = cluster1

	cluster1.R.UpgradeableComponents = append(cluster1.R.UpgradeableComponents, upgradeableComponent0)

	return nil
}

func attachUpgradeableComponentObject0(ctx context.Context, exec bob.Executor, count int, upgradeableComponent0 *UpgradeableComponent, object1 *Object) (*UpgradeableComponent, error) {
	setter := &UpgradeableComponentSetter{
		ClusterID: omit.From(object1.ClusterID),
		ObjectID:  omit.From(object1.ID),
	}

	err := upgradeableComponent0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUpgradeableComponentObject0: %w", err)
	}

	return upgradeableComponent0, nil
}

func (upgradeableComponent0 *UpgradeableComponent) InsertObject(ctx context.Context, exec bob.Executor, related *ObjectSetter) error {
	var err error

	object1, err := Objects.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUpgradeableComponentObject0(ctx, exec, 1, upgradeableComponent0, object1)
	if err != nil {
		return err
	}

	upgradeableComponent0.R.Object = object1

	object1.R.UpgradeableComponents = append(object1.R.UpgradeableComponents, upgradeableComponent0)

	return nil
}

func (upgradeableComponent0 *UpgradeableComponent) AttachObject(ctx context.Context, exec bob.Executor, object1 *Object) error {
	var err error

	_, err = attachUpgradeableComponentObject0(ctx, exec, 1, upgradeableComponent0, object1)
	if err != nil {
		return err
	}

	upgradeableComponent0.R.Object = object1

	object1.R.UpgradeableComponents = append(object1.R.UpgradeableComponents, upgradeableComponent0)

	return nil
}

type upgradeableComponentWhere[Q psql.Filterable] struct {
	ClusterID            psql.WhereMod[Q, uuid.UUID]
	ObjectID             psql.WhereMod[Q, uuid.UUID]
	Name                 psql.WhereMod[Q, string]
	Version              psql.WhereMod[Q, string]
	NextCompatible       psql.WhereMod[Q, bool]
	MinCompatibleVersion psql.WhereMod[Q, string]
	MaxCompatibleVersion psql.WhereMod[Q, string]
	CreatedAt            psql.WhereMod[Q, time.Time]
	UpdatedAt            psql.WhereMod[Q, time.Time]
	RunVersion           psql.WhereMod[Q, uuid.UUID]
}

func (upgradeableComponentWhere[Q]) AliasedAs(alias string) upgradeableComponentWhere[Q] {
	return buildUpgradeableComponentWhere[Q](buildUpgradeableComponentColumns(alias))
}

func buildUpgradeableComponentWhere[Q psql.Filterable](cols upgradeableComponentColumns) upgradeableComponentWhere[Q] {
	return upgradeableComponentWhere[Q]{
		ClusterID:            psql.Where[Q, uuid.UUID](cols.ClusterID),
		ObjectID:             psql.Where[Q, uuid.UUID](cols.ObjectID),
		Name:                 psql.Where[Q, string](cols.Name),
		Version:              psql.Where[Q, string](cols.Version),
		NextCompatible:       psql.Where[Q, bool](cols.NextCompatible),
		MinCompatibleVersion: psql.Where[Q, string](cols.MinCompatibleVersion),
		MaxCompatibleVersion: psql.Where[Q, string](cols.MaxCompatibleVersion),
		CreatedAt:            psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:            psql.Where[Q, time.Time](cols.UpdatedAt),
		RunVersion:           psql.Where[Q, uuid.UUID](cols.RunVersion),
	}
}

func (o *UpgradeableComponent) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Cluster":
		rel, ok := retrieved.(*Cluster)
		if !ok {
			return fmt.Errorf("upgradeableComponent cannot load %T as %q", retrieved, name)
		}

		o.R.Cluster = rel

		if rel != nil {
			rel.R.UpgradeableComponents = UpgradeableComponentSlice{o}
		}
		return nil
	case "Object":
		rel, ok := retrieved.(*Object)
		if !ok {
			return fmt.Errorf("upgradeableComponent cannot load %T as %q", retrieved, name)
		}

		o.R.Object = rel

		if rel != nil {
			rel.R.UpgradeableComponents = UpgradeableComponentSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("upgradeableComponent has no relationship %q", name)
	}
}

type upgradeableComponentPreloader struct {
	Cluster func(...psql.PreloadOption) psql.Preloader
	Object  func(...psql.PreloadOption) psql.Preloader
}

func buildUpgradeableComponentPreloader() upgradeableComponentPreloader {
	return upgradeableComponentPreloader{
		Cluster: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Cluster, ClusterSlice](psql.PreloadRel{
				Name: "Cluster",
				Sides: []psql.PreloadSide{
					{
						From:        UpgradeableComponents,
						To:          Clusters,
						FromColumns: []string{"cluster_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Clusters.Columns.Names(), opts...)
		},
		Object: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Object, ObjectSlice](psql.PreloadRel{
				Name: "Object",
				Sides: []psql.PreloadSide{
					{
						From:        UpgradeableComponents,
						To:          Objects,
						FromColumns: []string{"cluster_id", "object_id"},
						ToColumns:   []string{"cluster_id", "id"},
					},
				},
			}, Objects.Columns.Names(), opts...)
		},
	}
}

type upgradeableComponentThenLoader[Q orm.Loadable] struct {
	Cluster func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Object  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildUpgradeableComponentThenLoader[Q orm.Loadable]() upgradeableComponentThenLoader[Q] {
	type ClusterLoadInterface interface {
		LoadCluster(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ObjectLoadInterface interface {
		LoadObject(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return upgradeableComponentThenLoader[Q]{
		Cluster: thenLoadBuilder[Q](
			"Cluster",
			func(ctx context.Context, exec bob.Executor, retrieved ClusterLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCluster(ctx, exec, mods...)
			},
		),
		Object: thenLoadBuilder[Q](
			"Object",
			func(ctx context.Context, exec bob.Executor, retrieved ObjectLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadObject(ctx, exec, mods...)
			},
		),
	}
}

// LoadCluster loads the upgradeableComponent's Cluster into the .R struct
func (o *UpgradeableComponent) LoadCluster(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Cluster = nil

	related, err := o.Cluster(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UpgradeableComponents = UpgradeableComponentSlice{o}

	o.R.Cluster = related
	return nil
}

// LoadCluster loads the upgradeableComponent's Cluster into the .R struct
func (os UpgradeableComponentSlice) LoadCluster(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	clusters, err := os.Cluster(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range clusters {

			if !(o.ClusterID == rel.ID) {
				continue
			}

			rel.R.UpgradeableComponents = append(rel.R.UpgradeableComponents, o)

			o.R.Cluster = rel
			break
		}
	}

	return nil
}

// LoadObject loads the upgradeableComponent's Object into the .R struct
func (o *UpgradeableComponent) LoadObject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Object = nil

	related, err := o.Object(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UpgradeableComponents = UpgradeableComponentSlice{o}

	o.R.Object = related
	return nil
}

// LoadObject loads the upgradeableComponent's Object into the .R struct
func (os UpgradeableComponentSlice) LoadObject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	objects, err := os.Object(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range objects {

			if !(o.ClusterID == rel.ClusterID) {
				continue
			}

			if !(o.ObjectID == rel.ID) {
				continue
			}

			rel.R.UpgradeableComponents = append(rel.R.UpgradeableComponents, o)

			o.R.Object = rel
			break
		}
	}

	return nil
}

type upgradeableComponentJoins[Q dialect.Joinable] struct {
	typ     string
	Cluster modAs[Q, clusterColumns]
	Object  modAs[Q, objectColumns]
}

func (j upgradeableComponentJoins[Q]) aliasedAs(alias string) upgradeableComponentJoins[Q] {
	return buildUpgradeableComponentJoins[Q](buildUpgradeableComponentColumns(alias), j.typ)
}

func buildUpgradeableComponentJoins[Q dialect.Joinable](cols upgradeableComponentColumns, typ string) upgradeableComponentJoins[Q] {
	return upgradeableComponentJoins[Q]{
		typ: typ,
		Cluster: modAs[Q, clusterColumns]{
			c: Clusters.Columns,
			f: func(to clusterColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Clusters.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ClusterID),
					))
				}

				return mods
			},
		},
		Object: modAs[Q, objectColumns]{
			c: Objects.Columns,
			f: func(to objectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Objects.Name().As(to.Alias())).On(
						to.ClusterID.EQ(cols.ClusterID), to.ID.EQ(cols.ObjectID),
					))
				}

				return mods
			},
		},
	}
}
